/**
 * AgriNex - Wholesale Buyer Module Data Store
 */

const buyerData = {
  profile: {
    name: "Karthik Sundaram",
    role: "Procurement Lead",
    company: "BigBasket Direct Farm Sourcing",
    location: "Hosur Hub, Tamil Nadu",
    avatar: "assets/images/farmer-avatar.jpg",
    notificationsCount: 3,
    messagesCount: 2
  },
  stats: {
    totalDemands: 4,
    demandsSubtitle: "Active procurement quotas",
    matchedLots: 8,
    matchedLotsSubtitle: "Verified farmer lots in radius",
    activeShipments: 2,
    shipmentSubtitle: "Consignments in transit",
    costSavings: "₹ 46,200",
    savingsSubtitle: "Saved vs traditional mandi middlemen"
  },
  verifiedLots: [
    {
      id: "LOT-TOM-88",
      crop: "Tomato (Shivam Hybrid)",
      category: "Vegetables",
      farmerName: "Murugan P.",
      farmerLocation: "Dindigul, TN",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 94431-22901",
      image: "assets/images/tomato.jpg",
      grade: "Grade A (70%)",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      quantity: "50 Qt (5,000 kg)",
      qtyNum: 50,
      askPrice: "₹ 12.00 /kg (₹ 1,200 /Qt)",
      priceNum: 1200,
      mandiRate: "₹ 13.20 /kg (₹ 1,320 /Qt)",
      savings: "9.1% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "82.5%"
    },
    {
      id: "LOT-ONI-44",
      crop: "Red Onion (Nashik Export)",
      category: "Vegetables",
      farmerName: "Patil Rameshwar",
      farmerLocation: "Nashik, MH",
      farmerRating: "4.8 ⭐",
      farmerPhone: "+91 98220-44911",
      image: "assets/images/onion.jpg",
      grade: "Grade A (80%)",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      quantity: "80 Qt (8,000 kg)",
      qtyNum: 80,
      askPrice: "₹ 18.00 /kg (₹ 1,800 /Qt)",
      priceNum: 1800,
      mandiRate: "₹ 20.50 /kg (₹ 2,050 /Qt)",
      savings: "12.2% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "68.0%"
    },
    {
      id: "LOT-PAD-19",
      crop: "1121 Basmati Paddy",
      category: "Grains",
      farmerName: "Venkatesh Rao",
      farmerLocation: "Karnal, HR",
      farmerRating: "4.95 ⭐",
      farmerPhone: "+91 98120-33410",
      image: "assets/images/paddy.jpg",
      grade: "Grade A (85%)",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      quantity: "120 Qt (12,000 kg)",
      qtyNum: 120,
      askPrice: "₹ 24.00 /kg (₹ 2,400 /Qt)",
      priceNum: 2400,
      mandiRate: "₹ 26.50 /kg (₹ 2,650 /Qt)",
      savings: "9.4% Lower",
      status: "Counter Received",
      statusBadgeClass: "badge-status-negotiation",
      moisture: "12.0%"
    },
    {
      id: "LOT-COT-31",
      crop: "Long Staple Cotton",
      category: "Cash Crops",
      farmerName: "Kaliamurthi R",
      farmerLocation: "Guntur, AP",
      farmerRating: "4.75 ⭐",
      farmerPhone: "+91 98480-11234",
      image: "assets/images/cotton.jpg",
      grade: "Grade B (65%)",
      gradeKey: "grade-b",
      gradeBadgeClass: "badge-grade-b",
      quantity: "40 Qt (4,000 kg)",
      qtyNum: 40,
      askPrice: "₹ 56.00 /kg (₹ 5,600 /Qt)",
      priceNum: 5600,
      mandiRate: "₹ 59.00 /kg (₹ 5,900 /Qt)",
      savings: "5.1% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "8.5%"
    },
    {
      id: "LOT-TUR-55",
      crop: "Salem Turmeric Finger",
      category: "Cash Crops",
      farmerName: "M. Shanmugam",
      farmerLocation: "Salem, TN",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 94432-88190",
      image: "assets/images/wheat-logo.png",
      grade: "Grade A (90%)",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      quantity: "60 Qt (6,000 kg)",
      qtyNum: 60,
      askPrice: "₹ 142.00 /kg (₹ 14,200 /Qt)",
      priceNum: 14200,
      mandiRate: "₹ 154.00 /kg (₹ 15,400 /Qt)",
      savings: "7.8% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "9.2%"
    },
    {
      id: "LOT-CHL-12",
      crop: "Guntur Red Chilli (Teja)",
      category: "Cash Crops",
      farmerName: "N. Sambasiva Rao",
      farmerLocation: "Guntur, AP",
      farmerRating: "4.85 ⭐",
      farmerPhone: "+91 98481-99882",
      image: "assets/images/tomato.jpg",
      grade: "Grade B (60%)",
      gradeKey: "grade-b",
      gradeBadgeClass: "badge-grade-b",
      quantity: "35 Qt (3,500 kg)",
      qtyNum: 35,
      askPrice: "₹ 185.00 /kg (₹ 18,500 /Qt)",
      priceNum: 18500,
      mandiRate: "₹ 198.00 /kg (₹ 19,800 /Qt)",
      savings: "6.5% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "10.0%"
    },
    {
      id: "LOT-POT-77",
      crop: "Jyoti Processing Potato",
      category: "Vegetables",
      farmerName: "Gurpreet Singh",
      farmerLocation: "Jalandhar, PB",
      farmerRating: "4.7 ⭐",
      farmerPhone: "+91 98140-55219",
      image: "assets/images/onion.jpg",
      grade: "Grade C (Processing)",
      gradeKey: "grade-c",
      gradeBadgeClass: "badge-grade-c",
      quantity: "150 Qt (15,000 kg)",
      qtyNum: 150,
      askPrice: "₹ 8.50 /kg (₹ 850 /Qt)",
      priceNum: 850,
      mandiRate: "₹ 9.80 /kg (₹ 980 /Qt)",
      savings: "13.3% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "78.0%"
    },
    {
      id: "LOT-BAN-90",
      crop: "Grand Naine Banana",
      category: "Fruits",
      farmerName: "K. Selvaraj",
      farmerLocation: "Theni, TN",
      farmerRating: "4.92 ⭐",
      farmerPhone: "+91 94430-66712",
      image: "assets/images/paddy.jpg",
      grade: "Grade A (Export)",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      quantity: "90 Qt (9,000 kg)",
      qtyNum: 90,
      askPrice: "₹ 16.50 /kg (₹ 1,650 /Qt)",
      priceNum: 1650,
      mandiRate: "₹ 18.20 /kg (₹ 1,820 /Qt)",
      savings: "9.3% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "75.0%"
    }
  ],
  buyerDemands: [
    {
      id: "DEM-BB-101",
      crop: "Tomato (Hybrid)",
      image: "assets/images/tomato.jpg",
      tonnage: "15 MT (150 Qt)",
      targetPrice: "₹ 12.20 /kg (₹ 1,220 /Qt)",
      location: "Hosur Hub, TN",
      deadline: "18 Sep 2026",
      matchedCount: 3,
      status: "Active"
    },
    {
      id: "DEM-BB-102",
      crop: "Red Onion",
      image: "assets/images/onion.jpg",
      tonnage: "25 MT (250 Qt)",
      targetPrice: "₹ 18.50 /kg (₹ 1,850 /Qt)",
      location: "Navi Mumbai Hub",
      deadline: "22 Sep 2026",
      matchedCount: 5,
      status: "Active"
    }
  ],
  mandiPrices: [
    {
      crop: "Tomato",
      currentPrice: "₹ 11.50 /kg (₹ 1,150 /Qt)",
      trendPercent: "+6.2%",
      direction: "up",
      trendPoints: [20, 16, 18, 12, 14, 8, 4]
    },
    {
      crop: "Onion",
      currentPrice: "₹ 9.00 /kg (₹ 900 /Qt)",
      trendPercent: "+4.8%",
      direction: "up",
      trendPoints: [22, 19, 16, 14, 11, 7, 5]
    },
    {
      crop: "Paddy",
      currentPrice: "₹ 20.00 /kg (₹ 2,000 /Qt)",
      trendPercent: "+3.5%",
      direction: "up",
      trendPoints: [18, 17, 19, 15, 12, 9, 7]
    },
    {
      crop: "Cotton",
      currentPrice: "₹ 58.00 /kg (₹ 5,800 /Qt)",
      trendPercent: "-1.2%",
      direction: "down",
      trendPoints: [5, 8, 12, 9, 14, 18, 22]
    }
  ],
  activeContract: {
    contractId: "ESC-BB-9921",
    crop: "Tomato (Shivam Hybrid)",
    quantity: "50 Qt",
    farmerName: "Murugan Palanisamy",
    image: "assets/images/tomato.jpg",
    totalAmount: "₹ 60,000",
    advanceLocked: "₹ 21,000 (35%)",
    balanceDue: "₹ 39,000 (65%)",
    status: "Consignment Dispatched",
    trackingId: "TRK-EXP-9921-TN",
    currentStep: 2 // 1: Contract, 2: Advance Locked, 3: Dispatched, 4: Settled
  },
  grievances: [
    {
      id: "GRV-2026-981",
      consignmentId: "TRK-EXP-9921-TN",
      crop: "Tomato (Shivam Hybrid)",
      category: "Quality Defect (Moisture Deviation)",
      farmerName: "Murugan Palanisamy",
      amountUnderHold: "₹ 39,000 (65% Balance Held)",
      status: "Under Review",
      statusClass: "badge-status-negotiation",
      dateFiled: "12 Sep 2026",
      resolutionEta: "Within 4 Hours",
      description: "Arrival moisture index measured 88.5% at Hosur receiving dock vs agreed certified threshold 82.5%. Requesting 5% quality price revision.",
      timeline: [
        { step: "Grievance Raised", done: true, time: "12 Sep, 10:15 AM" },
        { step: "Escrow Settlement Frozen", done: true, time: "12 Sep, 10:16 AM" },
        { step: "AI Assay & Photo Review", done: true, time: "12 Sep, 11:30 AM" },
        { step: "Arbitrator Decision", done: false, time: "Pending" }
      ]
    },
    {
      id: "GRV-2026-744",
      consignmentId: "TRK-KA-3310-TATA",
      crop: "Red Onion (Nashik Quality)",
      category: "Weight Shortage",
      farmerName: "Patil Rameshwar",
      amountUnderHold: "₹ 14,200",
      status: "Resolved & Refunded",
      statusClass: "badge-grade-a",
      dateFiled: "08 Sep 2026",
      resolutionEta: "Closed",
      description: "Weighbridge weight recorded 76.5 Qt vs 80 Qt dispatch slip. Partial escrow refund of ₹ 6,300 disbursed to buyer account.",
      timeline: [
        { step: "Grievance Raised", done: true, time: "08 Sep, 02:00 PM" },
        { step: "Escrow Frozen", done: true, time: "08 Sep, 02:02 PM" },
        { step: "Weighbridge Slip Verified", done: true, time: "08 Sep, 03:45 PM" },
        { step: "Partial Refund Settled", done: true, time: "08 Sep, 04:30 PM" }
      ]
    }
  ]
};
