/**
 * AgriNex - Wholesale Buyer Module Data Store
 * Grounded in Maharashtra Agricultural Hubs, APMC Mandis, and Regional Produce
 */

const buyerData = {
  profile: {
    name: "Karthik Sundaram",
    role: "Procurement Lead",
    company: "BigBasket Direct Farm Sourcing (Maharashtra Division)",
    location: "Vashi APMC Central Terminal, Navi Mumbai, Maharashtra",
    avatar: "assets/images/farmer-avatar.jpg",
    notificationsCount: 3,
    messagesCount: 2
  },
  stats: {
    totalDemands: 6,
    demandsSubtitle: "Active procurement quotas",
    matchedLots: 8,
    matchedLotsSubtitle: "Verified farmer lots in radius",
    activeShipments: 3,
    shipmentSubtitle: "Consignments in transit",
    costSavings: "₹ 4,82,000",
    savingsSubtitle: "Saved vs traditional mandi middlemen"
  },
  verifiedLots: [
    {
      id: "LOT-ONI-01",
      crop: "Red Onion (Nashik Garwa Quality)",
      category: "Vegetables",
      farmerName: "Patil Rameshwar",
      farmerLocation: "Lasalgaon APMC Yard, Nashik ~ 2.4 km away",
      farmerRating: "4.92 ⭐",
      farmerPhone: "+91 98220-44911",
      image: "assets/images/onion.jpg",
      grade: "Grade A Export Calibrated",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 18.00,
      availableQtyKg: 10000,
      quantity: "100 Qt (10,000 kg)",
      qtyNum: 100,
      askPrice: "₹ 18.00 /kg (₹ 1,800 /Qt)",
      priceNum: 1800,
      mandiRate: "₹ 20.50 /kg (₹ 2,050 /Qt)",
      savings: "12.2% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "13.5%"
    },
    {
      id: "LOT-TOM-02",
      crop: "Tomato (Shivam / Abhinav Hybrid)",
      category: "Vegetables",
      farmerName: "Sanjay Deshmukh",
      farmerLocation: "Narayangaon Mandi Yard, Junnar, Pune ~ 3.2 km away",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 98224-33100",
      image: "assets/images/tomato.jpg",
      grade: "Grade A",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 13.00,
      availableQtyKg: 6000,
      quantity: "60 Qt (6,000 kg)",
      qtyNum: 60,
      askPrice: "₹ 13.00 /kg (₹ 1,300 /Qt)",
      priceNum: 1300,
      mandiRate: "₹ 15.00 /kg (₹ 1,500 /Qt)",
      savings: "13.3% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "82.0%"
    },
    {
      id: "LOT-BAN-03",
      crop: "Grand Naine Banana (GI Khandesh Export)",
      category: "Fruits",
      farmerName: "Rajesh Shinde",
      farmerLocation: "Raver APMC Hub, Jalgaon ~ 4.5 km away",
      farmerRating: "4.95 ⭐",
      farmerPhone: "+91 98500-11234",
      image: "assets/images/banana.jpg",
      grade: "Grade A Export Calibrated",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 14.50,
      availableQtyKg: 12000,
      quantity: "120 Qt (12,000 kg)",
      qtyNum: 120,
      askPrice: "₹ 14.50 /kg (₹ 1,450 /Qt)",
      priceNum: 1450,
      mandiRate: "₹ 16.80 /kg (₹ 1,680 /Qt)",
      savings: "13.7% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "76.0%"
    },
    {
      id: "LOT-SOY-04",
      crop: "Yellow Soybean (JS 335 / High Protein)",
      category: "Grains & Cereals",
      farmerName: "Anandrao Jadhav",
      farmerLocation: "Latur Mega APMC Yard, Marathwada ~ 1.8 km away",
      farmerRating: "4.88 ⭐",
      farmerPhone: "+91 98231-55890",
      image: "assets/images/wheat-logo.png",
      grade: "Grade A",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 42.00,
      availableQtyKg: 15000,
      quantity: "150 Qt (15,000 kg)",
      qtyNum: 150,
      askPrice: "₹ 42.00 /kg (₹ 4,200 /Qt)",
      priceNum: 4200,
      mandiRate: "₹ 47.50 /kg (₹ 4,750 /Qt)",
      savings: "11.6% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "9.5%"
    },
    {
      id: "LOT-ORG-05",
      crop: "Nagpur Orange / Santra (GI Vidarbha Quality)",
      category: "Fruits",
      farmerName: "Vikas Wankhede",
      farmerLocation: "Katol Mandi Yard, Nagpur ~ 12.0 km away",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 98222-33104",
      image: "assets/images/orange.jpg",
      grade: "Grade A Table / Export",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 38.00,
      availableQtyKg: 8000,
      quantity: "80 Qt (8,000 kg)",
      qtyNum: 80,
      askPrice: "₹ 38.00 /kg (₹ 3,800 /Qt)",
      priceNum: 3800,
      mandiRate: "₹ 44.00 /kg (₹ 4,400 /Qt)",
      savings: "13.6% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "85.0%"
    },
    {
      id: "LOT-TUR-06",
      crop: "Sangli Rajapuri Turmeric Finger",
      category: "Spices & High-Value",
      farmerName: "Kavita Thorat",
      farmerLocation: "Sangli APMC Turmeric Terminal ~ 2.1 km away",
      farmerRating: "4.95 ⭐",
      farmerPhone: "+91 98228-88190",
      image: "assets/images/turmeric.jpg",
      grade: "Double Polished Export Grade",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 135.00,
      availableQtyKg: 5000,
      quantity: "50 Qt (5,000 kg)",
      qtyNum: 50,
      askPrice: "₹ 135.00 /kg (₹ 13,500 /Qt)",
      priceNum: 13500,
      mandiRate: "₹ 152.00 /kg (₹ 15,200 /Qt)",
      savings: "11.2% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "8.8%"
    },
    {
      id: "LOT-POM-07",
      crop: "Bhagwa Pomegranate (Solapur Export Grade)",
      category: "Fruits",
      farmerName: "Sunil Chavan",
      farmerLocation: "Pandharpur Yard, Solapur ~ 5.4 km away",
      farmerRating: "4.85 ⭐",
      farmerPhone: "+91 98226-44102",
      image: "assets/images/pomegranate.jpg",
      grade: "Grade A (250g+ Calibrated)",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 88.00,
      availableQtyKg: 4000,
      quantity: "40 Qt (4,000 kg)",
      qtyNum: 40,
      askPrice: "₹ 88.00 /kg (₹ 8,800 /Qt)",
      priceNum: 8800,
      mandiRate: "₹ 102.00 /kg (₹ 10,200 /Qt)",
      savings: "13.7% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "80.0%"
    },
    {
      id: "LOT-COT-08",
      crop: "Raw Cotton (Vidarbha Long Staple)",
      category: "Cash Crops",
      farmerName: "Balasaheb More",
      farmerLocation: "Amravati APMC Cotton Yard ~ 8.0 km away",
      farmerRating: "4.8 ⭐",
      farmerPhone: "+91 98225-77890",
      image: "assets/images/cotton.jpg",
      grade: "Grade A Staple >29mm",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 62.00,
      availableQtyKg: 9000,
      quantity: "90 Qt (9,000 kg)",
      qtyNum: 90,
      askPrice: "₹ 62.00 /kg (₹ 6,200 /Qt)",
      priceNum: 6200,
      mandiRate: "₹ 69.50 /kg (₹ 6,950 /Qt)",
      savings: "10.8% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "8.2%"
    }
  ],
  buyerDemands: [
    {
      id: "DEM-BB-101",
      crop: "Red Onion (Nashik Garwa Export Grade)",
      category: "Vegetables",
      image: "assets/images/onion.jpg",
      tonnage: "250 Qt (25,000 kg)",
      tonnageNum: 250,
      unit: "Qt",
      targetPrice: "₹ 1,820 /Qt",
      targetPriceNum: 1820,
      pricePerKg: 18.20,
      mandiBenchmark: "₹ 2,120 /Qt",
      savingsPct: "14.2% Savings",
      location: "Vashi Terminal, Navi Mumbai (MH)",
      deadline: "22 Sep 2026",
      daysLeft: 8,
      matchedCount: 5,
      fulfilledTonnage: 180,
      fulfilledPct: 72,
      status: "Active Matching",
      statusClass: "badge-status-open",
      statusLabel: "⚡ 5 Farmer Bids (Auto-Match Ready)",
      grade: "Grade A (45-55mm Export Calibrated)",
      moistureLimit: "Max 13.5% Moisture • Sun Cured Skin",
      deliveryMode: "Farm-Gate Pickup (AgriNex Transit)",
      escrowAdvance: "35% Advance (₹ 1,59,250)",
      bids: [
        {
          bidId: "BID-ONI-901",
          farmerName: "Patil Rameshwar",
          farmerAvatar: "assets/images/onion.jpg",
          farmerPhone: "+91 98220-44911",
          location: "Lasalgaon, Nashik (Direct Mandi Lot)",
          rating: "4.92 ⭐",
          offeredQty: "100 Qt (10,000 kg)",
          bidPrice: "₹ 1,800 /Qt",
          bidPriceNum: 1800,
          pricePerKg: 18.00,
          qcScore: "98% (Export Certified)",
          leadTime: "6 Hours",
          status: "Verified Top Match"
        },
        {
          bidId: "BID-ONI-902",
          farmerName: "Nitin Shinde",
          farmerAvatar: "assets/images/onion.jpg",
          farmerPhone: "+91 98221-55440",
          location: "Pimpalgaon Baswant, Nashik (22 km away)",
          rating: "4.88 ⭐",
          offeredQty: "80 Qt (8,000 kg)",
          bidPrice: "₹ 1,810 /Qt",
          bidPriceNum: 1810,
          pricePerKg: 18.10,
          qcScore: "95% (Grade A)",
          leadTime: "8 Hours",
          status: "Available"
        }
      ]
    },
    {
      id: "DEM-BB-102",
      crop: "Tomato (Pune Junnar / Narayangaon Hybrid)",
      category: "Vegetables",
      image: "assets/images/tomato.jpg",
      tonnage: "150 Qt (15,000 kg)",
      tonnageNum: 150,
      unit: "Qt",
      targetPrice: "₹ 1,250 /Qt",
      targetPriceNum: 1250,
      pricePerKg: 12.50,
      mandiBenchmark: "₹ 1,450 /Qt",
      savingsPct: "13.8% Savings",
      location: "Pune APMC Gultekdi Hub, MH",
      deadline: "19 Sep 2026",
      daysLeft: 5,
      matchedCount: 4,
      fulfilledTonnage: 110,
      fulfilledPct: 73,
      status: "Active Matching",
      statusClass: "badge-status-open",
      statusLabel: "⚡ 4 Farmer Bids (Auto-Match Ready)",
      grade: "Grade A Firm Salad / Export",
      moistureLimit: "Max 82% Moisture • Brix > 4.8%",
      deliveryMode: "Crates in Reefer Truck",
      escrowAdvance: "35% Advance (₹ 65,625)",
      bids: [
        {
          bidId: "BID-TOM-801",
          farmerName: "Sanjay Deshmukh",
          farmerAvatar: "assets/images/tomato.jpg",
          farmerPhone: "+91 98224-33100",
          location: "Manchar, Pune (18 km away)",
          rating: "4.9 ⭐",
          offeredQty: "60 Qt (6,000 kg)",
          bidPrice: "₹ 1,240 /Qt",
          bidPriceNum: 1240,
          pricePerKg: 12.40,
          qcScore: "96% (Grade A)",
          leadTime: "4 Hours",
          status: "Top Match"
        },
        {
          bidId: "BID-TOM-802",
          farmerName: "Ganesh Walke",
          farmerAvatar: "assets/images/tomato.jpg",
          farmerPhone: "+91 98225-88190",
          location: "Narayangaon, Junnar (24 km away)",
          rating: "4.85 ⭐",
          offeredQty: "50 Qt (5,000 kg)",
          bidPrice: "₹ 1,250 /Qt",
          bidPriceNum: 1250,
          pricePerKg: 12.50,
          qcScore: "94% (Grade A)",
          leadTime: "6 Hours",
          status: "Available"
        }
      ]
    },
    {
      id: "DEM-BB-103",
      crop: "Grand Naine Banana (Khandesh Export Pack)",
      category: "Fruits",
      image: "assets/images/banana.jpg",
      tonnage: "200 Qt (20,000 kg)",
      tonnageNum: 200,
      unit: "Qt",
      targetPrice: "₹ 1,400 /Qt",
      targetPriceNum: 1400,
      pricePerKg: 14.00,
      mandiBenchmark: "₹ 1,650 /Qt",
      savingsPct: "15.2% Savings",
      location: "Vashi APMC Central Yard, Navi Mumbai",
      deadline: "24 Sep 2026",
      daysLeft: 10,
      matchedCount: 3,
      fulfilledTonnage: 120,
      fulfilledPct: 60,
      status: "Active Matching",
      statusClass: "badge-status-open",
      statusLabel: "⚡ 3 Farmer Bids (Auto-Match Ready)",
      grade: "Grade A Export Calibrated (7-8 hands)",
      moistureLimit: "Green Mature 75-80% RH Packed",
      deliveryMode: "Chilled Temperature Truck",
      escrowAdvance: "35% Advance (₹ 98,000)",
      bids: [
        {
          bidId: "BID-BAN-701",
          farmerName: "Rajesh Shinde",
          farmerAvatar: "assets/images/banana.jpg",
          farmerPhone: "+91 98500-11234",
          location: "Raver, Jalgaon (Direct Agro Hub)",
          rating: "4.95 ⭐",
          offeredQty: "120 Qt (12,000 kg)",
          bidPrice: "₹ 1,380 /Qt",
          bidPriceNum: 1380,
          pricePerKg: 13.80,
          qcScore: "99% (GI Tagged)",
          leadTime: "12 Hours",
          status: "Top Value Match"
        }
      ]
    },
    {
      id: "DEM-BB-104",
      crop: "Yellow Soybean (JS 335 / High Oil Content)",
      category: "Grains & Cereals",
      image: "assets/images/wheat-logo.png",
      tonnage: "300 Qt (30,000 kg)",
      tonnageNum: 300,
      unit: "Qt",
      targetPrice: "₹ 4,150 /Qt",
      targetPriceNum: 4150,
      pricePerKg: 41.50,
      mandiBenchmark: "₹ 4,700 /Qt",
      savingsPct: "11.7% Savings",
      location: "Latur Mega Yard, Marathwada, MH",
      deadline: "26 Sep 2026",
      daysLeft: 12,
      matchedCount: 4,
      fulfilledTonnage: 150,
      fulfilledPct: 50,
      status: "Broadcasting",
      statusClass: "badge-status-open",
      statusLabel: "● Broadcasting (4 Bids Received)",
      grade: "Machine Cleaned Single Origin",
      moistureLimit: "Max 10.0% Moisture • Oil >18.5%",
      deliveryMode: "Bulk Jute Gunny Bags 50kg",
      escrowAdvance: "35% Advance (₹ 4,35,750)",
      bids: [
        {
          bidId: "BID-SOY-601",
          farmerName: "Anandrao Jadhav (Latur FPO)",
          farmerAvatar: "assets/images/wheat-logo.png",
          farmerPhone: "+91 98231-55890",
          location: "Latur Mega APMC Silo, MH",
          rating: "4.88 ⭐",
          offeredQty: "150 Qt (15,000 kg)",
          bidPrice: "₹ 4,120 /Qt",
          bidPriceNum: 4120,
          pricePerKg: 41.20,
          qcScore: "97% (Lab Assay Certified)",
          leadTime: "18 Hours",
          status: "FPO Partner"
        }
      ]
    },
    {
      id: "DEM-BB-105",
      crop: "Nagpur Orange / Santra (Table Export Grade)",
      category: "Fruits",
      image: "assets/images/orange.jpg",
      tonnage: "180 Qt (18,000 kg)",
      tonnageNum: 180,
      unit: "Qt",
      targetPrice: "₹ 3,750 /Qt",
      targetPriceNum: 3750,
      pricePerKg: 37.50,
      mandiBenchmark: "₹ 4,300 /Qt",
      savingsPct: "12.8% Savings",
      location: "Nagpur Multi-Modal Terminal, MH",
      deadline: "15 Sep 2026",
      daysLeft: 1,
      matchedCount: 3,
      fulfilledTonnage: 180,
      fulfilledPct: 100,
      status: "Fulfilled",
      statusClass: "badge-grade-a",
      statusLabel: "✓ 100% Contracted & Fulfilled",
      grade: "Grade A Nagpur Mandarin (GI Tagged)",
      moistureLimit: "Fresh Harvest Brix > 10%",
      deliveryMode: "Ventilated Plastic Crates",
      escrowAdvance: "35% Advance (₹ 2,36,250)",
      bids: []
    },
    {
      id: "DEM-BB-106",
      crop: "Sangli Rajapuri Turmeric Finger",
      category: "Spices & High-Value",
      image: "assets/images/turmeric.jpg",
      tonnage: "120 Qt (12,000 kg)",
      tonnageNum: 120,
      unit: "Qt",
      targetPrice: "₹ 13,200 /Qt",
      targetPriceNum: 13200,
      pricePerKg: 132.00,
      mandiBenchmark: "₹ 14,900 /Qt",
      savingsPct: "11.4% Savings",
      location: "Sangli Turmeric Terminal, MH",
      deadline: "28 Sep 2026",
      daysLeft: 14,
      matchedCount: 3,
      fulfilledTonnage: 50,
      fulfilledPct: 42,
      status: "Broadcasting",
      statusClass: "badge-status-open",
      statusLabel: "● Broadcasting (3 Bids Received)",
      grade: "Double Polished High Curcumin >4.8%",
      moistureLimit: "Max 9.0% Moisture • Lab Tested",
      deliveryMode: "Standard Jute Sacks",
      escrowAdvance: "35% Advance (₹ 5,54,400)",
      bids: [
        {
          bidId: "BID-TUR-501",
          farmerName: "Kavita Thorat",
          farmerAvatar: "assets/images/turmeric.jpg",
          farmerPhone: "+91 98228-88190",
          location: "Sangli APMC Yard, MH",
          rating: "4.95 ⭐",
          offeredQty: "50 Qt (5,000 kg)",
          bidPrice: "₹ 13,100 /Qt",
          bidPriceNum: 13100,
          pricePerKg: 131.00,
          qcScore: "99% (Rajapuri Certified)",
          leadTime: "24 Hours",
          status: "Top Quality"
        }
      ]
    }
  ],
  mandiPrices: [
    {
      crop: "Onion (Lasalgaon)",
      currentPrice: "₹ 18.50 /kg (₹ 1,850 /Qt)",
      trendPercent: "+5.4%",
      direction: "up",
      trendPoints: [15, 16, 17, 16, 18, 19, 20]
    },
    {
      crop: "Tomato (Narayangaon)",
      currentPrice: "₹ 13.00 /kg (₹ 1,300 /Qt)",
      trendPercent: "+6.2%",
      direction: "up",
      trendPoints: [20, 16, 18, 12, 14, 8, 4]
    },
    {
      crop: "Soybean (Latur APMC)",
      currentPrice: "₹ 42.00 /kg (₹ 4,200 /Qt)",
      trendPercent: "+3.8%",
      direction: "up",
      trendPoints: [18, 17, 19, 15, 12, 9, 7]
    },
    {
      crop: "Banana (Jalgaon)",
      currentPrice: "₹ 14.50 /kg (₹ 1,450 /Qt)",
      trendPercent: "-1.5%",
      direction: "down",
      trendPoints: [5, 8, 12, 9, 14, 18, 22]
    }
  ],
  consignments: [
    {
      tracking_id: "TRK-MH-15-PATIL",
      gate_pass: "GP-2026-9921-MH",
      crop: "Red Onion (Nashik Garwa Grade A)",
      quantity_qt: 100,
      quantity_kg: 10000,
      farmer: "Patil Rameshwar",
      farmer_phone: "+91 98220-44911",
      farmer_origin: "Lasalgaon Yard, Nashik, MH",
      destination: "BigBasket Distribution Terminal, Navi Mumbai, MH",
      driver: "Sanjay Patil",
      driver_phone: "+91 98220 44911",
      transporter: "Sahyadri Agro Logistics Lines",
      dl_no: "DL-MH-15-2016-8812",
      vehicle: "Eicher Pro 2049 (MH 15 DK 8810)",
      capacity: "50 Qt (5,000 kg Reefer)",
      fastag: "Active (₹ 2,100 Balance)",
      gps_device_id: "GPS-AIS140-99412",
      temp: "14.5°C (Controlled)",
      status: "transit",
      status_label: "On The Road",
      step: 3,
      loc: "Samruddhi Mahamarg Corridor (Near Kasara Ghat)",
      eta: "Today 4:30 PM (Speed: 58 km/h)",
      total_val: 180000,
      adv_paid: 63000,
      balance_due: 117000,
      assay_moisture: "13.2% (Cured)",
      gross_wt: "14,400 kg",
      tare_wt: "4,400 kg",
      gate_seal: "#SEAL-90144"
    },
    {
      tracking_id: "TRK-MH-12-DESHMUKH",
      gate_pass: "GP-2026-4412-MH",
      crop: "Tomato (Shivam Hybrid Grade A)",
      quantity_qt: 60,
      quantity_kg: 6000,
      farmer: "Sanjay Deshmukh",
      farmer_phone: "+91 98224-33100",
      farmer_origin: "Manchar Yard, Junnar, Pune, MH",
      destination: "BigBasket Central Hub, Gultekdi, Pune, MH",
      driver: "Tukaram Shinde",
      driver_phone: "+91 98224 33100",
      transporter: "Shivneri Cold-Chain Express",
      dl_no: "DL-MH-12-2018-4491",
      vehicle: "Bolero Maxi (MH 12 QX 5521)",
      capacity: "25 Qt (2,500 kg Payload)",
      fastag: "Active (₹ 1,450 Balance)",
      gps_device_id: "GPS-AIS140-88120",
      temp: "18.2°C (Optimal Curing)",
      status: "transit",
      status_label: "On The Road",
      step: 3,
      loc: "NH 60 Nashik-Pune Corridor (Near Chakan MIDC)",
      eta: "Today 2:15 PM (On Schedule)",
      total_val: 78000,
      adv_paid: 27300,
      balance_due: 50700,
      assay_moisture: "82.5% (Certified)",
      gross_wt: "8,850 kg",
      tare_wt: "2,850 kg",
      gate_seal: "#SEAL-88912"
    },
    {
      tracking_id: "TRK-MH-19-SHINDE",
      gate_pass: "GP-2026-3310-MH",
      crop: "Grand Naine Banana (Export Grade)",
      quantity_qt: 120,
      quantity_kg: 12000,
      farmer: "Rajesh Shinde",
      farmer_phone: "+91 98500-11234",
      farmer_origin: "Raver Farm Gate, Jalgaon, MH",
      destination: "Vashi APMC Mega Terminal, Navi Mumbai, MH",
      driver: "Sunil Bhangale",
      driver_phone: "+91 98500 11992",
      transporter: "Khandesh Agro Transit",
      dl_no: "DL-MH-19-2019-3310",
      vehicle: "Tata 407 Reefer (MH 19 AA 7714)",
      capacity: "35 Qt (3,500 kg Chilled)",
      fastag: "Active (₹ 980 Balance)",
      gps_device_id: "GPS-AIS140-33104",
      temp: "13.5°C (Chilled Reefer)",
      status: "scheduled",
      status_label: "Pickup Scheduled",
      step: 2,
      loc: "Truck arriving at Raver farm gate at 2:30 PM",
      eta: "Tomorrow 6:00 AM",
      total_val: 174000,
      adv_paid: 60900,
      balance_due: 113100,
      assay_moisture: "76.0% (Grade A)",
      gross_wt: "16,200 kg",
      tare_wt: "4,200 kg",
      gate_seal: "#SEAL-77210"
    },
    {
      tracking_id: "TRK-MH-24-JADHAV",
      gate_pass: "GP-2026-8801-MH",
      crop: "Yellow Soybean (JS 335 High Protein)",
      quantity_qt: 150,
      quantity_kg: 15000,
      farmer: "Anandrao Jadhav",
      farmer_phone: "+91 98231-55890",
      farmer_origin: "Latur Mega APMC Silo, MH",
      destination: "Pune Institutional Processing DC, Hadapsar, MH",
      driver: "Dnyaneshwar Solanke",
      driver_phone: "+91 98231 88219",
      transporter: "Marathwada Agro Freight Corp",
      dl_no: "DL-MH-24-2015-8801",
      vehicle: "Tata LPT 1613 (MH 24 AT 9912)",
      capacity: "120 Qt (12,000 kg Bulk)",
      fastag: "Active (₹ 3,400 Balance)",
      gps_device_id: "GPS-AIS140-88011",
      temp: "Ambient (24°C)",
      status: "delivered",
      status_label: "Delivered & QC Passed",
      step: 4,
      loc: "Delivered & 100% Escrow Settled",
      eta: "Completed • QC Passed 99%",
      total_val: 630000,
      adv_paid: 220500,
      balance_due: 409500,
      assay_moisture: "9.5% (Passed)",
      gross_wt: "21,500 kg",
      tare_wt: "6,500 kg",
      gate_seal: "#SEAL-11029"
    }
  ],
  activeContract: {
    contractId: "ESC-MH-9921",
    crop: "Red Onion (Nashik Garwa Quality)",
    quantity: "100 Qt",
    farmerName: "Patil Rameshwar",
    image: "assets/images/onion.jpg",
    totalAmount: "₹ 1,80,000",
    advanceLocked: "₹ 63,000 (35%)",
    balanceDue: "₹ 1,17,000 (65%)",
    status: "Consignment Dispatched",
    trackingId: "TRK-MH-15-PATIL",
    currentStep: 2
  },
  grievances: [
    {
      id: "GRV-2026-981",
      consignmentId: "TRK-MH-15-PATIL",
      crop: "Red Onion (Nashik Garwa Quality)",
      category: "Quality Defect (Moisture Deviation)",
      farmerName: "Patil Rameshwar",
      amountUnderHold: "₹ 1,17,000 (65% Balance Held)",
      status: "Under Review",
      statusClass: "badge-status-negotiation",
      dateFiled: "12 Sep 2026",
      resolutionEta: "Within 4 Hours",
      description: "Arrival moisture index measured 15.2% at Navi Mumbai receiving dock vs agreed certified threshold 13.5%. Requesting 3% quality price adjustment.",
      timeline: [
        { step: "Grievance Raised", done: true, time: "12 Sep, 10:15 AM" },
        { step: "Escrow Settlement Frozen", done: true, time: "12 Sep, 10:16 AM" },
        { step: "AI Assay & Photo Review", done: true, time: "12 Sep, 11:30 AM" },
        { step: "Arbitrator Decision", done: false, time: "Pending" }
      ]
    },
    {
      id: "GRV-2026-744",
      consignmentId: "TRK-MH-12-DESHMUKH",
      crop: "Tomato (Shivam Hybrid)",
      category: "Weight Shortage",
      farmerName: "Sanjay Deshmukh",
      amountUnderHold: "₹ 14,200",
      status: "Resolved & Refunded",
      statusClass: "badge-grade-a",
      dateFiled: "08 Sep 2026",
      resolutionEta: "Closed",
      description: "Weighbridge weight recorded 58.2 Qt vs 60 Qt dispatch slip. Partial escrow refund of ₹ 2,340 disbursed to buyer account.",
      timeline: [
        { step: "Grievance Raised", done: true, time: "08 Sep, 02:00 PM" },
        { step: "Escrow Frozen", done: true, time: "08 Sep, 02:02 PM" },
        { step: "Weighbridge Slip Verified", done: true, time: "08 Sep, 03:45 PM" },
        { step: "Partial Refund Settled", done: true, time: "08 Sep, 04:30 PM" }
      ]
    }
  ],
  storageFacilities: [
    {
      id: "WH-NSK-01",
      name: "Lasalgaon-Nashik Solar Ventilated Onion & Multi-Commodity Complex",
      type: "Solar Ventilated Onion Storage & Cold Chambers",
      typeKey: "solar-onion",
      location: "Lasalgaon Road, Nashik, MH ~ 1.8 km from APMC Mandi",
      totalCapacity: "20,000 Qt (2,000,000 kg)",
      availableCapacity: "6,200 Qt (620,000 kg)",
      availablePct: 31,
      suitableCrops: ["Red Onion", "Garlic", "Thompson Grapes", "Tomato"],
      tempRange: "Solar Forced Air Ventilation (25°C) & Cold Chambers (2-4°C)",
      humidity: "65% RH Anti-Sprouting",
      tariff: "₹ 40 /Qt /Month (₹ 0.40 /kg)",
      tariffPerDay: "₹ 1.30 /Qt /Day",
      isWdraAccredited: true,
      hasENwrPledge: true,
      rating: "4.92 ⭐",
      manager: "Patil Balasaheb (+91 98221-44780)",
      image: "assets/images/onion.jpg"
    },
    {
      id: "WH-PUN-02",
      name: "Talegaon-Pune CA Cold Chain & Perishables Agro Logistics Park",
      type: "Controlled Atmosphere (CA) Hub & Reefer Park (0°C – 4°C)",
      typeKey: "cold-storage",
      location: "Talegaon Floriculture & Agro Park, Pune, MH ~ Near Mumbai-Pune Expressway",
      totalCapacity: "15,000 Qt (1,500,000 kg)",
      availableCapacity: "5,400 Qt (540,000 kg)",
      availablePct: 36,
      suitableCrops: ["Tomato", "Pomegranate", "Exotic Vegetables", "Green Chilli", "Grapes"],
      tempRange: "0°C to 4°C (Gas Regulated O2/CO2)",
      humidity: "90% - 94% Ultra-High Freshness",
      tariff: "₹ 50 /Qt /Month (₹ 0.50 /kg)",
      tariffPerDay: "₹ 1.65 /Qt /Day",
      isWdraAccredited: true,
      hasENwrPledge: true,
      rating: "4.95 ⭐",
      manager: "Sanjay Thorat (+91 98224-55102)",
      image: "assets/images/tomato.jpg"
    },
    {
      id: "WH-LAT-03",
      name: "Latur Mega Hermetic Grain & Pulse Silos (WDRA Accredited)",
      type: "Hermetic Aerated Dry Silo & Pulse Complex",
      typeKey: "dry-silo",
      location: "Latur Industrial Growth Centre, Marathwada, MH ~ 3.5 km from APMC",
      totalCapacity: "35,000 Qt (3,500,000 kg)",
      availableCapacity: "11,800 Qt (1,180,000 kg)",
      availablePct: 34,
      suitableCrops: ["Yellow Soybean", "Tur Dal", "Chana", "Wheat", "Jowar"],
      tempRange: "Ambient Aerated Silo (18°C – 22°C)",
      humidity: "Max 10% Moisture Guarantee",
      tariff: "₹ 35 /Qt /Month (₹ 0.35 /kg)",
      tariffPerDay: "₹ 1.15 /Qt /Day",
      isWdraAccredited: true,
      hasENwrPledge: true,
      rating: "4.88 ⭐",
      manager: "Anand Solanke (+91 98230-88901)",
      image: "assets/images/wheat-logo.png"
    },
    {
      id: "WH-NGP-04",
      name: "Nagpur Integrated Cold Storage & Citrus Packhouse (Butibori MIDC)",
      type: "Multi-Chamber Fruit Cold Chain & Packhouse",
      typeKey: "cold-storage",
      location: "Butibori MIDC Agro Zone, Nagpur, MH ~ Near Wardha Corridor",
      totalCapacity: "18,000 Qt (1,800,000 kg)",
      availableCapacity: "7,100 Qt (710,000 kg)",
      availablePct: 39,
      suitableCrops: ["Nagpur Orange", "Pomegranate", "Banana", "Ginger", "Turmeric"],
      tempRange: "2°C to 8°C (Multi-Chamber)",
      humidity: "88% - 92% RH Controlled",
      tariff: "₹ 45 /Qt /Month (₹ 0.45 /kg)",
      tariffPerDay: "₹ 1.50 /Qt /Day",
      isWdraAccredited: true,
      hasENwrPledge: true,
      rating: "4.9 ⭐",
      manager: "Pravin Wankhede (+91 98222-33104)",
      image: "assets/images/orange.jpg"
    }
  ],
  activeStorageBookings: [
    {
      id: "STR-2026-MH01",
      warehouseId: "WH-NSK-01",
      warehouseName: "Lasalgaon-Nashik Solar Storage Complex",
      crop: "Red Onion (Nashik Garwa Quality)",
      quantity: "100 Qt (10,000 kg)",
      lotRef: "LOT-ONI-01",
      chamberNo: "Chamber #2-A (Ventilated)",
      tempCurrent: "24.5°C (Solar Aerated)",
      humidityCurrent: "64% RH",
      bookingDate: "10 Sep 2026",
      expiryDate: "25 Sep 2026 (12 Days Remaining)",
      monthlyCost: "₹ 4,000",
      status: "In Storage (Active)",
      statusBadgeClass: "badge-status-open",
      eNwrReceiptNo: "eNWR-MH-2026-99120",
      pledgeLoanEligible: "₹ 1,26,000 (70% Value at ₹ 18/kg)"
    }
  ]
};
