/**
 * AgriNex - Wholesale Buyer Module Data Store
 */

const buyerData = {
  profile: {
    name: "Karthik Sundaram",
    role: "Procurement Lead",
    company: "BigBasket Direct Farm Sourcing",
    location: "Hosur Hub, Tamil Nadu",
    avatar: "assets/images/farmer-avatar.jpg",
    notificationsCount: 3,
    messagesCount: 2
  },
  stats: {
    totalDemands: 4,
    demandsSubtitle: "Active procurement quotas",
    matchedLots: 8,
    matchedLotsSubtitle: "Verified farmer lots in radius",
    activeShipments: 2,
    shipmentSubtitle: "Consignments in transit",
    costSavings: "₹ 46,200",
    savingsSubtitle: "Saved vs traditional mandi middlemen"
  },
  verifiedLots: [
    {
      id: "LOT-ONI-01",
      crop: "Onion",
      category: "Vegetables",
      farmerName: "gowran",
      farmerLocation: "Erode, Tamil Nadu ~ Near APMC Mandi",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 98422-77102",
      image: "assets/images/onion.jpg",
      grade: "Grade A",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 30,
      availableQtyKg: 15,
      quantity: "0.15 Qt",
      qtyNum: 0.15,
      askPrice: "₹ 3,000 /Qt",
      priceNum: 3000,
      mandiRate: "₹ 3,400 /Qt",
      savings: "11.8% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "65.0%"
    },
    {
      id: "LOT-TOM-02",
      crop: "Roma Plum Tomato (Firm & Red)",
      category: "Vegetables",
      farmerName: "S. Raman",
      farmerLocation: "Perundurai, Erode ~ 2.4 km away",
      farmerRating: "4.95 ⭐",
      farmerPhone: "+91 94431-22901",
      image: "assets/images/tomato.jpg",
      grade: "Grade A - Retail Ready",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 24,
      availableQtyKg: 500,
      quantity: "5 Qt",
      qtyNum: 5,
      askPrice: "₹ 2,400 /Qt",
      priceNum: 2400,
      mandiRate: "₹ 2,750 /Qt",
      savings: "12.7% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "82.0%"
    },
    {
      id: "LOT-TOM-03",
      crop: "Organic Country Tomato (Naatu Thakkali)",
      category: "Vegetables",
      farmerName: "K. Selvaraj",
      farmerLocation: "Bhavani, Erode ~ 4.1 km away",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 97890-33412",
      image: "assets/images/tomato.jpg",
      grade: "100% Organic Certified",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 32,
      availableQtyKg: 350,
      quantity: "3.5 Qt",
      qtyNum: 3.5,
      askPrice: "₹ 3,200 /Qt",
      priceNum: 3200,
      mandiRate: "₹ 3,600 /Qt",
      savings: "11.1% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "80.5%"
    },
    {
      id: "LOT-TOM-04",
      crop: "Hybrid Red Salad Tomato – Bulk Harvest",
      category: "Vegetables",
      farmerName: "M. Dhanapal",
      farmerLocation: "Sathyamangalam ~ 11.6 km away",
      farmerRating: "4.85 ⭐",
      farmerPhone: "+91 98421-55890",
      image: "assets/images/tomato.jpg",
      grade: "Grade A Commercial",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 20,
      availableQtyKg: 2000,
      quantity: "20 Qt",
      qtyNum: 20,
      askPrice: "₹ 2,000 /Qt",
      priceNum: 2000,
      mandiRate: "₹ 2,300 /Qt",
      savings: "13.0% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "84.0%"
    },
    {
      id: "LOT-ONI-05",
      crop: "Premium Bellary Big Red Onion",
      category: "Vegetables",
      farmerName: "Muthusamy Soundar",
      farmerLocation: "Perundurai, Erode ~ 2.8 km away",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 94433-88190",
      image: "assets/images/onion.jpg",
      grade: "Grade A Export Quality",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 32,
      availableQtyKg: 5000,
      quantity: "50 Qt",
      qtyNum: 50,
      askPrice: "₹ 3,200 /Qt",
      priceNum: 3200,
      mandiRate: "₹ 3,700 /Qt",
      savings: "13.5% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "66.0%"
    },
    {
      id: "LOT-ONI-06",
      crop: "Sambar Shallots (Small Country Onion)",
      category: "Vegetables",
      farmerName: "Revathi Balan",
      farmerLocation: "Anthiyur, Erode ~ 15.2 km away",
      farmerRating: "4.92 ⭐",
      farmerPhone: "+91 97892-44102",
      image: "assets/images/onion.jpg",
      grade: "Traditional Sambar Grade",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 65,
      availableQtyKg: 600,
      quantity: "6 Qt",
      qtyNum: 6,
      askPrice: "₹ 6,500 /Qt",
      priceNum: 6500,
      mandiRate: "₹ 7,200 /Qt",
      savings: "9.7% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "62.0%"
    },
    {
      id: "LOT-TUR-07",
      crop: "Salem Turmeric Finger (High Curcumin)",
      category: "Spices & High-Value",
      farmerName: "Kavitha Rajan",
      farmerLocation: "Salem ~ 32.0 km away",
      farmerRating: "4.9 ⭐",
      farmerPhone: "+91 94432-88190",
      image: "assets/images/wheat-logo.png",
      grade: "Organic Desi A2",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 74,
      availableQtyKg: 2500,
      quantity: "25 Qt",
      qtyNum: 25,
      askPrice: "₹ 7,400 /Qt",
      priceNum: 7400,
      mandiRate: "₹ 8,200 /Qt",
      savings: "9.8% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "9.2%"
    },
    {
      id: "LOT-PAD-08",
      crop: "1121 Basmati Paddy (Aromatic Long Grain)",
      category: "Grains & Cereals",
      farmerName: "Venkatesh Rao",
      farmerLocation: "Karnal, HR ~ Direct Express Line",
      farmerRating: "4.95 ⭐",
      farmerPhone: "+91 98120-33410",
      image: "assets/images/paddy.jpg",
      grade: "Premium Aged (1 Year)",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 24,
      availableQtyKg: 12000,
      quantity: "120 Qt",
      qtyNum: 120,
      askPrice: "₹ 2,400 /Qt",
      priceNum: 2400,
      mandiRate: "₹ 2,650 /Qt",
      savings: "9.4% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "12.0%"
    },
    {
      id: "LOT-COT-09",
      crop: "Long Staple Cotton (MCU-5 Fiber)",
      category: "FPO Bulk Lots",
      farmerName: "Kaliamurthi R",
      farmerLocation: "Guntur, AP ~ Cotton Yard Hub",
      farmerRating: "4.75 ⭐",
      farmerPhone: "+91 98480-11234",
      image: "assets/images/cotton.jpg",
      grade: "Grade A Export Spun",
      gradeKey: "grade-a",
      gradeBadgeClass: "badge-grade-a",
      pricePerKg: 56,
      availableQtyKg: 4000,
      quantity: "40 Qt",
      qtyNum: 40,
      askPrice: "₹ 5,600 /Qt",
      priceNum: 5600,
      mandiRate: "₹ 6,100 /Qt",
      savings: "8.2% Lower",
      status: "Verified Available",
      statusBadgeClass: "badge-status-open",
      moisture: "8.5%"
    }
  ],
  buyerDemands: [
    {
      id: "DEM-BB-101",
      crop: "Tomato (Shivam Hybrid / Roma)",
      category: "Vegetables",
      image: "assets/images/tomato.jpg",
      tonnage: "15 MT (150 Qt)",
      tonnageNum: 15,
      unit: "MT",
      targetPrice: "₹ 1,220 /Qt",
      targetPriceNum: 1220,
      pricePerKg: 12.20,
      mandiBenchmark: "₹ 1,410 /Qt",
      savingsPct: "13.5% Savings",
      location: "Hosur Hub, TN",
      deadline: "18 Sep 2026",
      daysLeft: 5,
      matchedCount: 4,
      fulfilledTonnage: 11,
      fulfilledPct: 73,
      status: "Active Matching",
      statusClass: "badge-status-open",
      statusLabel: "⚡ 4 Farmer Bids (Auto-Match Ready)",
      grade: "Grade A Commercial / Export",
      moistureLimit: "Max 85% Moisture • Brix > 4.5%",
      deliveryMode: "Farm-Gate Pickup (AgriNex Transit)",
      escrowAdvance: "35% Advance (₹ 64,050)",
      bids: [
        {
          bidId: "BID-TOM-991",
          farmerName: "Murugan Palanisamy",
          farmerAvatar: "assets/images/tomato.jpg",
          farmerPhone: "+91 94431-22901",
          location: "Dindigul, TN (42 km away)",
          rating: "4.9 ⭐",
          offeredQty: "5 MT (50 Qt)",
          bidPrice: "₹ 1,200 /Qt",
          bidPriceNum: 1200,
          pricePerKg: 12.00,
          qcScore: "96% (Grade A Verified)",
          leadTime: "6 Hours",
          status: "Verified Top Match"
        },
        {
          bidId: "BID-TOM-992",
          farmerName: "S. Raman",
          farmerAvatar: "assets/images/tomato.jpg",
          farmerPhone: "+91 94431-22901",
          location: "Perundurai, Erode (28 km away)",
          rating: "4.85 ⭐",
          offeredQty: "4 MT (40 Qt)",
          bidPrice: "₹ 1,210 /Qt",
          bidPriceNum: 1210,
          pricePerKg: 12.10,
          qcScore: "94% (Grade A)",
          leadTime: "4 Hours",
          status: "Nearby Farmer"
        },
        {
          bidId: "BID-TOM-993",
          farmerName: "M. Dhanapal",
          farmerAvatar: "assets/images/tomato.jpg",
          farmerPhone: "+91 98421-55890",
          location: "Sathyamangalam, TN (55 km away)",
          rating: "4.8 ⭐",
          offeredQty: "3 MT (30 Qt)",
          bidPrice: "₹ 1,220 /Qt",
          bidPriceNum: 1220,
          pricePerKg: 12.20,
          qcScore: "92% (Grade A)",
          leadTime: "8 Hours",
          status: "Available"
        }
      ]
    },
    {
      id: "DEM-BB-102",
      crop: "Red Onion (Garwa Export Grade)",
      category: "Vegetables",
      image: "assets/images/onion.jpg",
      tonnage: "25 MT (250 Qt)",
      tonnageNum: 25,
      unit: "MT",
      targetPrice: "₹ 1,850 /Qt",
      targetPriceNum: 1850,
      pricePerKg: 18.50,
      mandiBenchmark: "₹ 2,150 /Qt",
      savingsPct: "14.0% Savings",
      location: "Navi Mumbai Hub, MH",
      deadline: "22 Sep 2026",
      daysLeft: 9,
      matchedCount: 5,
      fulfilledTonnage: 18,
      fulfilledPct: 72,
      status: "Active Matching",
      statusClass: "badge-status-open",
      statusLabel: "● Broadcasting (5 Bids Received)",
      grade: "Grade A (45-55mm Calibrated)",
      moistureLimit: "Max 14% Moisture • Cured Skin",
      deliveryMode: "Direct Hub Delivery / Reefer",
      escrowAdvance: "35% Advance (₹ 1,61,875)",
      bids: [
        {
          bidId: "BID-ONI-801",
          farmerName: "Patil Rameshwar",
          farmerAvatar: "assets/images/onion.jpg",
          farmerPhone: "+91 98220-44911",
          location: "Nashik, MH (65 km away)",
          rating: "4.92 ⭐",
          offeredQty: "10 MT (100 Qt)",
          bidPrice: "₹ 1,820 /Qt",
          bidPriceNum: 1820,
          pricePerKg: 18.20,
          qcScore: "98% (Export Certified)",
          leadTime: "12 Hours",
          status: "Top Value Match"
        },
        {
          bidId: "BID-ONI-802",
          farmerName: "Muthusamy Soundar",
          farmerAvatar: "assets/images/onion.jpg",
          farmerPhone: "+91 94433-88190",
          location: "Perundurai, Erode (Direct Lot)",
          rating: "4.9 ⭐",
          offeredQty: "8 MT (80 Qt)",
          bidPrice: "₹ 1,840 /Qt",
          bidPriceNum: 1840,
          pricePerKg: 18.40,
          qcScore: "95% (Grade A)",
          leadTime: "14 Hours",
          status: "Available"
        }
      ]
    },
    {
      id: "DEM-BB-103",
      crop: "Green Chilli (G4 Spices & Export)",
      category: "Spices & High-Value",
      image: "assets/images/tomato.jpg",
      tonnage: "8 MT (80 Qt)",
      tonnageNum: 8,
      unit: "MT",
      targetPrice: "₹ 4,100 /Qt",
      targetPriceNum: 4100,
      pricePerKg: 41.00,
      mandiBenchmark: "₹ 4,800 /Qt",
      savingsPct: "14.6% Savings",
      location: "Kolar Logistics Hub, KA",
      deadline: "20 Sep 2026",
      daysLeft: 7,
      matchedCount: 3,
      fulfilledTonnage: 6,
      fulfilledPct: 75,
      status: "Active Matching",
      statusClass: "badge-status-open",
      statusLabel: "⚡ 3 Farmer Bids (Auto-Match Ready)",
      grade: "Grade A Dark Green (8-10cm)",
      moistureLimit: "Max 78% Moisture • Fresh Harvest",
      deliveryMode: "Reefer Cold-Chain Pickup",
      escrowAdvance: "35% Advance (₹ 1,14,800)",
      bids: [
        {
          bidId: "BID-CHI-701",
          farmerName: "S. Ramasamy",
          farmerAvatar: "assets/images/tomato.jpg",
          farmerPhone: "+91 98422-99812",
          location: "Kolar Hub 2, KA (18 km away)",
          rating: "4.88 ⭐",
          offeredQty: "4 MT (40 Qt)",
          bidPrice: "₹ 4,050 /Qt",
          bidPriceNum: 4050,
          pricePerKg: 40.50,
          qcScore: "97% (Grade A)",
          leadTime: "3 Hours",
          status: "Top Match"
        }
      ]
    },
    {
      id: "DEM-BB-104",
      crop: "Salem Turmeric Finger (Curcumin >4.5%)",
      category: "Spices & High-Value",
      image: "assets/images/onion.jpg",
      tonnage: "12 MT (120 Qt)",
      tonnageNum: 12,
      unit: "MT",
      targetPrice: "₹ 7,200 /Qt",
      targetPriceNum: 7200,
      pricePerKg: 72.00,
      mandiBenchmark: "₹ 8,100 /Qt",
      savingsPct: "11.1% Savings",
      location: "Salem / Erode Yard, TN",
      deadline: "25 Sep 2026",
      daysLeft: 12,
      matchedCount: 4,
      fulfilledTonnage: 4,
      fulfilledPct: 33,
      status: "Broadcasting",
      statusClass: "badge-status-open",
      statusLabel: "● Broadcasting (4 Bids Received)",
      grade: "Double Polished High Curcumin",
      moistureLimit: "Max 9.5% Moisture • Lab Certified",
      deliveryMode: "Farm-Gate Jute Bags 50kg",
      escrowAdvance: "35% Advance (₹ 3,02,400)",
      bids: [
        {
          bidId: "BID-TUR-601",
          farmerName: "Kavitha Rajan (Salem FPO)",
          farmerAvatar: "assets/images/onion.jpg",
          farmerPhone: "+91 94432-11980",
          location: "Salem Agro Hub, TN (22 km away)",
          rating: "4.95 ⭐",
          offeredQty: "8 MT (80 Qt)",
          bidPrice: "₹ 7,150 /Qt",
          bidPriceNum: 7150,
          pricePerKg: 71.50,
          qcScore: "99% (Lab Tested 4.8% Curcumin)",
          leadTime: "24 Hours",
          status: "FPO Bulk Lot"
        }
      ]
    },
    {
      id: "DEM-BB-105",
      crop: "1121 Basmati Paddy (Export)",
      category: "Grains & Cereals",
      image: "assets/images/tomato.jpg",
      tonnage: "50 MT (500 Qt)",
      tonnageNum: 50,
      unit: "MT",
      targetPrice: "₹ 3,450 /Qt",
      targetPriceNum: 3450,
      pricePerKg: 34.50,
      mandiBenchmark: "₹ 3,900 /Qt",
      savingsPct: "11.5% Savings",
      location: "Karnal Silo, HR",
      deadline: "12 Sep 2026",
      daysLeft: 0,
      matchedCount: 6,
      fulfilledTonnage: 50,
      fulfilledPct: 100,
      status: "Fulfilled",
      statusClass: "badge-grade-a",
      statusLabel: "✓ 100% Contracted & Fulfilled",
      grade: "Grade A Basmati (8.35mm)",
      moistureLimit: "12.0% Moisture • 98% Purity",
      deliveryMode: "Multi-Axle Bulk Transport",
      escrowAdvance: "35% Advance (₹ 6,03,750)",
      bids: []
    },
    {
      id: "DEM-BB-106",
      crop: "Long Staple Raw Cotton (Shankar-6)",
      category: "Commercial Cash Crops",
      image: "assets/images/onion.jpg",
      tonnage: "30 MT (300 Qt)",
      tonnageNum: 30,
      unit: "MT",
      targetPrice: "₹ 6,100 /Qt",
      targetPriceNum: 6100,
      pricePerKg: 61.00,
      mandiBenchmark: "₹ 6,950 /Qt",
      savingsPct: "12.2% Savings",
      location: "Rajkot Ginning Depot, GJ",
      deadline: "28 Sep 2026",
      daysLeft: 15,
      matchedCount: 3,
      fulfilledTonnage: 15,
      fulfilledPct: 50,
      status: "Broadcasting",
      statusClass: "badge-status-open",
      statusLabel: "● Broadcasting (3 Bids Received)",
      grade: "Staple >29mm • Mic 3.8-4.2",
      moistureLimit: "Max 8.5% Moisture • Trash <3%",
      deliveryMode: "Pressed Bales (170 kg)",
      escrowAdvance: "35% Advance (₹ 6,40,500)",
      bids: [
        {
          bidId: "BID-COT-501",
          farmerName: "Suresh Patel (Ginning Co-op)",
          farmerAvatar: "assets/images/onion.jpg",
          farmerPhone: "+91 98251-77890",
          location: "Rajkot Yard 3, GJ (34 km away)",
          rating: "4.9 ⭐",
          offeredQty: "15 MT (150 Qt)",
          bidPrice: "₹ 6,050 /Qt",
          bidPriceNum: 6050,
          pricePerKg: 60.50,
          qcScore: "98% (Shankar-6 Certified)",
          leadTime: "18 Hours",
          status: "Ginning Partner"
        }
      ]
    }
  ],
  mandiPrices: [
    {
      crop: "Tomato",
      currentPrice: "₹ 1,150",
      trendPercent: "+6.2%",
      direction: "up",
      trendPoints: [20, 16, 18, 12, 14, 8, 4]
    },
    {
      crop: "Onion",
      currentPrice: "₹ 900",
      trendPercent: "+4.8%",
      direction: "up",
      trendPoints: [22, 19, 16, 14, 11, 7, 5]
    },
    {
      crop: "Paddy",
      currentPrice: "₹ 2,000",
      trendPercent: "+3.5%",
      direction: "up",
      trendPoints: [18, 17, 19, 15, 12, 9, 7]
    },
    {
      crop: "Cotton",
      currentPrice: "₹ 5,800",
      trendPercent: "-1.2%",
      direction: "down",
      trendPoints: [5, 8, 12, 9, 14, 18, 22]
    }
  ],
  activeContract: {
    contractId: "ESC-BB-9921",
    crop: "Tomato (Shivam Hybrid)",
    quantity: "50 Qt",
    farmerName: "Murugan Palanisamy",
    image: "assets/images/tomato.jpg",
    totalAmount: "₹ 60,000",
    advanceLocked: "₹ 21,000 (35%)",
    balanceDue: "₹ 39,000 (65%)",
    status: "Consignment Dispatched",
    trackingId: "TRK-EXP-9921-TN",
    currentStep: 2 // 1: Contract, 2: Advance Locked, 3: Dispatched, 4: Settled
  },
  grievances: [
    {
      id: "GRV-2026-981",
      consignmentId: "TRK-EXP-9921-TN",
      crop: "Tomato (Shivam Hybrid)",
      category: "Quality Defect (Moisture Deviation)",
      farmerName: "Murugan Palanisamy",
      amountUnderHold: "₹ 39,000 (65% Balance Held)",
      status: "Under Review",
      statusClass: "badge-status-negotiation",
      dateFiled: "12 Sep 2026",
      resolutionEta: "Within 4 Hours",
      description: "Arrival moisture index measured 88.5% at Hosur receiving dock vs agreed certified threshold 82.5%. Requesting 5% quality price revision.",
      timeline: [
        { step: "Grievance Raised", done: true, time: "12 Sep, 10:15 AM" },
        { step: "Escrow Settlement Frozen", done: true, time: "12 Sep, 10:16 AM" },
        { step: "AI Assay & Photo Review", done: true, time: "12 Sep, 11:30 AM" },
        { step: "Arbitrator Decision", done: false, time: "Pending" }
      ]
    },
    {
      id: "GRV-2026-744",
      consignmentId: "TRK-KA-3310-TATA",
      crop: "Red Onion (Nashik Quality)",
      category: "Weight Shortage",
      farmerName: "Patil Rameshwar",
      amountUnderHold: "₹ 14,200",
      status: "Resolved & Refunded",
      statusClass: "badge-grade-a",
      dateFiled: "08 Sep 2026",
      resolutionEta: "Closed",
      description: "Weighbridge weight recorded 76.5 Qt vs 80 Qt dispatch slip. Partial escrow refund of ₹ 6,300 disbursed to buyer account.",
      timeline: [
        { step: "Grievance Raised", done: true, time: "08 Sep, 02:00 PM" },
        { step: "Escrow Frozen", done: true, time: "08 Sep, 02:02 PM" },
        { step: "Weighbridge Slip Verified", done: true, time: "08 Sep, 03:45 PM" },
        { step: "Partial Refund Settled", done: true, time: "08 Sep, 04:30 PM" }
      ]
    }
  ]
};
