/**
 * AgriNex - Farmer Module Enterprise Data Store
 * Grounded in Maharashtra Agricultural Hubs, APMC Mandis, and Regional Produce
 * Standardized in ₹/kg pricing across all 23 commodity lots, demands, and forecasts.
 * Completely synchronized with Buyer Module.
 */

const farmerData = {
  profile: {
<<<<<<< HEAD
    name: "Ramesh Patil",
    role: "Farmer",
    location: "Nashik, Maharashtra",
=======
    name: "Patil Rameshwar",
    role: "Progressive Farmer & FPO Director",
    location: "Lasalgaon APMC Yard, Nashik, Maharashtra",
>>>>>>> eb7b2131bbe40c41866443d60354b6bb55c668b5
    avatar: "assets/images/farmer-avatar.jpg",
    notificationsCount: 5,
    messagesCount: 3
  },
  stats: {
<<<<<<< HEAD
    totalLots: 7,
    activeListingsSubtitle: "Active listings",
    activeBids: 6,
    buyersSubtitle: "Buyers interested",
    pendingShipments: 1,
    shipmentSubtitle: "In transit",
    estimatedProfit: "₹ 10,95,000",
=======
    totalLots: 23,
    activeListingsSubtitle: "Active verified listings",
    activeBids: 18,
    buyersSubtitle: "Buyers interested across Maharashtra",
    pendingShipments: 4,
    shipmentSubtitle: "In transit to Vashi & Pune APMC",
    estimatedProfit: "₹ 28,45,000",
>>>>>>> eb7b2131bbe40c41866443d60354b6bb55c668b5
    profitSubtitle: "(Expected gross value)"
  },
  listings: [
    {
<<<<<<< HEAD
      id: "LOT-TOM-01",
      crop: "Tomato (Shivam Hybrid)",
      category: "Vegetables",
      shelfLife: "3 Days (Perishable)",
      harvestDate: "12 Sep 2026",
      image: "assets/images/tomato.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "50 Qt (5,000 kg)",
      quantityNumber: 50,
      expectedPrice: "₹ 12.00 /kg (₹ 1,200 /Qt)",
      expectedPriceNumber: 1200,
      bestBid: "₹ 12.50 /kg (₹ 1,250 /Qt)",
      bestBidNumber: 1250,
      buyerName: "AgriFoods Ltd.",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Nashik APMC Mandi, MH"
    },
    {
      id: "LOT-ONI-02",
      crop: "Red Onion (Nashik Quality)",
      category: "Vegetables",
      shelfLife: "25 Days",
      harvestDate: "10 Sep 2026",
      image: "assets/images/onion.jpg",
      grade: "Grade B",
      gradeBadgeClass: "badge-grade-b",
      quantity: "30 Qt (3,000 kg)",
      quantityNumber: 30,
      expectedPrice: "₹ 9.00 /kg (₹ 900 /Qt)",
      expectedPriceNumber: 900,
      bestBid: "₹ 9.50 /kg (₹ 950 /Qt)",
      bestBidNumber: 950,
      buyerName: "Global Grains Direct",
      status: "Negotiation",
      statusBadgeClass: "badge-status-negotiation",
      location: "Lasalgaon Mandi Yard, MH"
    },
    {
      id: "LOT-PAD-03",
      crop: "Paddy (1121 Basmati)",
      category: "Grains & Cereals",
      shelfLife: "180 Days",
      harvestDate: "05 Sep 2026",
      image: "assets/images/paddy.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "100 Qt (10,000 kg)",
      quantityNumber: 100,
      expectedPrice: "₹ 20.00 /kg (₹ 2,000 /Qt)",
      expectedPriceNumber: 2000,
      bestBid: "₹ 20.80 /kg (₹ 2,080 /Qt)",
      bestBidNumber: 2080,
      buyerName: "Fresh Mart Wholesale",
      status: "Dispatched",
      statusBadgeClass: "badge-status-dispatched",
      location: "Nashik Central Agro Warehouse, MH"
    },
    {
      id: "LOT-CHL-04",
      crop: "Green Chilli (G4 Spicy)",
      category: "Spices & High-Value",
      shelfLife: "5 Days (Perishable)",
      harvestDate: "11 Sep 2026",
      image: "assets/images/chilli.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "25 Qt (2,500 kg)",
      quantityNumber: 25,
      expectedPrice: "₹ 32.00 /kg (₹ 3,200 /Qt)",
      expectedPriceNumber: 3200,
      bestBid: "₹ 33.50 /kg (₹ 3,350 /Qt)",
      bestBidNumber: 3350,
      buyerName: "Spices Exim Hub",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Pimpalgaon APMC, MH"
    },
    {
      id: "LOT-COT-05",
      crop: "Raw Cotton (MCU-5 Long Staple)",
      category: "Cash Crops",
      shelfLife: "365 Days",
      harvestDate: "01 Sep 2026",
      image: "assets/images/cotton.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "80 Qt (8,000 kg)",
      quantityNumber: 80,
      expectedPrice: "₹ 58.00 /kg (₹ 5,800 /Qt)",
      expectedPriceNumber: 5800,
      bestBid: "₹ 59.50 /kg (₹ 5,950 /Qt)",
      bestBidNumber: 5950,
      buyerName: "Malegaon Cotton Textiles",
      status: "Negotiation",
      statusBadgeClass: "badge-status-negotiation",
      location: "Malegaon Mandi Yard, MH"
    },
    {
      id: "LOT-OKR-06",
      crop: "Fresh Okra (Ladyfinger)",
      category: "Vegetables",
      shelfLife: "2 Days (Perishable)",
      harvestDate: "13 Sep 2026",
      image: "assets/images/okra.jpg",
      grade: "Grade B",
      gradeBadgeClass: "badge-grade-b",
      quantity: "20 Qt (2,000 kg)",
      quantityNumber: 20,
      expectedPrice: "₹ 16.00 /kg (₹ 1,600 /Qt)",
      expectedPriceNumber: 1600,
      bestBid: "₹ 16.80 /kg (₹ 1,680 /Qt)",
      bestBidNumber: 1680,
      buyerName: "Annapoorna Caterers",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Nashik APMC Mandi, MH"
    },
    {
      id: "LOT-TUR-07",
      crop: "Salem Turmeric Finger (High Curcumin)",
      category: "Spices & High-Value",
      shelfLife: "365 Days",
      harvestDate: "28 Aug 2026",
      image: "assets/images/turmeric.jpg",
      grade: "Grade A Export Quality",
      gradeBadgeClass: "badge-grade-a",
      quantity: "25 Qt (2,500 kg)",
      quantityNumber: 25,
      expectedPrice: "₹ 141.00 /kg (₹ 14,100 /Qt)",
      expectedPriceNumber: 14100,
      bestBid: "₹ 143.00 /kg (₹ 14,300 /Qt)",
      bestBidNumber: 14300,
      buyerName: "Aroma Spices International",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Sangli Spices Hub, MH"
=======
        "id": "LOT-ONI-01",
        "crop": "Red Onion (Nashik Garwa Quality)",
        "category": "Vegetables",
        "shelfLife": "25 Days",
        "harvestDate": "10 Sep 2026",
        "image": "assets/images/onion.jpg",
        "grade": "Grade A Export Calibrated",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "100 Qt (10,000 kg)",
        "quantityNumber": 100,
        "expectedPrice": "₹ 18.00 /kg (₹ 1,800 /Qt)",
        "expectedPriceNumber": 1800,
        "bestBid": "₹ 18.90 /kg (₹ 1,890 /Qt)",
        "bestBidNumber": 1890,
        "buyerName": "BigBasket Direct Farm Sourcing",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Lasalgaon APMC Yard, Nashik"
    },
    {
        "id": "LOT-TOM-02",
        "crop": "Tomato (Shivam / Abhinav Hybrid)",
        "category": "Vegetables",
        "shelfLife": "4 Days (Perishable)",
        "harvestDate": "11 Sep 2026",
        "image": "assets/images/tomato.jpg?v=2",
        "grade": "Grade A",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "60 Qt (6,000 kg)",
        "quantityNumber": 60,
        "expectedPrice": "₹ 13.00 /kg (₹ 1,300 /Qt)",
        "expectedPriceNumber": 1300,
        "bestBid": "₹ 13.91 /kg (₹ 1,391 /Qt)",
        "bestBidNumber": 1391,
        "buyerName": "Reliance Fresh Supply Chain",
        "status": "Negotiation",
        "statusBadgeClass": "badge-status-negotiation",
        "location": "Narayangaon Mandi Yard, Junnar, Pune"
    },
    {
        "id": "LOT-BAN-03",
        "crop": "Grand Naine Banana (GI Khandesh Export)",
        "category": "Fruits",
        "shelfLife": "6 Days (Perishable)",
        "harvestDate": "12 Sep 2026",
        "image": "assets/images/banana.jpg?v=2",
        "grade": "Grade A Export Calibrated",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "120 Qt (12,000 kg)",
        "quantityNumber": 120,
        "expectedPrice": "₹ 14.50 /kg (₹ 1,450 /Qt)",
        "expectedPriceNumber": 1450,
        "bestBid": "₹ 15.81 /kg (₹ 1,581 /Qt)",
        "bestBidNumber": 1581,
        "buyerName": "Adani Wilmar Agri Procurement",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Raver APMC Hub, Jalgaon"
    },
    {
        "id": "LOT-SOY-04",
        "crop": "Yellow Soybean (JS 335 / High Protein)",
        "category": "Grains & Cereals",
        "shelfLife": "180 Days",
        "harvestDate": "13 Sep 2026",
        "image": "assets/images/soybean.jpg?v=3",
        "grade": "Grade A",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "150 Qt (15,000 kg)",
        "quantityNumber": 150,
        "expectedPrice": "₹ 42.00 /kg (₹ 4,200 /Qt)",
        "expectedPriceNumber": 4200,
        "bestBid": "₹ 46.62 /kg (₹ 4,662 /Qt)",
        "bestBidNumber": 4662,
        "buyerName": "DMart Wholesale (Avenue Supermarts)",
        "status": "Dispatched",
        "statusBadgeClass": "badge-status-dispatched",
        "location": "Latur Mega APMC Yard, Marathwada"
    },
    {
        "id": "LOT-ORG-05",
        "crop": "Nagpur Orange / Santra (GI Vidarbha Quality)",
        "category": "Fruits",
        "shelfLife": "12 Days",
        "harvestDate": "14 Sep 2026",
        "image": "assets/images/orange.jpg?v=2",
        "grade": "Grade A Table / Export",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "80 Qt (8,000 kg)",
        "quantityNumber": 80,
        "expectedPrice": "₹ 38.00 /kg (₹ 3,800 /Qt)",
        "expectedPriceNumber": 3800,
        "bestBid": "₹ 39.90 /kg (₹ 3,990 /Qt)",
        "bestBidNumber": 3990,
        "buyerName": "Kay Bee Exports International",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Katol Mandi Yard, Nagpur"
    },
    {
        "id": "LOT-TUR-06",
        "crop": "Sangli Rajapuri Turmeric Finger",
        "category": "Spices & High-Value",
        "shelfLife": "365 Days",
        "harvestDate": "10 Sep 2026",
        "image": "assets/images/turmeric.jpg",
        "grade": "Double Polished Export Grade",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "50 Qt (5,000 kg)",
        "quantityNumber": 50,
        "expectedPrice": "₹ 135.00 /kg (₹ 13,500 /Qt)",
        "expectedPriceNumber": 13500,
        "bestBid": "₹ 144.45 /kg (₹ 14,445 /Qt)",
        "bestBidNumber": 14445,
        "buyerName": "Mahagrapes Co-op Federation",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Sangli APMC Turmeric Terminal"
    },
    {
        "id": "LOT-POM-07",
        "crop": "Bhagwa Pomegranate (Solapur Export Grade)",
        "category": "Fruits",
        "shelfLife": "20 Days",
        "harvestDate": "11 Sep 2026",
        "image": "assets/images/pomegranate.jpg?v=2",
        "grade": "Grade A (250g+ Calibrated)",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "40 Qt (4,000 kg)",
        "quantityNumber": 40,
        "expectedPrice": "₹ 88.00 /kg (₹ 8,800 /Qt)",
        "expectedPriceNumber": 8800,
        "bestBid": "₹ 95.92 /kg (₹ 9,592 /Qt)",
        "bestBidNumber": 9592,
        "buyerName": "LuLu Hypermarket Gulf Supply",
        "status": "Negotiation",
        "statusBadgeClass": "badge-status-negotiation",
        "location": "Pandharpur Yard, Solapur"
    },
    {
        "id": "LOT-COT-08",
        "crop": "Raw Cotton (Vidarbha Long Staple)",
        "category": "Cash Crops",
        "shelfLife": "365 Days",
        "harvestDate": "12 Sep 2026",
        "image": "assets/images/cotton.jpg?v=2",
        "grade": "Grade A Staple >29mm",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "90 Qt (9,000 kg)",
        "quantityNumber": 90,
        "expectedPrice": "₹ 62.00 /kg (₹ 6,200 /Qt)",
        "expectedPriceNumber": 6200,
        "bestBid": "₹ 68.82 /kg (₹ 6,882 /Qt)",
        "bestBidNumber": 6882,
        "buyerName": "Everest Spices & Commodities",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Amravati APMC Cotton Yard"
    },
    {
        "id": "LOT-RIC-09",
        "crop": "Wada Kolam Rice (Palghar GI Quality)",
        "category": "Grains & Cereals",
        "shelfLife": "180 Days",
        "harvestDate": "13 Sep 2026",
        "image": "assets/images/rice.jpg?v=1",
        "grade": "Grade A Aged Aromatic",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "120 Qt (12,000 kg)",
        "quantityNumber": 120,
        "expectedPrice": "₹ 48.00 /kg (₹ 4,800 /Qt)",
        "expectedPriceNumber": 4800,
        "bestBid": "₹ 50.40 /kg (₹ 5,040 /Qt)",
        "bestBidNumber": 5040,
        "buyerName": "ITC Agri-Business Division",
        "status": "Dispatched",
        "statusBadgeClass": "badge-status-dispatched",
        "location": "Wada APMC Yard, Palghar"
    },
    {
        "id": "LOT-JOW-10",
        "crop": "Solapur Maldandi Jowar (Sorghum)",
        "category": "Grains & Cereals",
        "shelfLife": "180 Days",
        "harvestDate": "14 Sep 2026",
        "image": "assets/images/jowar.jpg?v=1",
        "grade": "Grade A Bold White",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "100 Qt (10,000 kg)",
        "quantityNumber": 100,
        "expectedPrice": "₹ 34.00 /kg (₹ 3,400 /Qt)",
        "expectedPriceNumber": 3400,
        "bestBid": "₹ 36.38 /kg (₹ 3,638 /Qt)",
        "bestBidNumber": 3638,
        "buyerName": "Raymond Textile Mills",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Solapur APMC Grain Terminal"
    },
    {
        "id": "LOT-BAJ-11",
        "crop": "Dhule Hybrid Pearl Millet (Bajra)",
        "category": "Grains & Cereals",
        "shelfLife": "180 Days",
        "harvestDate": "10 Sep 2026",
        "image": "assets/images/bajra.jpg?v=1",
        "grade": "Grade A Machine Cleaned",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "140 Qt (14,000 kg)",
        "quantityNumber": 140,
        "expectedPrice": "₹ 26.00 /kg (₹ 2,600 /Qt)",
        "expectedPriceNumber": 2600,
        "bestBid": "₹ 28.34 /kg (₹ 2,834 /Qt)",
        "bestBidNumber": 2834,
        "buyerName": "BigBasket Direct Farm Sourcing",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Dhule APMC Mandi"
    },
    {
        "id": "LOT-WHT-12",
        "crop": "Sharbati Lokwan Golden Wheat",
        "category": "Grains & Cereals",
        "shelfLife": "180 Days",
        "harvestDate": "11 Sep 2026",
        "image": "assets/images/wheat.jpg?v=1",
        "grade": "Grade A+ Luster Golden",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "200 Qt (20,000 kg)",
        "quantityNumber": 200,
        "expectedPrice": "₹ 28.50 /kg (₹ 2,850 /Qt)",
        "expectedPriceNumber": 2850,
        "bestBid": "₹ 31.64 /kg (₹ 3,164 /Qt)",
        "bestBidNumber": 3164,
        "buyerName": "Reliance Fresh Supply Chain",
        "status": "Negotiation",
        "statusBadgeClass": "badge-status-negotiation",
        "location": "Niphad APMC Hub, Nashik"
    },
    {
        "id": "LOT-TUR-13",
        "crop": "Latur Red Tur (Pigeon Pea / Arhar)",
        "category": "Pulses & Legumes",
        "shelfLife": "180 Days",
        "harvestDate": "12 Sep 2026",
        "image": "assets/images/tur.jpg?v=2",
        "grade": "Grade A Maruti Premium",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "80 Qt (8,000 kg)",
        "quantityNumber": 80,
        "expectedPrice": "₹ 85.00 /kg (₹ 8,500 /Qt)",
        "expectedPriceNumber": 8500,
        "bestBid": "₹ 89.25 /kg (₹ 8,925 /Qt)",
        "bestBidNumber": 8925,
        "buyerName": "Adani Wilmar Agri Procurement",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Latur Pulses Yard"
    },
    {
        "id": "LOT-GRA-14",
        "crop": "Akola Desi Chana (Bengal Gram)",
        "category": "Pulses & Legumes",
        "shelfLife": "180 Days",
        "harvestDate": "13 Sep 2026",
        "image": "assets/images/chana.jpg?v=1",
        "grade": "Grade A Bold Digvijay",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "110 Qt (11,000 kg)",
        "quantityNumber": 110,
        "expectedPrice": "₹ 58.00 /kg (₹ 5,800 /Qt)",
        "expectedPriceNumber": 5800,
        "bestBid": "₹ 62.06 /kg (₹ 6,206 /Qt)",
        "bestBidNumber": 6206,
        "buyerName": "DMart Wholesale (Avenue Supermarts)",
        "status": "Dispatched",
        "statusBadgeClass": "badge-status-dispatched",
        "location": "Akola APMC Yard"
    },
    {
        "id": "LOT-MUN-15",
        "crop": "Jalgaon Shiny Green Mung Bean",
        "category": "Pulses & Legumes",
        "shelfLife": "180 Days",
        "harvestDate": "14 Sep 2026",
        "image": "assets/images/mung.jpg?v=1",
        "grade": "Grade A Bold Luster",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "60 Qt (6,000 kg)",
        "quantityNumber": 60,
        "expectedPrice": "₹ 78.00 /kg (₹ 7,800 /Qt)",
        "expectedPriceNumber": 7800,
        "bestBid": "₹ 85.02 /kg (₹ 8,502 /Qt)",
        "bestBidNumber": 8502,
        "buyerName": "Kay Bee Exports International",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Jalgaon APMC Market"
    },
    {
        "id": "LOT-URA-16",
        "crop": "Nanded Black Urad Dal (Black Gram)",
        "category": "Pulses & Legumes",
        "shelfLife": "180 Days",
        "harvestDate": "10 Sep 2026",
        "image": "assets/images/urad.jpg?v=2",
        "grade": "Grade A Machine Polished",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "70 Qt (7,000 kg)",
        "quantityNumber": 70,
        "expectedPrice": "₹ 72.00 /kg (₹ 7,200 /Qt)",
        "expectedPriceNumber": 7200,
        "bestBid": "₹ 79.92 /kg (₹ 7,992 /Qt)",
        "bestBidNumber": 7992,
        "buyerName": "Mahagrapes Co-op Federation",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Nanded APMC Hub"
    },
    {
        "id": "LOT-GND-17",
        "crop": "Kolhapur Bold Groundnut (Peanut)",
        "category": "Oilseeds",
        "shelfLife": "180 Days",
        "harvestDate": "11 Sep 2026",
        "image": "assets/images/groundnut.jpg?v=1",
        "grade": "Grade A Bold 80/90 Count",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "90 Qt (9,000 kg)",
        "quantityNumber": 90,
        "expectedPrice": "₹ 68.00 /kg (₹ 6,800 /Qt)",
        "expectedPriceNumber": 6800,
        "bestBid": "₹ 71.40 /kg (₹ 7,140 /Qt)",
        "bestBidNumber": 7140,
        "buyerName": "LuLu Hypermarket Gulf Supply",
        "status": "Negotiation",
        "statusBadgeClass": "badge-status-negotiation",
        "location": "Vadgaon APMC, Kolhapur"
    },
    {
        "id": "LOT-SUN-18",
        "crop": "Beed High-Oil Sunflower Seeds",
        "category": "Oilseeds",
        "shelfLife": "180 Days",
        "harvestDate": "12 Sep 2026",
        "image": "assets/images/sunflower.jpg?v=2",
        "grade": "Grade A Oil >40%",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "85 Qt (8,500 kg)",
        "quantityNumber": 85,
        "expectedPrice": "₹ 54.00 /kg (₹ 5,400 /Qt)",
        "expectedPriceNumber": 5400,
        "bestBid": "₹ 57.78 /kg (₹ 5,778 /Qt)",
        "bestBidNumber": 5778,
        "buyerName": "Everest Spices & Commodities",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Beed APMC Yard"
    },
    {
        "id": "LOT-SUG-19",
        "crop": "Kolhapur Co 86032 Sugarcane",
        "category": "Cash Crops",
        "shelfLife": "180 Days",
        "harvestDate": "13 Sep 2026",
        "image": "assets/images/sugarcane.jpg?v=1",
        "grade": "Grade A High-Brix (>21°)",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "1000 Qt (1,00,000 kg)",
        "quantityNumber": 1000,
        "expectedPrice": "₹ 3.40 /kg (₹ 340 /Qt)",
        "expectedPriceNumber": 340,
        "bestBid": "₹ 3.71 /kg (₹ 371 /Qt)",
        "bestBidNumber": 371,
        "buyerName": "ITC Agri-Business Division",
        "status": "Dispatched",
        "statusBadgeClass": "badge-status-dispatched",
        "location": "Shirol Sugar Belt, Kolhapur"
    },
    {
        "id": "LOT-MAN-20",
        "crop": "Ratnagiri Alphonso (Hapus) Mango",
        "category": "Fruits",
        "shelfLife": "7 Days (Perishable)",
        "harvestDate": "14 Sep 2026",
        "image": "assets/images/mango.jpg?v=2",
        "grade": "GI Tagged Export Grade (220g+)",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "30 Qt (3,000 kg)",
        "quantityNumber": 30,
        "expectedPrice": "₹ 180.00 /kg (₹ 18,000 /Qt)",
        "expectedPriceNumber": 18000,
        "bestBid": "₹ 199.80 /kg (₹ 19,980 /Qt)",
        "bestBidNumber": 19980,
        "buyerName": "Raymond Textile Mills",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Devgad Coastal Belt, Ratnagiri"
    },
    {
        "id": "LOT-GRP-21",
        "crop": "Nashik Thompson Seedless Grapes",
        "category": "Fruits",
        "shelfLife": "10 Days",
        "harvestDate": "10 Sep 2026",
        "image": "assets/images/grapes.jpg?v=2",
        "grade": "Grade A Export Calibrated (Brix >18°)",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "75 Qt (7,500 kg)",
        "quantityNumber": 75,
        "expectedPrice": "₹ 65.00 /kg (₹ 6,500 /Qt)",
        "expectedPriceNumber": 6500,
        "bestBid": "₹ 68.25 /kg (₹ 6,825 /Qt)",
        "bestBidNumber": 6825,
        "buyerName": "BigBasket Direct Farm Sourcing",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Pimpalgaon Baswant, Nashik"
    },
    {
        "id": "LOT-MOS-22",
        "crop": "Jalna Sweet Lime (Mosambi)",
        "category": "Fruits",
        "shelfLife": "14 Days",
        "harvestDate": "11 Sep 2026",
        "image": "assets/images/mosambi.jpg?v=1",
        "grade": "Grade A Juicy Calibrated",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "90 Qt (9,000 kg)",
        "quantityNumber": 90,
        "expectedPrice": "₹ 32.00 /kg (₹ 3,200 /Qt)",
        "expectedPriceNumber": 3200,
        "bestBid": "₹ 34.24 /kg (₹ 3,424 /Qt)",
        "bestBidNumber": 3424,
        "buyerName": "Reliance Fresh Supply Chain",
        "status": "Negotiation",
        "statusBadgeClass": "badge-status-negotiation",
        "location": "Badnapur Mandi, Jalna"
    },
    {
        "id": "LOT-CUS-23",
        "crop": "Beed Balanagar Custard Apple (Sitaphal)",
        "category": "Fruits",
        "shelfLife": "4 Days (Perishable)",
        "harvestDate": "12 Sep 2026",
        "image": "assets/images/custard_apple.jpg?v=1",
        "grade": "Grade A Premium Pulp (300g+)",
        "gradeBadgeClass": "badge-grade-a",
        "quantity": "45 Qt (4,500 kg)",
        "quantityNumber": 45,
        "expectedPrice": "₹ 75.00 /kg (₹ 7,500 /Qt)",
        "expectedPriceNumber": 7500,
        "bestBid": "₹ 81.75 /kg (₹ 8,175 /Qt)",
        "bestBidNumber": 8175,
        "buyerName": "Adani Wilmar Agri Procurement",
        "status": "Bids Open",
        "statusBadgeClass": "badge-status-open",
        "location": "Dharur Hill Belt, Beed"
>>>>>>> eb7b2131bbe40c41866443d60354b6bb55c668b5
    }
],
  mandiPrices: [
    {
<<<<<<< HEAD
      crop: "Tomato",
      currentPrice: "₹ 12.00 /kg (₹ 1,200 /Qt)",
=======
      crop: "Red Onion (Nashik)",
      currentPrice: "₹ 18.00 /kg (₹ 1,800 /Qt)",
>>>>>>> eb7b2131bbe40c41866443d60354b6bb55c668b5
      trendPercent: "+6.2%",
      direction: "up",
      trendPoints: [20, 16, 18, 12, 14, 8, 4]
    },
    {
      crop: "Tomato (Narayangaon)",
      currentPrice: "₹ 13.00 /kg (₹ 1,300 /Qt)",
      trendPercent: "+4.8%",
      direction: "up",
      trendPoints: [22, 19, 16, 14, 11, 7, 5]
    },
    {
      crop: "Yellow Soybean (Latur)",
      currentPrice: "₹ 42.00 /kg (₹ 4,200 /Qt)",
      trendPercent: "+3.5%",
      direction: "up",
      trendPoints: [18, 17, 19, 15, 12, 9, 7]
    },
    {
      crop: "Raw Cotton (Amravati)",
      currentPrice: "₹ 62.00 /kg (₹ 6,200 /Qt)",
      trendPercent: "-1.2%",
      direction: "down",
      trendPoints: [5, 8, 12, 9, 14, 18, 22]
    },
    {
      crop: "Sangli Rajapuri Turmeric",
      currentPrice: "₹ 135.00 /kg (₹ 13,500 /Qt)",
      trendPercent: "+7.4%",
      direction: "up",
      trendPoints: [12, 15, 18, 20, 24, 28, 32]
    },
    {
      crop: "Alphonso Mango (Ratnagiri)",
      currentPrice: "₹ 180.00 /kg (₹ 18,000 /Qt)",
      trendPercent: "+9.1%",
      direction: "up",
      trendPoints: [8, 12, 16, 21, 25, 29, 35]
    }
  ],
  forecast: {
    crop: "Red Onion (Nashik Garwa)",
    image: "assets/images/onion.jpg",
    timeframe: "Next 7 days",
    percentage: "+8.5% *",
    subtext: "(Expected)",
    description: "Market trend is positive. Prices expected to rise across Lasalgaon & Vashi APMC mandis due to strong export demand."
  },
  shipmentTracking: {
    orderId: "#AG12345",
<<<<<<< HEAD
    crop: "Tomato (Shivam Hybrid)",
    quantity: "50 Qt",
    image: "assets/images/tomato.jpg",
    status: "In Transit"
=======
    crop: "Red Onion",
    quantity: "100 Qt",
    image: "assets/images/onion.jpg",
    status: "In Transit to Vashi Terminal"
>>>>>>> eb7b2131bbe40c41866443d60354b6bb55c668b5
  }
};
