/**
 * AgriNex - Farmer Module Enterprise Data Store
 */

const farmerData = {
  profile: {
    name: "Ramesh Patil",
    role: "Farmer",
    location: "Nashik, Maharashtra",
    avatar: "assets/images/farmer-avatar.jpg",
    notificationsCount: 2,
    messagesCount: 1
  },
  stats: {
    totalLots: 7,
    activeListingsSubtitle: "Active listings",
    activeBids: 6,
    buyersSubtitle: "Buyers interested",
    pendingShipments: 1,
    shipmentSubtitle: "In transit",
    estimatedProfit: "₹ 10,95,000",
    profitSubtitle: "(Expected gross value)"
  },
  listings: [
    {
      id: "LOT-TOM-01",
      crop: "Tomato (Shivam Hybrid)",
      category: "Vegetables",
      shelfLife: "3 Days (Perishable)",
      harvestDate: "12 Sep 2026",
      image: "assets/images/tomato.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "50 Qt (5,000 kg)",
      quantityNumber: 50,
      expectedPrice: "₹ 12.00 /kg (₹ 1,200 /Qt)",
      expectedPriceNumber: 1200,
      bestBid: "₹ 12.50 /kg (₹ 1,250 /Qt)",
      bestBidNumber: 1250,
      buyerName: "AgriFoods Ltd.",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Nashik APMC Mandi, MH"
    },
    {
      id: "LOT-ONI-02",
      crop: "Red Onion (Nashik Quality)",
      category: "Vegetables",
      shelfLife: "25 Days",
      harvestDate: "10 Sep 2026",
      image: "assets/images/onion.jpg",
      grade: "Grade B",
      gradeBadgeClass: "badge-grade-b",
      quantity: "30 Qt (3,000 kg)",
      quantityNumber: 30,
      expectedPrice: "₹ 9.00 /kg (₹ 900 /Qt)",
      expectedPriceNumber: 900,
      bestBid: "₹ 9.50 /kg (₹ 950 /Qt)",
      bestBidNumber: 950,
      buyerName: "Global Grains Direct",
      status: "Negotiation",
      statusBadgeClass: "badge-status-negotiation",
      location: "Lasalgaon Mandi Yard, MH"
    },
    {
      id: "LOT-PAD-03",
      crop: "Paddy (1121 Basmati)",
      category: "Grains & Cereals",
      shelfLife: "180 Days",
      harvestDate: "05 Sep 2026",
      image: "assets/images/paddy.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "100 Qt (10,000 kg)",
      quantityNumber: 100,
      expectedPrice: "₹ 20.00 /kg (₹ 2,000 /Qt)",
      expectedPriceNumber: 2000,
      bestBid: "₹ 20.80 /kg (₹ 2,080 /Qt)",
      bestBidNumber: 2080,
      buyerName: "Fresh Mart Wholesale",
      status: "Dispatched",
      statusBadgeClass: "badge-status-dispatched",
      location: "Nashik Central Agro Warehouse, MH"
    },
    {
      id: "LOT-CHL-04",
      crop: "Green Chilli (G4 Spicy)",
      category: "Spices & High-Value",
      shelfLife: "5 Days (Perishable)",
      harvestDate: "11 Sep 2026",
      image: "assets/images/chilli.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "25 Qt (2,500 kg)",
      quantityNumber: 25,
      expectedPrice: "₹ 32.00 /kg (₹ 3,200 /Qt)",
      expectedPriceNumber: 3200,
      bestBid: "₹ 33.50 /kg (₹ 3,350 /Qt)",
      bestBidNumber: 3350,
      buyerName: "Spices Exim Hub",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Pimpalgaon APMC, MH"
    },
    {
      id: "LOT-COT-05",
      crop: "Raw Cotton (MCU-5 Long Staple)",
      category: "Cash Crops",
      shelfLife: "365 Days",
      harvestDate: "01 Sep 2026",
      image: "assets/images/cotton.jpg",
      grade: "Grade A",
      gradeBadgeClass: "badge-grade-a",
      quantity: "80 Qt (8,000 kg)",
      quantityNumber: 80,
      expectedPrice: "₹ 58.00 /kg (₹ 5,800 /Qt)",
      expectedPriceNumber: 5800,
      bestBid: "₹ 59.50 /kg (₹ 5,950 /Qt)",
      bestBidNumber: 5950,
      buyerName: "Malegaon Cotton Textiles",
      status: "Negotiation",
      statusBadgeClass: "badge-status-negotiation",
      location: "Malegaon Mandi Yard, MH"
    },
    {
      id: "LOT-OKR-06",
      crop: "Fresh Okra (Ladyfinger)",
      category: "Vegetables",
      shelfLife: "2 Days (Perishable)",
      harvestDate: "13 Sep 2026",
      image: "assets/images/okra.jpg",
      grade: "Grade B",
      gradeBadgeClass: "badge-grade-b",
      quantity: "20 Qt (2,000 kg)",
      quantityNumber: 20,
      expectedPrice: "₹ 16.00 /kg (₹ 1,600 /Qt)",
      expectedPriceNumber: 1600,
      bestBid: "₹ 16.80 /kg (₹ 1,680 /Qt)",
      bestBidNumber: 1680,
      buyerName: "Annapoorna Caterers",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Nashik APMC Mandi, MH"
    },
    {
      id: "LOT-TUR-07",
      crop: "Salem Turmeric Finger (High Curcumin)",
      category: "Spices & High-Value",
      shelfLife: "365 Days",
      harvestDate: "28 Aug 2026",
      image: "assets/images/turmeric.jpg",
      grade: "Grade A Export Quality",
      gradeBadgeClass: "badge-grade-a",
      quantity: "25 Qt (2,500 kg)",
      quantityNumber: 25,
      expectedPrice: "₹ 141.00 /kg (₹ 14,100 /Qt)",
      expectedPriceNumber: 14100,
      bestBid: "₹ 143.00 /kg (₹ 14,300 /Qt)",
      bestBidNumber: 14300,
      buyerName: "Aroma Spices International",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Sangli Spices Hub, MH"
    }
  ],
  mandiPrices: [
    {
      crop: "Tomato",
      currentPrice: "₹ 12.00 /kg (₹ 1,200 /Qt)",
      trendPercent: "+6.2%",
      direction: "up",
      trendPoints: [20, 16, 18, 12, 14, 8, 4]
    },
    {
      crop: "Onion",
      currentPrice: "₹ 9.00 /kg (₹ 900 /Qt)",
      trendPercent: "+4.8%",
      direction: "up",
      trendPoints: [22, 19, 16, 14, 11, 7, 5]
    },
    {
      crop: "Paddy",
      currentPrice: "₹ 20.00 /kg (₹ 2,000 /Qt)",
      trendPercent: "+3.5%",
      direction: "up",
      trendPoints: [18, 17, 19, 15, 12, 9, 7]
    },
    {
      crop: "Cotton",
      currentPrice: "₹ 58.00 /kg (₹ 5,800 /Qt)",
      trendPercent: "-1.2%",
      direction: "down",
      trendPoints: [5, 8, 12, 9, 14, 18, 22]
    }
  ],
  forecast: {
    crop: "Tomato",
    image: "assets/images/tomato.jpg",
    timeframe: "Next 7 days",
    percentage: "+8.5% *",
    subtext: "(Expected)",
    description: "Market trend is positive. Prices are expected to rise in the next 7 days."
  },
  shipmentTracking: {
    orderId: "#AG12345",
    crop: "Tomato (Shivam Hybrid)",
    quantity: "50 Qt",
    image: "assets/images/tomato.jpg",
    status: "In Transit"
  }
};
