/**
 * AgriNex - Farmer Module Enterprise Data Store
 * Grounded in Maharashtra Agricultural Hubs, APMC Mandis, and Regional Produce
 * Standardized in ₹/kg pricing across all commodity lots, demands, and forecasts.
 */

const farmerData = {
  profile: {
    name: "Patil Rameshwar",
    role: "Progressive Farmer & FPO Director",
    location: "Lasalgaon APMC Yard, Nashik, Maharashtra",
    avatar: "assets/images/farmer-avatar.jpg",
    notificationsCount: 3,
    messagesCount: 2
  },
  stats: {
    totalLots: 8,
    activeListingsSubtitle: "Active verified listings",
    activeBids: 12,
    buyersSubtitle: "Buyers interested across Maharashtra",
    pendingShipments: 2,
    shipmentSubtitle: "In transit to Vashi & Pune APMC",
    estimatedProfit: "₹ 14,85,000",
    profitSubtitle: "(Expected gross value)"
  },
  listings: [
    {
      id: "LOT-ONI-01",
      crop: "Red Onion (Nashik Garwa Quality)",
      category: "Vegetables",
      shelfLife: "25 Days",
      harvestDate: "10 Sep 2026",
      image: "assets/images/onion.jpg",
      grade: "Grade A Export Calibrated",
      gradeBadgeClass: "badge-grade-a",
      quantity: "100 Qt (10,000 kg)",
      quantityNumber: 100,
      expectedPrice: "₹ 18.00 /kg (₹ 1,800 /Qt)",
      expectedPriceNumber: 1800,
      bestBid: "₹ 19.20 /kg (₹ 1,920 /Qt)",
      bestBidNumber: 1920,
      buyerName: "BigBasket Direct Sourcing",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Lasalgaon APMC Yard, Nashik, MH"
    },
    {
      id: "LOT-TOM-02",
      crop: "Tomato (Shivam / Abhinav Hybrid)",
      category: "Vegetables",
      shelfLife: "4 Days (Perishable)",
      harvestDate: "12 Sep 2026",
      image: "assets/images/tomato.jpg?v=2",
      grade: "Grade A Red Firm",
      gradeBadgeClass: "badge-grade-a",
      quantity: "50 Qt (5,000 kg)",
      quantityNumber: 50,
      expectedPrice: "₹ 22.00 /kg (₹ 2,200 /Qt)",
      expectedPriceNumber: 2200,
      bestBid: "₹ 23.50 /kg (₹ 2,350 /Qt)",
      bestBidNumber: 2350,
      buyerName: "Reliance Fresh Supply Chain",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Narayangaon Mandi Yard, Junnar, MH"
    },
    {
      id: "LOT-SOY-04",
      crop: "Yellow Soybean (Latur JS 335)",
      category: "Oilseeds",
      shelfLife: "180 Days",
      harvestDate: "05 Sep 2026",
      image: "assets/images/soybean.jpg?v=3",
      grade: "Grade A Premium High-Oil",
      gradeBadgeClass: "badge-grade-a",
      quantity: "150 Qt (15,000 kg)",
      quantityNumber: 150,
      expectedPrice: "₹ 46.00 /kg (₹ 4,600 /Qt)",
      expectedPriceNumber: 4600,
      bestBid: "₹ 47.80 /kg (₹ 4,780 /Qt)",
      bestBidNumber: 4780,
      buyerName: "Adani Wilmar Solvent Extraction",
      status: "Negotiation",
      statusBadgeClass: "badge-status-negotiation",
      location: "Latur APMC Yard, MH"
    },
    {
      id: "LOT-TUR-06",
      crop: "Sangli Rajapuri Turmeric",
      category: "Spices",
      shelfLife: "365 Days",
      harvestDate: "28 Aug 2026",
      image: "assets/images/turmeric.jpg",
      grade: "GI Grade Curcumin >4.5%",
      gradeBadgeClass: "badge-grade-a",
      quantity: "60 Qt (6,000 kg)",
      quantityNumber: 60,
      expectedPrice: "₹ 125.00 /kg (₹ 12,500 /Qt)",
      expectedPriceNumber: 12500,
      bestBid: "₹ 128.50 /kg (₹ 12,850 /Qt)",
      bestBidNumber: 12850,
      buyerName: "Everest Spices Exim",
      status: "Dispatched",
      statusBadgeClass: "badge-status-dispatched",
      location: "Sangli APMC Spices Hub, MH"
    },
    {
      id: "LOT-COT-08",
      crop: "Raw Cotton (Yavatmal / Amravati)",
      category: "Cash Crops",
      shelfLife: "365 Days",
      harvestDate: "01 Sep 2026",
      image: "assets/images/cotton.jpg?v=2",
      grade: "Grade A Staple >29mm",
      gradeBadgeClass: "badge-grade-a",
      quantity: "90 Qt (9,000 kg)",
      quantityNumber: 90,
      expectedPrice: "₹ 62.00 /kg (₹ 6,200 /Qt)",
      expectedPriceNumber: 6200,
      bestBid: "₹ 64.00 /kg (₹ 6,400 /Qt)",
      bestBidNumber: 6400,
      buyerName: "Raymond Textile Mills, Amravati",
      status: "Negotiation",
      statusBadgeClass: "badge-status-negotiation",
      location: "Amravati APMC Cotton Yard, MH"
    },
    {
      id: "LOT-RIC-09",
      crop: "Wada Kolam Rice (Palghar GI Quality)",
      category: "Grains & Cereals",
      shelfLife: "180 Days",
      harvestDate: "02 Sep 2026",
      image: "assets/images/rice.jpg?v=1",
      grade: "Grade A Aged Aromatic",
      gradeBadgeClass: "badge-grade-a",
      quantity: "120 Qt (12,000 kg)",
      quantityNumber: 120,
      expectedPrice: "₹ 48.00 /kg (₹ 4,800 /Qt)",
      expectedPriceNumber: 4800,
      bestBid: "₹ 49.50 /kg (₹ 4,950 /Qt)",
      bestBidNumber: 4950,
      buyerName: "DMart Wholesale (Avenue Supermarts)",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Wada APMC Yard, Palghar, MH"
    },
    {
      id: "LOT-MAN-20",
      crop: "Ratnagiri Alphonso (Hapus) Mango",
      category: "Fruits",
      shelfLife: "7 Days",
      harvestDate: "14 Sep 2026",
      image: "assets/images/mango.jpg?v=2",
      grade: "Grade A GI Export Choice",
      gradeBadgeClass: "badge-grade-a",
      quantity: "40 Qt (4,000 kg)",
      quantityNumber: 40,
      expectedPrice: "₹ 180.00 /kg (₹ 18,000 /Qt)",
      expectedPriceNumber: 18000,
      bestBid: "₹ 192.00 /kg (₹ 19,200 /Qt)",
      bestBidNumber: 19200,
      buyerName: "Kay Bee Exports International",
      status: "Bids Open",
      statusBadgeClass: "badge-status-open",
      location: "Devgad / Ratnagiri APMC Terminal, MH"
    },
    {
      id: "LOT-GRP-21",
      crop: "Nashik Thompson Seedless Grapes",
      category: "Fruits",
      shelfLife: "10 Days",
      harvestDate: "11 Sep 2026",
      image: "assets/images/grapes.jpg?v=2",
      grade: "Grade A Cold Storage Export",
      gradeBadgeClass: "badge-grade-a",
      quantity: "75 Qt (7,500 kg)",
      quantityNumber: 75,
      expectedPrice: "₹ 75.00 /kg (₹ 7,500 /Qt)",
      expectedPriceNumber: 7500,
      bestBid: "₹ 78.50 /kg (₹ 7,850 /Qt)",
      bestBidNumber: 7850,
      buyerName: "Mahagrapes Co-op Export Federation",
      status: "Dispatched",
      statusBadgeClass: "badge-status-dispatched",
      location: "Pimpalgaon APMC Yard, Nashik, MH"
    }
  ],
  mandiPrices: [
    {
      crop: "Red Onion (Nashik)",
      currentPrice: "₹ 18.00 /kg (₹ 1,800 /Qt)",
      trendPercent: "+6.2%",
      direction: "up",
      trendPoints: [20, 16, 18, 12, 14, 8, 4]
    },
    {
      crop: "Tomato (Narayangaon)",
      currentPrice: "₹ 22.00 /kg (₹ 2,200 /Qt)",
      trendPercent: "+4.8%",
      direction: "up",
      trendPoints: [22, 19, 16, 14, 11, 7, 5]
    },
    {
      crop: "Yellow Soybean (Latur)",
      currentPrice: "₹ 46.00 /kg (₹ 4,600 /Qt)",
      trendPercent: "+3.5%",
      direction: "up",
      trendPoints: [18, 17, 19, 15, 12, 9, 7]
    },
    {
      crop: "Raw Cotton (Amravati)",
      currentPrice: "₹ 62.00 /kg (₹ 6,200 /Qt)",
      trendPercent: "-1.2%",
      direction: "down",
      trendPoints: [5, 8, 12, 9, 14, 18, 22]
    }
  ],
  forecast: {
    crop: "Red Onion (Nashik Garwa)",
    image: "assets/images/onion.jpg",
    timeframe: "Next 7 days",
    percentage: "+8.5% *",
    subtext: "(Expected)",
    description: "Market trend is positive. Prices expected to rise across Lasalgaon & Vashi APMC mandis due to strong export demand."
  },
  shipmentTracking: {
    orderId: "#AG12345",
    crop: "Red Onion",
    quantity: "100 Qt",
    image: "assets/images/onion.jpg",
    status: "In Transit to Vashi Terminal"
  }
};
