/**
 * AgriNex Enterprise Logistics & Cold-Chain Fleet Data Store
 * Regional Supply Chain: Maharashtra (Nashik, Sangli, Pimpalgaon, Pune, Mumbai, Thane, Bhiwandi)
 */

const logisticsData = {
  profile: {
    name: "Dinesh Yadav",
    company: "AgriNex Fleet & Cold-Chain Logistics",
    role: "Verified Fleet Partner",
    location: "Nashik APMC Regional Aggregation Hub, Maharashtra",
    driverId: "DRV-MH-8910",
    phone: "+91 98230 45892",
    vehicleNo: "Tata Ace EV (MH-15-AX-8910)",
    vehicleTag: "TATA ACE EV • MH-15-AX-8910",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80",
    rating: "4.92",
    tripsCompleted: 428,
    ratingScore: "4.92 Rating • 428 Trips Completed",
    status: "ONLINE",
    totalTrips: 428,
    onTimeScore: "99.8%",
    kycStatus: "Verified Fleet Partner",
    upiId: "9842199812@okhdfcbank",
    settledToday: 3840,
    inTripPay: 1650,
    tripsToday: 3,
    distanceTodayKm: 142,
    evBatteryPct: 84,
    batteryRangeKm: 110
  },
  driverConsole: {
    activeMissionCode: "CLUSTER-AGX-801",
    settledToday: 3840,
    inTripPay: 1650,
    tripsToday: 3,
    distanceTodayKm: 142,
    evBatteryPct: 84,
    batteryRangeKm: 110,
    linkedUpi: "9842199812@okhdfcbank",
    isOnline: true
  },
  stats: {
    activeFleet: 24,
    activeFleetSubtitle: "Trucks connected via Haversine Telematics",
    inTransitConsignments: 4,
    inTransitSubtitle: "Active live highway trips",
    onTimeRate: "99.4%",
    onTimeSubtitle: "Zero transit spoilages",
    freightEarnings: "₹ 4,86,500",
    earningsSubtitle: "Smart escrow settlements"
  },
  telemetry: {
    vehicleNo: "TN-33-AX-8910",
    model: "Tata Ace EV Smart Commercial Carrier",
    temperatureC: 4.8,
    tempStatus: "Optimal (4.0°C - 6.0°C)",
    humidityPct: 86,
    freshnessScore: "98.4%",
    speedKmh: 54,
    evBatteryPct: 84,
    fuelRangeKm: "110 km",
    currentLocation: "NH 544 Highway Corridor, Erode - Salem Belt",
    destination: "Erode Mandi Central Aggregation Hub",
    lastGpsPing: "Just now (Haversine Telematics)",
    calculationMethod: "Haversine Great-Circle Geodesic Formula (Pure Latitude & Longitude - No GPS hardware dependency)"
  },
  dispatchOrders: [
    {
      id: 0,
      orderCode: "CLUSTER-AGX-801",
      orderType: "cluster_pool",
      typeLabel: "3-Village Tomato Collection",
      poolTag: "POOL #801",
      title: "CLUSTER-AGX-801 • 3-Village Tomato Collection",
      cropName: "Fresh Roma Tomatoes (48 Crates - 1.2 Tonnes)",
      image: "assets/images/tomato.jpg",
      quantityQt: 12,
      quantityKg: 1200,
      cargoPackaging: "48 Crates (1.2 Tonnes)",
      pickupFarmerName: "Ravi Kumar & Cluster Farmers",
      pickupFarmerPhone: "+91 98421 11201",
      pickupAddress: "Farmgate A, Thindal, Erode, TN 638012",
      pickupCoords: [11.3190, 77.6880],
      deliveryAddress: "Erode Mandi Central Aggregation Hub, Dock #4, TN 638001",
      deliveryCoords: [11.3410, 77.7172],
      currentTruckCoords: [11.3000, 77.6500],
      speedKmh: 54,
      truckSpeed: "54 km/h",
      activeStopIndex: 0,
      stops: [
        {
          index: 0,
          label: "Stop 1: Farmgate A - Thindal (Farmer: Ravi Kumar)",
          shortTitle: "Stop 1 (Thindal)",
          locationName: "Farmgate A - Thindal",
          farmerName: "Ravi Kumar",
          farmerPhone: "+91 98421 11201",
          coords: [11.3190, 77.6880],
          loadText: "Load: 350 kg Fresh Tomatoes (14 Crates) • Share: ₹481",
          crates: 14,
          weightKg: 350,
          sharePay: 481,
          status: "IN PROGRESS",
          isCurrent: true,
          otp: "7291"
        },
        {
          index: 1,
          label: "Stop 2: Farmgate B - Perundurai (Farmer: Senthil Vel)",
          shortTitle: "Stop 2 (Perundurai)",
          locationName: "Farmgate B - Perundurai",
          farmerName: "Senthil Vel",
          farmerPhone: "+91 98421 33490",
          coords: [11.2750, 77.5850],
          loadText: "Load: 450 kg Fresh Tomatoes (18 Crates) • Share: ₹619",
          crates: 18,
          weightKg: 450,
          sharePay: 619,
          status: "Pending",
          isCurrent: false,
          otp: "4819"
        },
        {
          index: 2,
          label: "Stop 3: Erode Mandi Central Aggregation Hub",
          shortTitle: "Erode Mandi Hub",
          locationName: "Erode Central Mandi Aggregation Hub",
          farmerName: "Erode APMC Central Dock",
          farmerPhone: "+91 98421 88710",
          coords: [11.3410, 77.7172],
          loadText: "Final Unloading: All 48 Crates (1.2 Tonnes) • Terminal Release: ₹550",
          crates: 48,
          weightKg: 1200,
          sharePay: 550,
          status: "Pending",
          isCurrent: false,
          pin: "8821"
        }
      ],
      shortestDistanceKm: 29.7,
      highwayDistanceKm: 38.4,
      distanceKm: 29.7,
      shortestEta: "35m",
      highwayEta: "57m",
      etaTime: "On highway - ETA 35m",
      savingsKm: 8.7,
      savingsMin: 22,
      netDriverPay: 1650,
      freightFee: 1650,
      freightFormatted: "₹ 1,650",
      fareBreakdown: {
        baseFare: 600,
        distanceFreight: 700,
        distanceFreightDetail: "35 km @ ₹20/km",
        multiStopAllowance: 350,
        multiStopDetail: "3 Stops",
        total: 1650
      },
      escrowAmount: 1650,
      escrowStatus: "Locked in Smart Escrow",
      deliveryStatus: "In Transit",
      statusBadgeClass: "badge-status-in-transit",
      temperatureC: "Fresh Ambient 24°C",
      humidityPct: "70%",
      driverName: "Karthik Raja",
      driverPhone: "+91 98421 99812",
      vehicleNo: "Tata Ace EV (TN-33-AX-8910)",
      deliveryPin: "8821",
      deliveryWindow: "10:00 AM – 02:00 PM",
      deliveryDate: "Today"
    },
    {
      id: 1,
      orderCode: "FPO-MH-901",
      orderType: "bulk_fpo",
      typeLabel: "Bulk FPO Aggregation Haul",
      title: "Nashik Onion Growers Consortium ➔ Mumbai APMC Terminal",
      cropName: "Red Onion (Nashik Export Grade)",
      image: "assets/images/onion.jpg",
      quantityQt: 500,
      quantityKg: 50000,
      cargoPackaging: "1,000 Ventilated Mesh Bags (50 Tons, Heavy 10-Wheeler)",
      pickupFarmerName: "Nashik Agro Farmer Producer Co. (NAFPO)",
      pickupFarmerId: "FPO-NAFPO-MH",
      pickupFarmerPhone: "+91 98220 77611",
      pickupAddress: "Lasalgaon Mandi Yard, Aggregation Bay 3, Nashik, MH 422306",
      pickupLandmark: "Near Central Weighbridge Ramp #2",
      pickupGate: "Gate 3 (Heavy Commercial Dock)",
      pickupCoords: [20.1472, 74.2255],
      pickupWindow: "06:00 AM – 12:00 PM (Morning Harvest Window)",
      pickupDate: "Today, 15 Sept",
      driverScheduledSlot: "08:30 AM (Confirmed)",
      driverNotes: "10-wheeler vehicle with side-loading tarpaulin",
      availableSlots: ["06:30 AM", "08:00 AM", "09:30 AM", "11:00 AM"],
      slotFlexibilityType: "Flexible FPO Aggregation Window (6 hrs)",
      buyerName: "Mumbai Central APMC Terminal",
      buyerContact: "Sunil Mehta (Head of Procurement)",
      buyerPhone: "+91 98190 33441",
      deliveryAddress: "Vashi APMC Wholesale Market, Sector 19, Navi Mumbai, MH 400703",
      deliveryCoords: [19.0760, 73.0076],
      distanceKm: 195.0,
      etaTime: "4 hrs 15 mins",
      freightFee: 14500,
      freightFormatted: "₹ 14,500",
      escrowAmount: 14500,
      escrowStatus: "Locked in Smart Escrow",
      deliveryStatus: "Available",
      statusBadgeClass: "badge-status-open",
      temperatureC: "Ambient 22.0°C",
      humidityPct: "60%",
      driverName: null,
      driverPhone: null,
      vehicleNo: null,
      deliveryPin: "8821",
      deliveryWindow: "01:00 PM – 05:30 PM",
      deliveryDate: "Today, 15 Sept"
    },
    {
      id: 2,
      orderCode: "FPO-MH-902",
      orderType: "bulk_fpo",
      typeLabel: "Export Port Haul",
      title: "Sangli Spices Producer Co. ➔ JNPT Port Export Terminal",
      cropName: "Salem Turmeric Finger (High Curcumin)",
      image: "assets/images/turmeric.jpg",
      quantityQt: 250,
      quantityKg: 25000,
      cargoPackaging: "500 Sealed Moisture-Proof Sacks (25 Tons, Export Certified)",
      pickupFarmerName: "Sangli Spices Hub & Cooperative",
      pickupFarmerId: "FPO-SANGLI-09",
      pickupFarmerPhone: "+91 94432 88190",
      pickupAddress: "Sangli Spices Park, Industrial Corridor, Sangli, MH 416416",
      pickupLandmark: "Opposite Phyto-Sanitary Inspection Lab",
      pickupGate: "Export Inward Gate #1",
      pickupCoords: [16.8524, 74.5815],
      pickupWindow: "08:00 AM – 02:00 PM (Export Inspection Window)",
      pickupDate: "Today, 15 Sept",
      driverScheduledSlot: null,
      driverNotes: null,
      availableSlots: ["08:30 AM", "10:00 AM", "11:30 AM", "01:00 PM"],
      slotFlexibilityType: "Export Terminal Window (6 hrs)",
      buyerName: "Aroma Spices International (Export Wing)",
      buyerContact: "Capt. R. Deshmukh",
      buyerPhone: "+91 98200 44552",
      deliveryAddress: "JNPT Container Freight Station (CFS), Nhava Sheva, Navi Mumbai, MH 400707",
      deliveryCoords: [18.9499, 72.9515],
      distanceKm: 360.0,
      etaTime: "7 hrs 30 mins",
      freightFee: 26800,
      freightFormatted: "₹ 26,800",
      escrowAmount: 26800,
      escrowStatus: "Locked in Smart Escrow",
      deliveryStatus: "Available",
      statusBadgeClass: "badge-status-open",
      temperatureC: "Ambient Dry 24.5°C",
      humidityPct: "45%",
      driverName: null,
      driverPhone: null,
      vehicleNo: null,
      deliveryPin: "4912",
      deliveryWindow: "04:00 PM – 09:30 PM",
      deliveryDate: "Today, 15 Sept"
    },
    {
      id: 3,
      orderCode: "FPO-MH-903",
      orderType: "bulk_fpo",
      typeLabel: "Cold-Chain Reefer Pool",
      title: "Pimpalgaon Horticulture Federation ➔ Pune Retail Megahub",
      cropName: "Tomato & Green Chilli (Cold-Chain Reefer)",
      image: "assets/images/tomato.jpg",
      quantityQt: 300,
      quantityKg: 30000,
      cargoPackaging: "1,200 Plastic Crates (30 Tons, 5.0°C Active Reefer)",
      pickupFarmerName: "Pimpalgaon Growers Federation",
      pickupFarmerId: "FPO-PIMP-044",
      pickupFarmerPhone: "+91 97654 32109",
      pickupAddress: "Pimpalgaon APMC Cold Hub, NH-60, Pimpalgaon Baswant, MH 422209",
      pickupLandmark: "Cold Storage Ramp #4",
      pickupGate: "Reefer Dock #2",
      pickupCoords: [20.1738, 73.9856],
      pickupWindow: "05:00 AM – 11:00 AM (Cold Reefer Pre-Cooling Window)",
      pickupDate: "Today, 15 Sept",
      driverScheduledSlot: null,
      driverNotes: null,
      availableSlots: ["05:30 AM", "07:00 AM", "08:30 AM", "10:00 AM"],
      slotFlexibilityType: "Active Reefer Cold Window (6 hrs)",
      buyerName: "Reliance Retail Fresh Distribution Center",
      buyerContact: "Anand Kulkarni (DC Manager)",
      buyerPhone: "+91 98234 11223",
      deliveryAddress: "Reliance DC, Chakan MIDC Phase 2, Pune, MH 410501",
      deliveryCoords: [18.7606, 73.8636],
      distanceKm: 175.0,
      etaTime: "3 hrs 45 mins",
      freightFee: 16200,
      freightFormatted: "₹ 16,200",
      escrowAmount: 16200,
      escrowStatus: "Locked in Smart Escrow",
      deliveryStatus: "Available",
      statusBadgeClass: "badge-status-open",
      temperatureC: "5.0°C Active Reefer",
      humidityPct: "85%",
      driverName: null,
      driverPhone: null,
      vehicleNo: null,
      deliveryPin: "7730",
      deliveryWindow: "10:00 AM – 03:00 PM",
      deliveryDate: "Today, 15 Sept"
    },
    {
      id: 4,
      orderCode: "IND-MH-401",
      orderType: "express_local",
      typeLabel: "Express Direct Farm Pickup",
      title: "Farmer Ramesh Patil ➔ AgriFoods Ltd. DC Thane",
      cropName: "Tomato (Shivam Hybrid)",
      image: "assets/images/tomato.jpg",
      quantityQt: 50,
      quantityKg: 5000,
      cargoPackaging: "200 Standard Crates (5,000 kg)",
      pickupFarmerName: "Ramesh Patil",
      pickupFarmerId: "FARM-88210",
      pickupFarmerPhone: "+91 98421 88390",
      pickupAddress: "Survey #42, Dindori Road, Near APMC Yard, Nashik, MH 422004",
      pickupLandmark: "Farm Gate 1 with concrete loading ramp",
      pickupGate: "Gate 1 (North Field)",
      pickupCoords: [20.0110, 73.7900],
      pickupWindow: "06:30 AM – 11:30 AM (Farm Gate Plucking Window)",
      pickupDate: "Today, 15 Sept",
      driverScheduledSlot: "09:15 AM (Confirmed)",
      driverNotes: "Ramp loading with crate spacers",
      availableSlots: ["07:00 AM", "08:15 AM", "09:15 AM", "10:30 AM"],
      slotFlexibilityType: "Direct Farm-Gate Window (5 hrs)",
      buyerName: "AgriFoods Ltd. Central Sourcing",
      buyerContact: "Karthik Sundaram (Procurement Lead)",
      buyerPhone: "+91 98234 11223",
      deliveryAddress: "AgriFoods Distribution Center, Majiwada, Thane West, MH 400601",
      deliveryCoords: [19.2183, 72.9781],
      distanceKm: 142.0,
      etaTime: "2 hrs 50 mins",
      freightFee: 4200,
      freightFormatted: "₹ 4,200",
      escrowAmount: 4200,
      escrowStatus: "Locked in Smart Escrow",
      deliveryStatus: "In Transit",
      statusBadgeClass: "badge-status-in-transit",
      temperatureC: "6.2°C Fresh Cool",
      humidityPct: "88%",
      driverName: "Dinesh Yadav",
      driverPhone: "+91 97230 44819",
      vehicleNo: "MH-15-AQ-9011 (Tata 407 Reefer)",
      deliveryPin: "5519",
      deliveryWindow: "11:30 AM – 02:30 PM",
      deliveryDate: "Today, 15 Sept"
    },
    {
      id: 5,
      orderCode: "IND-MH-402",
      orderType: "express_local",
      typeLabel: "Mandi Aggregated Delivery",
      title: "Lasalgaon Mandi Yard ➔ Global Grains Direct Bhiwandi",
      cropName: "Red Onion (Nashik Quality)",
      image: "assets/images/onion.jpg",
      quantityQt: 30,
      quantityKg: 3000,
      cargoPackaging: "60 Jute Bags (3,000 kg)",
      pickupFarmerName: "Ramesh Patil & Lasalgaon Cluster",
      pickupFarmerId: "FARM-88210",
      pickupFarmerPhone: "+91 98421 88390",
      pickupAddress: "Lasalgaon APMC Mandi Shed #4, Nashik, MH 422306",
      pickupLandmark: "Near Main Auction Gate",
      pickupGate: "Shed #4 Ramp",
      pickupCoords: [20.1472, 74.2255],
      pickupWindow: "09:00 AM – 04:00 PM (All-Day Mandi Shed Window)",
      pickupDate: "Today, 15 Sept",
      driverScheduledSlot: "10:45 AM (Confirmed)",
      driverNotes: "Weighbridge clearance pass requested",
      availableSlots: ["09:30 AM", "11:00 AM", "01:30 PM", "03:00 PM"],
      slotFlexibilityType: "All-Day Mandi Window (7 hrs)",
      buyerName: "Global Grains Direct Logistics Hub",
      buyerContact: "Rajesh Singhal",
      buyerPhone: "+91 98110 55432",
      deliveryAddress: "Bhiwandi Logistics Park, Anjurphata, Bhiwandi, MH 421302",
      deliveryCoords: [19.2967, 73.0631],
      distanceKm: 158.0,
      etaTime: "3 hrs 15 mins",
      freightFee: 3800,
      freightFormatted: "₹ 3,800",
      escrowAmount: 3800,
      escrowStatus: "Locked in Smart Escrow",
      deliveryStatus: "In Transit",
      statusBadgeClass: "badge-status-in-transit",
      temperatureC: "Ambient 23.0°C",
      humidityPct: "58%",
      driverName: "Dinesh Yadav",
      driverPhone: "+91 97230 44819",
      vehicleNo: "MH-15-AQ-9011 (Tata 407 Reefer 5°C)",
      deliveryPin: "6204",
      deliveryWindow: "01:00 PM – 05:00 PM",
      deliveryDate: "Today, 15 Sept"
    },
    {
      id: 6,
      orderCode: "IND-MH-403",
      orderType: "express_local",
      typeLabel: "Perishable Express Direct",
      title: "Pimpalgaon APMC ➔ Spices Exim Hub Mumbai",
      cropName: "Green Chilli (G4 Spicy)",
      image: "assets/images/chilli.jpg",
      quantityQt: 25,
      quantityKg: 2500,
      cargoPackaging: "100 Perforated Crates (2,500 kg)",
      pickupFarmerName: "Ramesh Patil",
      pickupFarmerId: "FARM-88210",
      pickupFarmerPhone: "+91 98421 88390",
      pickupAddress: "Pimpalgaon Mandi Cold Inward Yard, Nashik, MH 422209",
      pickupLandmark: "Cold Dock #2",
      pickupGate: "Gate 2",
      pickupCoords: [20.1738, 73.9856],
      pickupWindow: "07:00 AM – 01:00 PM (Perishable Fast-Track Window)",
      pickupDate: "Today, 15 Sept",
      driverScheduledSlot: "08:00 AM (Confirmed)",
      driverNotes: "Reefer cool box set to 8°C",
      availableSlots: ["07:30 AM", "08:00 AM", "10:00 AM", "12:00 PM"],
      slotFlexibilityType: "Perishable Fast-Track Window (6 hrs)",
      buyerName: "Spices Exim Consortium",
      buyerContact: "Vikram Seth",
      buyerPhone: "+91 97654 32109",
      deliveryAddress: "Crawford Market Wholesale Cold Bay, Mumbai, MH 400001",
      deliveryCoords: [18.9472, 72.8347],
      distanceKm: 178.0,
      etaTime: "3 hrs 40 mins",
      freightFee: 4600,
      freightFormatted: "₹ 4,600",
      escrowAmount: 4600,
      escrowStatus: "Locked in Smart Escrow",
      deliveryStatus: "In Transit",
      statusBadgeClass: "badge-status-in-transit",
      temperatureC: "8.0°C Cool Box",
      humidityPct: "82%",
      driverName: "Dinesh Yadav",
      driverPhone: "+91 97230 44819",
      vehicleNo: "MH-15-AQ-9011 (Tata 407 Reefer 5°C)",
      deliveryPin: "9182",
      deliveryWindow: "12:00 PM – 04:00 PM",
      deliveryDate: "Today, 15 Sept"
    }
  ],
  passbook: [
    {
      txId: "TX-ESC-9081",
      orderCode: "FPO-MH-889",
      crop: "Paddy (1121 Basmati - 100 Qt)",
      buyer: "Fresh Mart Wholesale (Navi Mumbai)",
      amount: "₹ 11,200",
      payoutMethod: "Direct UPI ➔ dinesh.logistics@okaxis",
      status: "Settled",
      date: "14 Sep 2026, 6:45 PM"
    },
    {
      txId: "TX-ESC-8922",
      orderCode: "IND-MH-380",
      crop: "Raw Cotton (80 Qt)",
      buyer: "Malegaon Cotton Textiles",
      amount: "₹ 7,500",
      payoutMethod: "Bank NEFT (HDFC0001234)",
      status: "Settled",
      date: "12 Sep 2026, 4:20 PM"
    },
    {
      txId: "TX-ESC-8710",
      orderCode: "IND-MH-365",
      crop: "Fresh Okra (20 Qt)",
      buyer: "Annapoorna Caterers (Nashik)",
      amount: "₹ 2,800",
      payoutMethod: "Direct UPI ➔ dinesh.logistics@okaxis",
      status: "Settled",
      date: "10 Sep 2026, 11:30 AM"
    }
  ]
};
