const fs = require('fs');
const path = require('path');

const cropsData = [
  { key: "onion", name: "Red Onion (Lasalgaon Garwa)", emoji: "🧅", hub: "Lasalgaon APMC (Nashik)", currentModalQt: 1850, currentMinQt: 1400, currentMaxQt: 2150, farmGateQt: 1800, terminalVashiQt: 2150, arbitragePct: 16.3, trendPct: "+4.8%", trendDir: "up", arrivalsQt: 6850, arrivalsChange: "+12.4% vs last week", sentiment: "Bullish (Export Demand Peak)", sentimentScore: 82, category: "vegetables", recommendation: "High institutional procurement velocity. Lock 35% advance escrow on Lasalgaon Grade A lots before post-monsoon export quota surge." },
  { key: "tomato", name: "Hybrid Tomato (Narayangaon / Junnar)", emoji: "🍅", hub: "Narayangaon APMC (Pune)", currentModalQt: 1200, currentMinQt: 900, currentMaxQt: 1450, farmGateQt: 1200, terminalVashiQt: 1450, arbitragePct: 17.2, trendPct: "-3.2%", trendDir: "down", arrivalsQt: 5400, arrivalsChange: "+28.0% Heavy Inflow", sentiment: "Buyer's Market (Excess Supply)", sentimentScore: 64, category: "vegetables", recommendation: "Peak harvest arrivals from Junnar and Otur clusters. High bargaining power for bulk processing and retail packing. Counter-bid at ₹ 11.50-11.80/kg." },
  { key: "banana", name: "Grand Naine Banana (Jalgaon G9)", emoji: "🍌", hub: "Raver & Jalgaon APMC", currentModalQt: 1400, currentMinQt: 1100, currentMaxQt: 1650, farmGateQt: 1400, terminalVashiQt: 1680, arbitragePct: 16.7, trendPct: "+2.1%", trendDir: "up", arrivalsQt: 4200, arrivalsChange: "+6.5% Consistent", sentiment: "Steady Institutional Off-take", sentimentScore: 76, category: "fruits", recommendation: "Export and supermarket grade bunches available with calibrated ripening reefer fleet. Fast haulage to Mumbai/Pune recommended." },
  { key: "soybean", name: "Yellow Soybean (Latur JS 335)", emoji: "🌱", hub: "Latur APMC Mega Silos", currentModalQt: 4600, currentMinQt: 4100, currentMaxQt: 4950, farmGateQt: 4550, terminalVashiQt: 5200, arbitragePct: 12.5, trendPct: "+1.8%", trendDir: "up", arrivalsQt: 9400, arrivalsChange: "+15.0% Post-Monsoon", sentiment: "Bullish Crusher Demand", sentimentScore: 79, category: "spices", recommendation: "High solvent extraction demand. Procure moisture-certified Grade A lots directly from Latur and Nanded silos with quality lab reports." },
  { key: "orange", name: "Nagpur Orange (Santra GI)", emoji: "🍊", hub: "Katol & Amravati APMC", currentModalQt: 3200, currentMinQt: 2600, currentMaxQt: 3800, farmGateQt: 3100, terminalVashiQt: 3900, arbitragePct: 20.5, trendPct: "+5.4%", trendDir: "up", arrivalsQt: 5800, arrivalsChange: "+8.2% Seasonal Peak", sentiment: "Strong Juice Processor Buying", sentimentScore: 84, category: "fruits", recommendation: "Ambika and Nagpur mandarin harvest at peak Brix sweetness. Ideal for beverage manufacturers and retail chains." },
  { key: "turmeric", name: "Sangli Rajapuri Turmeric", emoji: "🟡", hub: "Sangli Spices APMC", currentModalQt: 14200, currentMinQt: 12500, currentMaxQt: 16000, farmGateQt: 13900, terminalVashiQt: 16800, arbitragePct: 17.3, trendPct: "+8.5%", trendDir: "up", arrivalsQt: 2100, arrivalsChange: "+4.1% Tight Supply", sentiment: "Extremely Bullish (Pharma & Export)", sentimentScore: 91, category: "spices", recommendation: "Curcumin >4.5% premium quality in Sangli and Hingoli. High global export demand; lock long-term supply contracts immediately." },
  { key: "pomegranate", name: "Bhagwa Pomegranate (Solapur GI)", emoji: "🔴", hub: "Solapur APMC Market Yard", currentModalQt: 9500, currentMinQt: 8000, currentMaxQt: 11500, farmGateQt: 9200, terminalVashiQt: 11800, arbitragePct: 22.0, trendPct: "+3.6%", trendDir: "up", arrivalsQt: 3400, arrivalsChange: "+9.8% Export Demand", sentiment: "High Middle-East Export Demand", sentimentScore: 88, category: "fruits", recommendation: "Deep red aril fruit size 250g+ available in Solapur & Sangola clusters. Premium price realized in EU and Gulf markets." },
  { key: "cotton", name: "Vidarbha Raw Cotton (Long Staple)", emoji: "☁️", hub: "Yavatmal & Amravati APMC", currentModalQt: 7100, currentMinQt: 6400, currentMaxQt: 7600, farmGateQt: 7000, terminalVashiQt: 7900, arbitragePct: 11.4, trendPct: "+1.2%", trendDir: "up", arrivalsQt: 7800, arrivalsChange: "+18.2% Harvest Surge", sentiment: "Textile Mill Buying Active", sentimentScore: 75, category: "spices", recommendation: "Staple length 29.5mm+ Shankar-6 equivalent available across Yavatmal spinning ginning hubs." },
  { key: "maize", name: "Yellow Maize (Malegaon Hybrid)", emoji: "🌽", hub: "Malegaon APMC Yard", currentModalQt: 2200, currentMinQt: 1950, currentMaxQt: 2400, farmGateQt: 2150, terminalVashiQt: 2500, arbitragePct: 14.0, trendPct: "+2.5%", trendDir: "up", arrivalsQt: 6200, arrivalsChange: "+11.0% Feed Demand", sentiment: "Poultry Feed & Starch Demand", sentimentScore: 77, category: "grains", recommendation: "High moisture-controlled feed grade maize available across Nashik and Khandesh hubs." },
  { key: "safflower", name: "Safflower Seeds (Kardi High-Oil)", emoji: "🌼", hub: "Solapur APMC Market Yard", currentModalQt: 5600, currentMinQt: 5100, currentMaxQt: 6000, farmGateQt: 5500, terminalVashiQt: 6300, arbitragePct: 12.7, trendPct: "+1.9%", trendDir: "up", arrivalsQt: 1800, arrivalsChange: "+5.2% Oil Mills", sentiment: "Steady Cold-Press Demand", sentimentScore: 74, category: "spices", recommendation: "High linoleic oil content seeds available in Solapur & Dharashiv APMCs." },
  { key: "sesame", name: "White Sesame (Til Export Grade)", emoji: "⚪", hub: "Dhule APMC Yard", currentModalQt: 13500, currentMinQt: 12000, currentMaxQt: 14800, farmGateQt: 13200, terminalVashiQt: 15500, arbitragePct: 14.8, trendPct: "+6.2%", trendDir: "up", arrivalsQt: 1200, arrivalsChange: "+3.5% Premium", sentiment: "Bullish Export Demand", sentimentScore: 89, category: "spices", recommendation: "Natural white 99.5% purity sesame available in Dhule & Jalgaon hubs for confectionery & oil extraction." },
  { key: "chilli", name: "Dry Red Chilli (Nandurbar Teja)", emoji: "🌶️", hub: "Nandurbar Chilli Yard", currentModalQt: 18000, currentMinQt: 16000, currentMaxQt: 20500, farmGateQt: 17600, terminalVashiQt: 21000, arbitragePct: 16.2, trendPct: "+7.1%", trendDir: "up", arrivalsQt: 2400, arrivalsChange: "+7.8% Spice Mills", sentiment: "High Pungency Premium", sentimentScore: 87, category: "spices", recommendation: "High SHU capsaicin Teja and Guntur varieties in Nandurbar market yard." },
  { key: "guava", name: "Sweet Guava (Rahata L-49)", emoji: "🍈", hub: "Rahata APMC Market", currentModalQt: 3200, currentMinQt: 2700, currentMaxQt: 3600, farmGateQt: 3100, terminalVashiQt: 3750, arbitragePct: 17.3, trendPct: "+3.0%", trendDir: "up", arrivalsQt: 2900, arrivalsChange: "+14.0% Fresh Harvest", sentiment: "Retail & Pulp Processing Demand", sentimentScore: 78, category: "fruits", recommendation: "Fresh Sardar L-49 table guava harvested daily in Ahmednagar belt." },
  { key: "wheat", name: "Lokwan Golden Wheat (Sharbati)", emoji: "🌾", hub: "Akola & Washim APMC", currentModalQt: 2800, currentMinQt: 2500, currentMaxQt: 3100, farmGateQt: 2750, terminalVashiQt: 3150, arbitragePct: 12.7, trendPct: "+1.5%", trendDir: "up", arrivalsQt: 8500, arrivalsChange: "+6.0% Roller Mills", sentiment: "Atta Mill Procurement High", sentimentScore: 81, category: "grains", recommendation: "High protein, lustrous Lokwan wheat grains for flour mills and retail brand packing." },
  { key: "rice", name: "Wada Kolam Rice (Palghar GI)", emoji: "🍚", hub: "Palghar & Wada APMC", currentModalQt: 4500, currentMinQt: 4000, currentMaxQt: 5100, farmGateQt: 4400, terminalVashiQt: 5200, arbitragePct: 15.4, trendPct: "+3.8%", trendDir: "up", arrivalsQt: 3100, arrivalsChange: "+4.2% Premium Grain", sentiment: "High Aromatic Demand", sentimentScore: 85, category: "grains", recommendation: "Aromatic non-basmati Wada Kolam paddy available directly from coastal Maharashtra farmers." },
  { key: "jowar", name: "Maldandi Jowar (Solapur Sorghum)", emoji: "🌾", hub: "Solapur & Barshi APMC", currentModalQt: 3400, currentMinQt: 3000, currentMaxQt: 3800, farmGateQt: 3300, terminalVashiQt: 3900, arbitragePct: 15.4, trendPct: "+2.0%", trendDir: "up", arrivalsQt: 4100, arrivalsChange: "+8.5% Health Food", sentiment: "Millet & Superfood Demand", sentimentScore: 83, category: "grains", recommendation: "Maldandi M35-1 white lustrous grain high in fiber, ideal for FMCG superfood brands." },
  { key: "bajra", name: "Pearl Millet (Dhule Hybrid Bajra)", emoji: "🥣", hub: "Dhule & Malegaon APMC", currentModalQt: 2100, currentMinQt: 1850, currentMaxQt: 2350, farmGateQt: 2050, terminalVashiQt: 2450, arbitragePct: 16.3, trendPct: "+1.1%", trendDir: "up", arrivalsQt: 5300, arrivalsChange: "+10.2% Steady", sentiment: "Steady Feed & Food Demand", sentimentScore: 73, category: "grains", recommendation: "Cleaned hybrid bajra grain available across North Maharashtra hubs." },
  { key: "tur", name: "Latur Red Tur (Arhar Dal)", emoji: "🫘", hub: "Latur Pulses APMC", currentModalQt: 9200, currentMinQt: 8400, currentMaxQt: 10100, farmGateQt: 9000, terminalVashiQt: 10600, arbitragePct: 15.1, trendPct: "+4.2%", trendDir: "up", arrivalsQt: 6700, arrivalsChange: "+5.5% Pulse Mills", sentiment: "Bullish Dal Mill Off-take", sentimentScore: 86, category: "pulses", recommendation: "Marathwada bold red tur with high milling recovery rate; lock advance escrow for mills." },
  { key: "chana", name: "Desi Chana (Akola Bengal Gram)", emoji: "🫘", hub: "Akola & Khamgaon APMC", currentModalQt: 5400, currentMinQt: 4900, currentMaxQt: 5900, farmGateQt: 5300, terminalVashiQt: 6100, arbitragePct: 13.1, trendPct: "+2.8%", trendDir: "up", arrivalsQt: 8100, arrivalsChange: "+12.0% Active", sentiment: "Strong Besan Processor Buying", sentimentScore: 80, category: "pulses", recommendation: "High protein Vijay and Digvijay varieties in Vidarbha pulses market yards." },
  { key: "mung", name: "Green Mung Bean (Jalgaon Shiny)", emoji: "🟢", hub: "Jalgaon & Jalna APMC", currentModalQt: 7800, currentMinQt: 7000, currentMaxQt: 8500, farmGateQt: 7650, terminalVashiQt: 8800, arbitragePct: 13.1, trendPct: "+3.5%", trendDir: "up", arrivalsQt: 3800, arrivalsChange: "+7.1% Peak", sentiment: "Sprout & Dal Mill Demand", sentimentScore: 82, category: "pulses", recommendation: "Bold shiny green mung beans harvested across Khandesh and Marathwada." },
  { key: "urad", name: "Black Urad Dal (Nanded Black Gram)", emoji: "🖤", hub: "Nanded & Latur APMC", currentModalQt: 8100, currentMinQt: 7300, currentMaxQt: 8900, farmGateQt: 7950, terminalVashiQt: 9200, arbitragePct: 13.6, trendPct: "+2.9%", trendDir: "up", arrivalsQt: 3500, arrivalsChange: "+6.4% Steady", sentiment: "Papad & FMCG Brand Buying", sentimentScore: 81, category: "pulses", recommendation: "High gluten index black urad suitable for papad manufacturers and dal processors." },
  { key: "groundnut", name: "Kolhapur Bold Groundnut", emoji: "🥜", hub: "Kolhapur & Sangli APMC", currentModalQt: 6800, currentMinQt: 6100, currentMaxQt: 7400, farmGateQt: 6650, terminalVashiQt: 7700, arbitragePct: 13.6, trendPct: "+3.1%", trendDir: "up", arrivalsQt: 4200, arrivalsChange: "+8.9% Oil Mills", sentiment: "High Oil Content Demand", sentimentScore: 83, category: "spices", recommendation: "48%+ oil content bold groundnuts harvested in South Maharashtra river belts." },
  { key: "sunflower", name: "Beed Sunflower Seeds", emoji: "🌻", hub: "Beed & Dharashiv APMC", currentModalQt: 5100, currentMinQt: 4600, currentMaxQt: 5550, farmGateQt: 5000, terminalVashiQt: 5800, arbitragePct: 13.8, trendPct: "+1.7%", trendDir: "up", arrivalsQt: 2100, arrivalsChange: "+4.5% Oil Extraction", sentiment: "Refined Oil Processor Demand", sentimentScore: 76, category: "spices", recommendation: "High oil yield sunflower seed lots available in Marathwada APMC yards." },
  { key: "sugarcane", name: "Kolhapur Co 86032 Sugarcane", emoji: "🎋", hub: "Kolhapur & Karad APMC", currentModalQt: 3400, currentMinQt: 3100, currentMaxQt: 3700, farmGateQt: 3300, terminalVashiQt: 3850, arbitragePct: 14.3, trendPct: "+2.0%", trendDir: "up", arrivalsQt: 12500, arrivalsChange: "+22.0% Crushing Season", sentiment: "Sugar Factory & Jaggery High", sentimentScore: 85, category: "spices", recommendation: "High sucrose recovery sugarcane for jaggery (gur) units and ethanol distilleries." },
  { key: "grapes", name: "Nashik Thompson Seedless Grapes", emoji: "🍇", hub: "Pimpalgaon & Nashik APMC", currentModalQt: 8500, currentMinQt: 7200, currentMaxQt: 10200, farmGateQt: 8200, terminalVashiQt: 10800, arbitragePct: 24.1, trendPct: "+6.8%", trendDir: "up", arrivalsQt: 4600, arrivalsChange: "+16.5% Export Peak", sentiment: "EU & Gulf Export Surge", sentimentScore: 92, category: "fruits", recommendation: "18mm+ berry size MRL compliant grapes with cold chain reefer access." },
  { key: "mosambi", name: "Jalna Sweet Lime (Mosambi)", emoji: "🍋", hub: "Jalna & Aurangabad APMC", currentModalQt: 3800, currentMinQt: 3200, currentMaxQt: 4400, farmGateQt: 3700, terminalVashiQt: 4600, arbitragePct: 19.6, trendPct: "+4.0%", trendDir: "up", arrivalsQt: 5200, arrivalsChange: "+11.2% Juice Demand", sentiment: "Beverage Industry Buying High", sentimentScore: 84, category: "fruits", recommendation: "High juice yield sweet limes from Marathwada citrus orchards." },
  { key: "sitaphal", name: "Beed Balanagar Custard Apple", emoji: "🍈", hub: "Beed & Dharashiv APMC", currentModalQt: 4200, currentMinQt: 3500, currentMaxQt: 4900, farmGateQt: 4050, terminalVashiQt: 5100, arbitragePct: 20.6, trendPct: "+5.1%", trendDir: "up", arrivalsQt: 2800, arrivalsChange: "+18.0% Seasonal", sentiment: "Ice Cream & Pulp Industry Peak", sentimentScore: 87, category: "fruits", recommendation: "Balanagar extra sweet custard apples harvested daily for dairy & dessert processors." },
  { key: "mango", name: "Ratnagiri Alphonso (Hapus GI)", emoji: "🥭", hub: "Ratnagiri & Devgad APMC", currentModalQt: 18500, currentMinQt: 15000, currentMaxQt: 22000, farmGateQt: 18000, terminalVashiQt: 24000, arbitragePct: 25.0, trendPct: "+9.2%", trendDir: "up", arrivalsQt: 1900, arrivalsChange: "+8.0% GI Premium", sentiment: "Global Premium Export Peak", sentimentScore: 96, category: "fruits", recommendation: "100% authentic Konkan GI tagged Alphonso mangoes with QR traceability tags." },
  { key: "potato", name: "Grade A Potato (Manchar Jyoti)", emoji: "🥔", hub: "Manchar APMC (Pune)", currentModalQt: 1600, currentMinQt: 1300, currentMaxQt: 1850, farmGateQt: 1550, terminalVashiQt: 1900, arbitragePct: 18.4, trendPct: "+2.4%", trendDir: "up", arrivalsQt: 6100, arrivalsChange: "+14.2% Cold Storage", sentiment: "Bullish Processing Buying", sentimentScore: 81, category: "vegetables", recommendation: "High dry matter Jyoti potatoes from Khed and Manchar cold stores. Ideal for chip processors and wholesale markets." },
  { key: "brinjal", name: "Purple Brinjal (Baingan / Eggplant)", emoji: "🍆", hub: "Rahuri APMC (Ahmednagar)", currentModalQt: 2200, currentMinQt: 1800, currentMaxQt: 2600, farmGateQt: 2150, terminalVashiQt: 2650, arbitragePct: 18.9, trendPct: "+3.1%", trendDir: "up", arrivalsQt: 3200, arrivalsChange: "+9.0% Harvest", sentiment: "Steady Retail Off-take", sentimentScore: 77, category: "vegetables", recommendation: "Freshly harvested shiny purple long brinjals in Ahmednagar and Pune belts. High demand for urban retail supply chains." },
  { key: "green_chilli", name: "Fresh Green Chilli (G4 High-Pungency)", emoji: "🌶️", hub: "Nandurbar APMC", currentModalQt: 4200, currentMinQt: 3600, currentMaxQt: 4800, farmGateQt: 4100, terminalVashiQt: 4900, arbitragePct: 16.3, trendPct: "+5.0%", trendDir: "up", arrivalsQt: 2900, arrivalsChange: "+11.5% Peak", sentiment: "Strong FMCG & Pickle Demand", sentimentScore: 85, category: "vegetables", recommendation: "G4 variety fresh green chillies with deep green skin and high capsaicin content harvested in Nandurbar and Solapur." }
];

// Multi-district breakdown generator per crop across major MH agricultural districts
const districtHubMap = {
  onion: [
    { district: "Nashik", mandi: "Lasalgaon APMC", modalQt: 1850, minQt: 1400, maxQt: 2150, arrivalsQt: 6850, factor: 1.0 },
    { district: "Ahmednagar", mandi: "Rahuri APMC", modalQt: 1820, minQt: 1380, maxQt: 2100, arrivalsQt: 4200, factor: 0.984 },
    { district: "Solapur", mandi: "Solapur APMC Yard", modalQt: 1790, minQt: 1350, maxQt: 2080, arrivalsQt: 5100, factor: 0.967 },
    { district: "Pune", mandi: "Manchar APMC", modalQt: 1860, minQt: 1420, maxQt: 2160, arrivalsQt: 3600, factor: 1.005 },
    { district: "Dhule", mandi: "Dhule Market Yard", modalQt: 1810, minQt: 1360, maxQt: 2090, arrivalsQt: 2800, factor: 0.978 }
  ],
  tomato: [
    { district: "Pune", mandi: "Narayangaon APMC", modalQt: 1200, minQt: 900, maxQt: 1450, arrivalsQt: 5400, factor: 1.0 },
    { district: "Nashik", mandi: "Pimpalgaon APMC", modalQt: 1180, minQt: 880, maxQt: 1420, arrivalsQt: 3800, factor: 0.983 },
    { district: "Satara", mandi: "Karad APMC", modalQt: 1220, minQt: 920, maxQt: 1480, arrivalsQt: 2400, factor: 1.016 },
    { district: "Ahmednagar", mandi: "Sangamner APMC", modalQt: 1190, minQt: 890, maxQt: 1430, arrivalsQt: 3100, factor: 0.991 }
  ],
  banana: [
    { district: "Jalgaon", mandi: "Raver APMC Yard", modalQt: 1400, minQt: 1100, maxQt: 1650, arrivalsQt: 4200, factor: 1.0 },
    { district: "Nanded", mandi: "Ardhapur APMC", modalQt: 1380, minQt: 1080, maxQt: 1620, arrivalsQt: 2600, factor: 0.985 },
    { district: "Solapur", mandi: "Pandharpur APMC", modalQt: 1420, minQt: 1120, maxQt: 1680, arrivalsQt: 3100, factor: 1.014 },
    { district: "Pune", mandi: "Indapur APMC", modalQt: 1450, minQt: 1150, maxQt: 1700, arrivalsQt: 1900, factor: 1.035 }
  ],
  soybean: [
    { district: "Latur", mandi: "Latur Mega Silos APMC", modalQt: 4600, minQt: 4100, maxQt: 4950, arrivalsQt: 9400, factor: 1.0 },
    { district: "Nanded", mandi: "Nanded APMC Yard", modalQt: 4580, minQt: 4080, maxQt: 4920, arrivalsQt: 5200, factor: 0.995 },
    { district: "Washim", mandi: "Washim APMC", modalQt: 4620, minQt: 4120, maxQt: 4980, arrivalsQt: 4100, factor: 1.004 },
    { district: "Akola", mandi: "Akola APMC", modalQt: 4590, minQt: 4090, maxQt: 4940, arrivalsQt: 4800, factor: 0.997 },
    { district: "Amravati", mandi: "Amravati APMC Yard", modalQt: 4610, minQt: 4110, maxQt: 4960, arrivalsQt: 5600, factor: 1.002 }
  ],
  orange: [
    { district: "Nagpur", mandi: "Kalamna APMC Market", modalQt: 3200, minQt: 2600, maxQt: 3800, arrivalsQt: 5800, factor: 1.0 },
    { district: "Amravati", mandi: "Warud Orange APMC", modalQt: 3150, minQt: 2550, maxQt: 3750, arrivalsQt: 4300, factor: 0.984 },
    { district: "Chhatrapati Sambhajinagar", mandi: "Paithan Citrus Yard", modalQt: 3250, minQt: 2650, maxQt: 3850, arrivalsQt: 2100, factor: 1.015 }
  ],
  turmeric: [
    { district: "Sangli", mandi: "Sangli Spices APMC", modalQt: 14200, minQt: 12500, maxQt: 16000, arrivalsQt: 2100, factor: 1.0 },
    { district: "Hingoli", mandi: "Basmat Turmeric APMC", modalQt: 14100, minQt: 12400, maxQt: 15900, arrivalsQt: 3400, factor: 0.993 },
    { district: "Nanded", mandi: "Nanded Spices Yard", modalQt: 14250, minQt: 12550, maxQt: 16100, arrivalsQt: 1800, factor: 1.003 }
  ],
  pomegranate: [
    { district: "Solapur", mandi: "Sangola APMC Yard", modalQt: 9500, minQt: 8000, maxQt: 11500, arrivalsQt: 3400, factor: 1.0 },
    { district: "Nashik", mandi: "Satana APMC", modalQt: 9400, minQt: 7900, maxQt: 11400, arrivalsQt: 2800, factor: 0.989 },
    { district: "Ahmednagar", mandi: "Rahata APMC", modalQt: 9600, minQt: 8100, maxQt: 11600, arrivalsQt: 2200, factor: 1.01 },
    { district: "Pune", mandi: "Indapur Pomegranate Yard", modalQt: 9550, minQt: 8050, maxQt: 11550, arrivalsQt: 1900, factor: 1.005 }
  ],
  cotton: [
    { district: "Yavatmal", mandi: "Yavatmal APMC Yard", modalQt: 7100, minQt: 6400, maxQt: 7600, arrivalsQt: 7800, factor: 1.0 },
    { district: "Amravati", mandi: "Dhamangaon APMC", modalQt: 7050, minQt: 6350, maxQt: 7550, arrivalsQt: 6100, factor: 0.993 },
    { district: "Wardha", mandi: "Hinganghat Cotton APMC", modalQt: 7120, minQt: 6420, maxQt: 7620, arrivalsQt: 5400, factor: 1.002 },
    { district: "Jalna", mandi: "Partur APMC", modalQt: 7080, minQt: 6380, maxQt: 7580, arrivalsQt: 3900, factor: 0.997 }
  ],
  maize: [
    { district: "Nashik", mandi: "Malegaon APMC Yard", modalQt: 2200, minQt: 1950, maxQt: 2400, arrivalsQt: 6200, factor: 1.0 },
    { district: "Jalgaon", mandi: "Chalisgaon APMC", modalQt: 2180, minQt: 1930, maxQt: 2380, arrivalsQt: 4100, factor: 0.991 },
    { district: "Chhatrapati Sambhajinagar", mandi: "Kannad APMC", modalQt: 2220, minQt: 1970, maxQt: 2420, arrivalsQt: 3500, factor: 1.009 }
  ],
  safflower: [
    { district: "Solapur", mandi: "Barshi APMC Yard", modalQt: 5600, minQt: 5100, maxQt: 6000, arrivalsQt: 1800, factor: 1.0 },
    { district: "Dharashiv", mandi: "Dharashiv APMC", modalQt: 5550, minQt: 5050, maxQt: 5950, arrivalsQt: 1400, factor: 0.991 },
    { district: "Latur", mandi: "Ausa APMC", modalQt: 5620, minQt: 5120, maxQt: 6020, arrivalsQt: 1200, factor: 1.003 }
  ],
  sesame: [
    { district: "Dhule", mandi: "Shirpur APMC", modalQt: 13500, minQt: 12000, maxQt: 14800, arrivalsQt: 1200, factor: 1.0 },
    { district: "Jalgaon", mandi: "Chopda APMC", modalQt: 13450, minQt: 11950, maxQt: 14750, arrivalsQt: 950, factor: 0.996 },
    { district: "Nandurbar", mandi: "Shahada APMC", modalQt: 13550, minQt: 12050, maxQt: 14850, arrivalsQt: 800, factor: 1.003 }
  ],
  chilli: [
    { district: "Nandurbar", mandi: "Nandurbar Chilli Yard", modalQt: 18000, minQt: 16000, maxQt: 20500, arrivalsQt: 2400, factor: 1.0 },
    { district: "Nagpur", mandi: "Bhiwapur Chilli APMC", modalQt: 17900, minQt: 15900, maxQt: 20400, arrivalsQt: 1900, factor: 0.994 },
    { district: "Solapur", mandi: "Karmala APMC", modalQt: 18100, minQt: 16100, maxQt: 20600, arrivalsQt: 1100, factor: 1.005 }
  ],
  guava: [
    { district: "Ahmednagar", mandi: "Rahata APMC Market", modalQt: 3200, minQt: 2700, maxQt: 3600, arrivalsQt: 2900, factor: 1.0 },
    { district: "Pune", mandi: "Purandar Guava APMC", modalQt: 3250, minQt: 2750, maxQt: 3650, arrivalsQt: 2100, factor: 1.015 },
    { district: "Solapur", mandi: "Solapur City APMC", modalQt: 3180, minQt: 2680, maxQt: 3580, arrivalsQt: 1500, factor: 0.993 }
  ],
  wheat: [
    { district: "Akola", mandi: "Akola Grain APMC", modalQt: 2800, minQt: 2500, maxQt: 3100, arrivalsQt: 8500, factor: 1.0 },
    { district: "Washim", mandi: "Karanja APMC", modalQt: 2780, minQt: 2480, maxQt: 3080, arrivalsQt: 5400, factor: 0.993 },
    { district: "Buldhana", mandi: "Khamgaon APMC", modalQt: 2810, minQt: 2510, maxQt: 3110, arrivalsQt: 4800, factor: 1.003 }
  ],
  rice: [
    { district: "Palghar", mandi: "Wada Paddy APMC", modalQt: 4500, minQt: 4000, maxQt: 5100, arrivalsQt: 3100, factor: 1.0 },
    { district: "Thane", mandi: "Shahapur APMC", modalQt: 4480, minQt: 3980, maxQt: 5080, arrivalsQt: 2200, factor: 0.995 },
    { district: "Bhandara", mandi: "Bhandara Rice APMC", modalQt: 4520, minQt: 4020, maxQt: 5120, arrivalsQt: 4600, factor: 1.004 }
  ],
  jowar: [
    { district: "Solapur", mandi: "Barshi APMC Market", modalQt: 3400, minQt: 3000, maxQt: 3800, arrivalsQt: 4100, factor: 1.0 },
    { district: "Dharashiv", mandi: "Omerga APMC", modalQt: 3380, minQt: 2980, maxQt: 3780, arrivalsQt: 2900, factor: 0.994 },
    { district: "Ahmednagar", mandi: "Shevgaon APMC", modalQt: 3420, minQt: 3020, maxQt: 3820, arrivalsQt: 2300, factor: 1.005 }
  ],
  bajra: [
    { district: "Dhule", mandi: "Sakri APMC Yard", modalQt: 2100, minQt: 1850, maxQt: 2350, arrivalsQt: 5300, factor: 1.0 },
    { district: "Nashik", mandi: "Yeola APMC", modalQt: 2080, minQt: 1830, maxQt: 2330, arrivalsQt: 3800, factor: 0.99 },
    { district: "Ahmednagar", mandi: "Kopargaon APMC", modalQt: 2120, minQt: 1870, maxQt: 2370, arrivalsQt: 3100, factor: 1.009 }
  ],
  tur: [
    { district: "Latur", mandi: "Latur Pulses APMC", modalQt: 9200, minQt: 8400, maxQt: 10100, arrivalsQt: 6700, factor: 1.0 },
    { district: "Nanded", mandi: "Mukhed APMC", modalQt: 9150, minQt: 8350, maxQt: 10050, arrivalsQt: 4300, factor: 0.994 },
    { district: "Akola", mandi: "Akola Pulses APMC", modalQt: 9250, minQt: 8450, maxQt: 10150, arrivalsQt: 5100, factor: 1.005 }
  ],
  chana: [
    { district: "Akola", mandi: "Khamgaon APMC", modalQt: 5400, minQt: 4900, maxQt: 5900, arrivalsQt: 8100, factor: 1.0 },
    { district: "Latur", mandi: "Udgir APMC", modalQt: 5380, minQt: 4880, maxQt: 5880, arrivalsQt: 5900, factor: 0.996 },
    { district: "Amravati", mandi: "Chandur APMC", modalQt: 5420, minQt: 4920, maxQt: 5920, arrivalsQt: 4600, factor: 1.003 }
  ],
  mung: [
    { district: "Jalgaon", mandi: "Pachora APMC", modalQt: 7800, minQt: 7000, maxQt: 8500, arrivalsQt: 3800, factor: 1.0 },
    { district: "Jalna", mandi: "Ambad APMC", modalQt: 7750, minQt: 6950, maxQt: 8450, arrivalsQt: 2700, factor: 0.993 },
    { district: "Beed", mandi: "Majalgaon APMC", modalQt: 7820, minQt: 7020, maxQt: 8520, arrivalsQt: 2100, factor: 1.002 }
  ],
  urad: [
    { district: "Nanded", mandi: "Degloor APMC", modalQt: 8100, minQt: 7300, maxQt: 8900, arrivalsQt: 3500, factor: 1.0 },
    { district: "Latur", mandi: "Latur Grain Yard", modalQt: 8050, minQt: 7250, maxQt: 8850, arrivalsQt: 3100, factor: 0.993 },
    { district: "Parbhani", mandi: "Parbhani APMC", modalQt: 8120, minQt: 7320, maxQt: 8920, arrivalsQt: 2400, factor: 1.002 }
  ],
  groundnut: [
    { district: "Kolhapur", mandi: "Vadgaon APMC", modalQt: 6800, minQt: 6100, maxQt: 7400, arrivalsQt: 4200, factor: 1.0 },
    { district: "Sangli", mandi: "Tasgaon APMC", modalQt: 6780, minQt: 6080, maxQt: 7380, arrivalsQt: 3400, factor: 0.997 },
    { district: "Satara", mandi: "Phaltan APMC", modalQt: 6820, minQt: 6120, maxQt: 7420, arrivalsQt: 2800, factor: 1.003 }
  ],
  sunflower: [
    { district: "Beed", mandi: "Kaij APMC Yard", modalQt: 5100, minQt: 4600, maxQt: 5550, arrivalsQt: 2100, factor: 1.0 },
    { district: "Dharashiv", mandi: "Kalamb APMC", modalQt: 5080, minQt: 4580, maxQt: 5530, arrivalsQt: 1700, factor: 0.996 },
    { district: "Latur", mandi: "Nilanga APMC", modalQt: 5120, minQt: 4620, maxQt: 5570, arrivalsQt: 1500, factor: 1.003 }
  ],
  sugarcane: [
    { district: "Kolhapur", mandi: "Shirol APMC", modalQt: 3400, minQt: 3100, maxQt: 3700, arrivalsQt: 12500, factor: 1.0 },
    { district: "Sangli", mandi: "Walwa APMC", modalQt: 3380, minQt: 3080, maxQt: 3680, arrivalsQt: 9800, factor: 0.994 },
    { district: "Satara", mandi: "Karad Sugarcane Hub", modalQt: 3420, minQt: 3120, maxQt: 3720, arrivalsQt: 8400, factor: 1.005 }
  ],
  grapes: [
    { district: "Nashik", mandi: "Pimpalgaon Baswant APMC", modalQt: 8500, minQt: 7200, maxQt: 10200, arrivalsQt: 4600, factor: 1.0 },
    { district: "Sangli", mandi: "Tasgaon Grape Yard", modalQt: 8450, minQt: 7150, maxQt: 10150, arrivalsQt: 3900, factor: 0.994 },
    { district: "Solapur", mandi: "Pandharpur APMC", modalQt: 8550, minQt: 7250, maxQt: 10250, arrivalsQt: 2700, factor: 1.005 }
  ],
  mosambi: [
    { district: "Jalna", mandi: "Ghansawangi APMC", modalQt: 3800, minQt: 3200, maxQt: 4400, arrivalsQt: 5200, factor: 1.0 },
    { district: "Chhatrapati Sambhajinagar", mandi: "Paithan Citrus APMC", modalQt: 3750, minQt: 3150, maxQt: 4350, arrivalsQt: 3600, factor: 0.986 },
    { district: "Nanded", mandi: "Bhokar APMC", modalQt: 3820, minQt: 3220, maxQt: 4420, arrivalsQt: 2800, factor: 1.005 }
  ],
  sitaphal: [
    { district: "Beed", mandi: "Dharur APMC", modalQt: 4200, minQt: 3500, maxQt: 4900, arrivalsQt: 2800, factor: 1.0 },
    { district: "Dharashiv", mandi: "Tuljapur APMC", modalQt: 4150, minQt: 3450, maxQt: 4850, arrivalsQt: 2200, factor: 0.988 },
    { district: "Solapur", mandi: "Barshi Sitaphal Yard", modalQt: 4250, minQt: 3550, maxQt: 4950, arrivalsQt: 1900, factor: 1.011 }
  ],
  mango: [
    { district: "Ratnagiri", mandi: "Ratnagiri Mango APMC", modalQt: 18500, minQt: 15000, maxQt: 22000, arrivalsQt: 1900, factor: 1.0 },
    { district: "Sindhudurg", mandi: "Devgad Hapus Yard", modalQt: 18800, minQt: 15300, maxQt: 22300, arrivalsQt: 2400, factor: 1.016 },
    { district: "Raigad", mandi: "Alibaug APMC", modalQt: 18200, minQt: 14700, maxQt: 21700, arrivalsQt: 1100, factor: 0.983 }
  ],
  potato: [
    { district: "Pune", mandi: "Manchar Potato APMC", modalQt: 1600, minQt: 1300, maxQt: 1850, arrivalsQt: 6100, factor: 1.0 },
    { district: "Satara", mandi: "Wai APMC", modalQt: 1580, minQt: 1280, maxQt: 1830, arrivalsQt: 3900, factor: 0.987 },
    { district: "Nashik", mandi: "Sinnar APMC", modalQt: 1620, minQt: 1320, maxQt: 1870, arrivalsQt: 4200, factor: 1.012 },
    { district: "Ahmednagar", mandi: "Parner APMC", modalQt: 1590, minQt: 1290, maxQt: 1840, arrivalsQt: 2800, factor: 0.993 }
  ],
  brinjal: [
    { district: "Ahmednagar", mandi: "Rahuri APMC Market", modalQt: 2200, minQt: 1800, maxQt: 2600, arrivalsQt: 3200, factor: 1.0 },
    { district: "Pune", mandi: "Khed APMC Yard", modalQt: 2230, minQt: 1830, maxQt: 2630, arrivalsQt: 2700, factor: 1.013 },
    { district: "Solapur", mandi: "Mohol APMC", modalQt: 2180, minQt: 1780, maxQt: 2580, arrivalsQt: 1900, factor: 0.991 },
    { district: "Nashik", mandi: "Pimpalgaon APMC", modalQt: 2210, minQt: 1810, maxQt: 2610, arrivalsQt: 2400, factor: 1.004 }
  ],
  green_chilli: [
    { district: "Nandurbar", mandi: "Nandurbar APMC Yard", modalQt: 4200, minQt: 3600, maxQt: 4800, arrivalsQt: 2900, factor: 1.0 },
    { district: "Nagpur", mandi: "Kalamna APMC", modalQt: 4180, minQt: 3580, maxQt: 4780, arrivalsQt: 2300, factor: 0.995 },
    { district: "Solapur", mandi: "Solapur Spices Yard", modalQt: 4240, minQt: 3640, maxQt: 4840, arrivalsQt: 1800, factor: 1.009 },
    { district: "Pune", mandi: "Manchar Green Yard", modalQt: 4220, minQt: 3620, maxQt: 4820, arrivalsQt: 1500, factor: 1.004 }
  ]
};

// Master list of all major 30 agricultural districts in Maharashtra to ensure 100% district coverage for EVERY crop
const ALL_MAHARASHTRA_DISTRICTS = [
  { district: "Nashik", mandiSuffix: "APMC Yard", factor: 1.00, arrivals: 6850 },
  { district: "Pune", mandiSuffix: "Gultekdi Market Yard", factor: 1.025, arrivals: 5400 },
  { district: "Jalgaon", mandiSuffix: "Bhusawal APMC Yard", factor: 0.982, arrivals: 4200 },
  { district: "Latur", mandiSuffix: "Latur Pulses & Grain APMC", factor: 0.995, arrivals: 6400 },
  { district: "Nagpur", mandiSuffix: "Kalamna Market Yard", factor: 1.018, arrivals: 4900 },
  { district: "Sangli", mandiSuffix: "Sangli Market Yard", factor: 0.992, arrivals: 3600 },
  { district: "Solapur", mandiSuffix: "Solapur Siddheshwar APMC", factor: 1.006, arrivals: 4500 },
  { district: "Ahmednagar", mandiSuffix: "Rahuri / Rahata APMC", factor: 0.987, arrivals: 5100 },
  { district: "Amravati", mandiSuffix: "Amravati Grain APMC", factor: 0.994, arrivals: 3800 },
  { district: "Akola", mandiSuffix: "Akola Oilseeds APMC", factor: 0.991, arrivals: 4100 },
  { district: "Nanded", mandiSuffix: "Degloor APMC Yard", factor: 0.997, arrivals: 3200 },
  { district: "Satara", mandiSuffix: "Karad APMC Yard", factor: 1.012, arrivals: 2800 },
  { district: "Kolhapur", mandiSuffix: "Shahu Market Yard", factor: 1.022, arrivals: 3300 },
  { district: "Dhule", mandiSuffix: "Dhule Grain APMC", factor: 0.981, arrivals: 3500 },
  { district: "Nandurbar", mandiSuffix: "Nandurbar APMC Market", factor: 0.978, arrivals: 2900 },
  { district: "Beed", mandiSuffix: "Majalgaon APMC Yard", factor: 0.986, arrivals: 2400 },
  { district: "Washim", mandiSuffix: "Karanja Lad APMC", factor: 0.993, arrivals: 2300 },
  { district: "Palghar", mandiSuffix: "Wada Paddy APMC", factor: 1.015, arrivals: 2100 },
  { district: "Dharashiv", mandiSuffix: "Omerga APMC Yard", factor: 0.989, arrivals: 2200 },
  { district: "Chhatrapati Sambhajinagar", mandiSuffix: "Paithan APMC Yard", factor: 1.006, arrivals: 3400 },
  { district: "Hingoli", mandiSuffix: "Hingoli APMC Market", factor: 0.990, arrivals: 1900 },
  { district: "Wardha", mandiSuffix: "Hinganghat APMC", factor: 0.996, arrivals: 2400 },
  { district: "Ratnagiri", mandiSuffix: "Ratnagiri APMC Yard", factor: 1.045, arrivals: 1800 },
  { district: "Sindhudurg", mandiSuffix: "Devgad / Kudal APMC", factor: 1.048, arrivals: 1600 },
  { district: "Raigad", mandiSuffix: "Panvel APMC Yard", factor: 1.035, arrivals: 2700 },
  { district: "Yavatmal", mandiSuffix: "Yavatmal APMC Yard", factor: 0.987, arrivals: 3300 },
  { district: "Buldhana", mandiSuffix: "Khamgaon APMC Yard", factor: 0.993, arrivals: 3100 },
  { district: "Bhandara", mandiSuffix: "Bhandara Rice APMC", factor: 0.984, arrivals: 2600 },
  { district: "Jalna", mandiSuffix: "Jalna APMC Market Yard", factor: 0.996, arrivals: 3200 },
  { district: "Parbhani", mandiSuffix: "Parbhani APMC Yard", factor: 0.991, arrivals: 2500 }
];

// Ensure EVERY single crop has price benchmarks across ALL 30 districts of Maharashtra
cropsData.forEach(c => {
  const existingDistricts = new Set();
  if (districtHubMap[c.key]) {
    districtHubMap[c.key].forEach(h => existingDistricts.add(h.district));
  } else {
    districtHubMap[c.key] = [];
  }

  ALL_MAHARASHTRA_DISTRICTS.forEach(d => {
    if (!existingDistricts.has(d.district)) {
      const modal = Math.round(c.currentModalQt * d.factor);
      const min = Math.round(c.currentMinQt * d.factor);
      const max = Math.round(c.currentMaxQt * d.factor);
      const cropSimpleName = c.name.split('(')[0].trim();
      districtHubMap[c.key].push({
        district: d.district,
        mandi: `${d.district} ${cropSimpleName} APMC`,
        modalQt: modal,
        minQt: min,
        maxQt: max,
        arrivalsQt: d.arrivals,
        factor: d.factor
      });
    }
  });
});

function generateHistory(modal, min, max) {
  const base = modal;
  return {
    "7D": {
      labels: ["08 Sep", "09 Sep", "10 Sep", "11 Sep", "12 Sep", "13 Sep", "14 Sep (Today)", "16 Sep (AI)", "18 Sep (AI)", "20 Sep (AI)"],
      historical: [Math.round(base * 0.93), Math.round(base * 0.95), Math.round(base * 0.96), Math.round(base * 0.98), Math.round(base * 0.99), Math.round(base * 0.995), base, null, null, null],
      forecast: [null, null, null, null, null, null, base, Math.round(base * 1.02), Math.round(base * 1.05), Math.round(base * 1.07)],
      mandiMin: [Math.round(min * 0.95), Math.round(min * 0.96), Math.round(min * 0.97), Math.round(min * 0.98), Math.round(min * 0.99), min, min, null, null, null],
      mandiMax: [Math.round(max * 0.93), Math.round(max * 0.95), Math.round(max * 0.97), Math.round(max * 0.98), Math.round(max * 0.99), max, max, null, null, null]
    },
    "1M": {
      labels: ["15 Aug", "22 Aug", "29 Aug", "05 Sep", "12 Sep", "14 Sep (Today)", "21 Sep (AI)", "28 Sep (AI)"],
      historical: [Math.round(base * 0.85), Math.round(base * 0.88), Math.round(base * 0.91), Math.round(base * 0.95), Math.round(base * 0.98), base, null, null],
      forecast: [null, null, null, null, null, base, Math.round(base * 1.04), Math.round(base * 1.08)],
      mandiMin: [Math.round(min * 0.85), Math.round(min * 0.88), Math.round(min * 0.92), Math.round(min * 0.96), min, min, null, null],
      mandiMax: [Math.round(max * 0.85), Math.round(max * 0.88), Math.round(max * 0.92), Math.round(max * 0.96), max, max, null, null]
    },
    "3M": {
      labels: ["Jun 26", "Jul 26", "Aug 26", "Sep 26 (Now)", "Oct 26 (AI)", "Nov 26 (AI)"],
      historical: [Math.round(base * 0.80), Math.round(base * 0.86), Math.round(base * 0.92), base, null, null],
      forecast: [null, null, null, base, Math.round(base * 1.06), Math.round(base * 1.12)],
      mandiMin: [Math.round(min * 0.80), Math.round(min * 0.86), Math.round(min * 0.92), min, null, null],
      mandiMax: [Math.round(max * 0.80), Math.round(max * 0.86), Math.round(max * 0.92), max, null, null]
    },
    "1Y": {
      labels: ["Oct 25", "Dec 25", "Feb 26", "Apr 26", "Jun 26", "Aug 26", "Sep 26 (Now)"],
      historical: [Math.round(base * 1.05), Math.round(base * 1.20), Math.round(base * 0.85), Math.round(base * 0.75), Math.round(base * 0.80), Math.round(base * 0.90), base],
      forecast: [null, null, null, null, null, null, base],
      mandiMin: [Math.round(min * 1.05), Math.round(min * 1.20), Math.round(min * 0.85), Math.round(min * 0.75), Math.round(min * 0.80), Math.round(min * 0.90), min],
      mandiMax: [Math.round(max * 1.05), Math.round(max * 1.20), Math.round(max * 0.85), Math.round(max * 0.75), Math.round(max * 0.80), Math.round(max * 0.90), max]
    }
  };
}

const commObjString = cropsData.map(c => `    ${c.key}: {
      key: "${c.key}",
      name: "${c.name}",
      emoji: "${c.emoji}",
      hub: "${c.hub}",
      currentModalQt: ${c.currentModalQt},
      currentMinQt: ${c.currentMinQt},
      currentMaxQt: ${c.currentMaxQt},
      farmGateQt: ${c.farmGateQt},
      terminalVashiQt: ${c.terminalVashiQt},
      arbitragePct: ${c.arbitragePct},
      trendPct: "${c.trendPct}",
      trendDir: "${c.trendDir}",
      arrivalsQt: ${c.arrivalsQt},
      arrivalsChange: "${c.arrivalsChange}",
      sentiment: "${c.sentiment}",
      sentimentScore: ${c.sentimentScore},
      recommendation: "${c.recommendation.replace(/"/g, '\\"')}",
      districtHubs: ${JSON.stringify(districtHubMap[c.key] || [], null, 8)},
      history: ${JSON.stringify(generateHistory(c.currentModalQt, c.currentMinQt, c.currentMaxQt), null, 8)}
    }`).join(',\n');

const cropCatsMapString = cropsData.map(c => `    ${c.key}: "${c.category}"`).join(',\n');

const jsLines = [
  "/**",
  " * AgriNex Buyer Module - Market Insights & Institutional Intelligence Engine",
  " * Comprehensive APMC Mandi Price Analytics, Predictive Forecasting & Arbitrage Tracking (Maharashtra)",
  " */",
  "",
  "(function () {",
  "  'use strict';",
  "",
  "  // Comprehensive Maharashtra Commodity Analytics & Trend Matrix (All 28 Crops)",
  "  const COMMODITY_INSIGHTS = {",
  commObjString,
  "  };",
  "",
  "  // Category Lookup Mapping",
  "  const CROP_CATEGORIES = {",
  cropCatsMapString,
  "  };",
  "",
  "  // Comprehensive Multi-District APMC Mandis Real-Time Benchmark Table Data",
  "  const MAHARASHTRA_MANDIS_TABLE = [];",
  "  Object.values(COMMODITY_INSIGHTS).forEach(c => {",
  "    const hubs = (c.districtHubs && c.districtHubs.length > 0) ? c.districtHubs : [{",
  "      district: c.hub.includes('(') ? c.hub.split('(')[1].replace(')', '').trim() : 'Nashik',",
  "      mandi: c.hub.split('(')[0].trim(),",
  "      modalQt: c.currentModalQt,",
  "      minQt: c.currentMinQt,",
  "      maxQt: c.currentMaxQt,",
  "      arrivalsQt: c.arrivalsQt",
  "    }];",
  "",
  "    hubs.forEach(h => {",
  "      MAHARASHTRA_MANDIS_TABLE.push({",
  "        crop: c.name.split('(')[0].trim(),",
  "        cropKey: c.key,",
  "        emoji: c.emoji,",
  "        mandi: h.mandi,",
  "        district: h.district,",
  "        arrivalsQt: h.arrivalsQt,",
  "        arrivalsKg: h.arrivalsQt * 100,",
  "        minPriceQt: h.minQt,",
  "        modalPriceQt: h.modalQt,",
  "        maxPriceQt: h.maxQt,",
  "        farmGateQt: c.farmGateQt,",
  "        savingsQt: c.terminalVashiQt - c.farmGateQt,",
  "        savingsPct: c.arbitragePct,",
  "        trend: c.trendDir,",
  "        trendText: c.trendPct",
  "      });",
  "    });",
  "  });",
  "",
  "  // State",
  "  let activeCommodity = 'onion';",
  "  let activeTimeframe = '7D';",
  "  let activePriceUnit = 'kg'; // default 'kg'",
  "  let activeCategory = 'all';",
  "  let priceChartInstance = null;",
  "  let tableSearchQuery = '';",
  "  let tableDistrictFilter = 'all';",
  "  let tableVisibleCount = 5;",
  "  let districtMatrixSearchQuery = '';",
  "",
  "  // Initialize View",
  "  function initBuyerMarketInsights() {",
  "    renderProduceSelectorChips();",
  "    renderInsightChart();",
  "    renderInsightSummaryCards();",
  "    renderSupplyInflowHeatmap();",
  "    renderAiProcurementAdvisories();",
  "    renderMaharashtraMandisTable();",
  "    updateLiveTimestamp();",
  "  }",
  "",
  "  // Category Filtering Handler",
  "  function selectInsightCategory(catKey) {",
  "    activeCategory = catKey;",
  "    document.querySelectorAll('.insight-cat-tab').forEach(tab => {",
  "      const c = tab.getAttribute('data-cat');",
  "      if (c === catKey) {",
  "        tab.classList.add('active');",
  "        tab.style.background = '#0c5a36';",
  "        tab.style.color = '#ffffff';",
  "        tab.style.borderColor = '#0c5a36';",
  "      } else {",
  "        tab.classList.remove('active');",
  "        tab.style.background = '#f8fafc';",
  "        tab.style.color = '#475569';",
  "        tab.style.borderColor = '#cbd5e1';",
  "      }",
  "    });",
  "",
  "    let list = Object.values(COMMODITY_INSIGHTS);",
  "    if (activeCategory !== 'all') {",
  "      list = list.filter(c => (CROP_CATEGORIES[c.key] || 'vegetables') === activeCategory);",
  "    }",
  "",
  "    if (list.length > 0 && !list.some(c => c.key === activeCommodity)) {",
  "      selectInsightCommodity(list[0].key);",
  "    } else {",
  "      renderProduceSelectorChips();",
  "    }",
  "  }",
  "",
  "  // Render Commodity Selector Chips",
  "  function renderProduceSelectorChips() {",
  "    const container = document.getElementById('insight-produce-chips');",
  "    if (!container) return;",
  "",
  "    let list = Object.values(COMMODITY_INSIGHTS);",
  "    if (activeCategory !== 'all') {",
  "      list = list.filter(c => (CROP_CATEGORIES[c.key] || 'vegetables') === activeCategory);",
  "    }",
  "",
  "    container.innerHTML = list.map(c => `",
  "      <div class=\"produce-chip \${c.key === activeCommodity ? 'active' : ''}\" onclick=\"selectInsightCommodity('\${c.key}')\">",
  "        <span style=\"font-size: 1.4rem; line-height: 1;\">\${c.emoji}</span>",
  "        <div>",
  "          <strong style=\"font-size: 0.85rem; color: #0f172a; display: block; white-space: nowrap;\">\${c.name.split('(')[0].trim()}</strong>",
  "          <span style=\"font-size: 0.72rem; color: #64748b;\">\${c.hub.split('(')[0].trim()}</span>",
  "        </div>",
  "        <span class=\"badge \${c.trendDir === 'up' ? 'badge-grade-green' : 'badge-grade-blue'}\" style=\"font-size: 0.7rem; font-weight: 800; margin-left: 4px;\">",
  "          \${c.trendPct}",
  "        </span>",
  "      </div>",
  "    `).join('');",
  "  }",
  "",
  "  function selectInsightCommodity(key) {",
  "    if (!COMMODITY_INSIGHTS[key]) return;",
  "    activeCommodity = key;",
  "    renderProduceSelectorChips();",
  "    renderInsightChart();",
  "    renderInsightSummaryCards();",
  "    renderAiProcurementAdvisories();",
  "  }",
  "",
  "  function setInsightTimeframe(tf) {",
  "    activeTimeframe = tf;",
  "    document.querySelectorAll('.insight-tf-btn').forEach(btn => {",
  "      if (btn.getAttribute('data-tf') === tf) {",
  "        btn.classList.add('active');",
  "        btn.style.background = '#0c5a36';",
  "        btn.style.color = '#ffffff';",
  "      } else {",
  "        btn.classList.remove('active');",
  "        btn.style.background = 'transparent';",
  "        btn.style.color = '#475569';",
  "      }",
  "    });",
  "    renderInsightChart();",
  "  }",
  "",
  "  function setInsightPriceUnit(unit) {",
  "    activePriceUnit = unit;",
  "    const btnQt = document.getElementById('insight-unit-qt');",
  "    const btnKg = document.getElementById('insight-unit-kg');",
  "",
  "    if (unit === 'qt') {",
  "      if (btnQt) { btnQt.classList.add('active'); btnQt.style.background = '#0c5a36'; btnQt.style.color = '#fff'; }",
  "      if (btnKg) { btnKg.classList.remove('active'); btnKg.style.background = 'transparent'; btnKg.style.color = '#475569'; }",
  "    } else {",
  "      if (btnKg) { btnKg.classList.add('active'); btnKg.style.background = '#0c5a36'; btnKg.style.color = '#fff'; }",
  "      if (btnQt) { btnQt.classList.remove('active'); btnQt.style.background = 'transparent'; btnQt.style.color = '#475569'; }",
  "    }",
  "",
  "    renderInsightChart();",
  "    renderInsightSummaryCards();",
  "    renderMaharashtraMandisTable();",
  "  }",
  "",
  "  // Render High-DPI Chart.js Interactive Graph",
  "  function renderInsightChart() {",
  "    const canvas = document.getElementById('buyer-insight-chart');",
  "    if (!canvas) return;",
  "",
  "    if (typeof Chart === 'undefined') {",
  "      console.warn('Chart.js not loaded yet. Waiting...');",
  "      setTimeout(renderInsightChart, 200);",
  "      return;",
  "    }",
  "",
  "    const commodity = COMMODITY_INSIGHTS[activeCommodity];",
  "    if (!commodity || !commodity.history || !commodity.history[activeTimeframe]) return;",
  "",
  "    const dataObj = commodity.history[activeTimeframe];",
  "    const multiplier = activePriceUnit === 'kg' ? 0.01 : 1;",
  "    const unitLabel = activePriceUnit === 'kg' ? '₹ /kg' : '₹ /Qt';",
  "",
  "    const histData = dataObj.historical.map(v => v !== null ? (v * multiplier) : null);",
  "    const foreData = dataObj.forecast.map(v => v !== null ? (v * multiplier) : null);",
  "    const minData = (dataObj.mandiMin || []).map(v => v !== null ? (v * multiplier) : null);",
  "    const maxData = (dataObj.mandiMax || []).map(v => v !== null ? (v * multiplier) : null);",
  "",
  "    if (priceChartInstance) {",
  "      priceChartInstance.destroy();",
  "    }",
  "",
  "    const ctx = canvas.getContext('2d');",
  "    const gradientFill = ctx.createLinearGradient(0, 0, 0, 300);",
  "    gradientFill.addColorStop(0, 'rgba(12, 90, 54, 0.22)');",
  "    gradientFill.addColorStop(1, 'rgba(12, 90, 54, 0.00)');",
  "",
  "    priceChartInstance = new Chart(ctx, {",
  "      type: 'line',",
  "      data: {",
  "        labels: dataObj.labels,",
  "        datasets: [",
  "          {",
  "            label: `Mandi Modal Price (\${unitLabel})`,",
  "            data: histData,",
  "            borderColor: '#0c5a36',",
  "            backgroundColor: gradientFill,",
  "            borderWidth: 3,",
  "            fill: true,",
  "            tension: 0.35,",
  "            pointRadius: 4,",
  "            pointBackgroundColor: '#0c5a36',",
  "            pointHoverRadius: 6",
  "          },",
  "          {",
  "            label: `AI Forward Forecast (\${unitLabel})`,",
  "            data: foreData,",
  "            borderColor: '#2563eb',",
  "            backgroundColor: 'transparent',",
  "            borderWidth: 2.5,",
  "            borderDash: [6, 6],",
  "            fill: false,",
  "            tension: 0.35,",
  "            pointRadius: 4,",
  "            pointBackgroundColor: '#2563eb',",
  "            pointHoverRadius: 6",
  "          },",
  "          {",
  "            label: `Mandi Ceiling / Max (\${unitLabel})`,",
  "            data: maxData,",
  "            borderColor: 'rgba(239, 68, 68, 0.4)',",
  "            borderWidth: 1.5,",
  "            borderDash: [3, 3],",
  "            fill: false,",
  "            tension: 0.3,",
  "            pointRadius: 0",
  "          },",
  "          {",
  "            label: `Mandi Floor / Min (\${unitLabel})`,",
  "            data: minData,",
  "            borderColor: 'rgba(16, 185, 129, 0.4)',",
  "            borderWidth: 1.5,",
  "            borderDash: [3, 3],",
  "            fill: false,",
  "            tension: 0.3,",
  "            pointRadius: 0",
  "          }",
  "        ]",
  "      },",
  "      options: {",
  "        responsive: true,",
  "        maintainAspectRatio: false,",
  "        interaction: {",
  "          mode: 'index',",
  "          intersect: false",
  "        },",
  "        plugins: {",
  "          legend: {",
  "            position: 'top',",
  "            labels: {",
  "              usePointStyle: true,",
  "              boxWidth: 8,",
  "              font: {",
  "                family: \"'Plus Jakarta Sans', sans-serif\",",
  "                size: 12,",
  "                weight: '600'",
  "              },",
  "              color: '#334155'",
  "            }",
  "          },",
  "          tooltip: {",
  "            backgroundColor: '#0f172a',",
  "            titleFont: { family: \"'Plus Jakarta Sans'\", size: 13, weight: '700' },",
  "            bodyFont: { family: \"'Plus Jakarta Sans'\", size: 12 },",
  "            padding: 12,",
  "            cornerRadius: 8,",
  "            callbacks: {",
  "              label: function (ctx) {",
  "                if (ctx.raw === null || ctx.raw === undefined) return null;",
  "                const formatted = activePriceUnit === 'kg' ? `₹ \${parseFloat(ctx.raw).toFixed(2)} /kg` : `₹ \${Math.round(ctx.raw).toLocaleString('en-IN')} /Qt`;",
  "                return `\${ctx.dataset.label.split('(')[0]}: \${formatted}`;",
  "              }",
  "            }",
  "          }",
  "        },",
  "        scales: {",
  "          x: {",
  "            grid: { color: '#f1f5f9' },",
  "            ticks: {",
  "              font: { family: \"'Plus Jakarta Sans'\", size: 11, weight: '600' },",
  "              color: '#64748b'",
  "            }",
  "          },",
  "          y: {",
  "            grid: { color: '#f1f5f9' },",
  "            ticks: {",
  "              font: { family: \"'Plus Jakarta Sans'\", size: 11, weight: '600' },",
  "              color: '#64748b',",
  "              callback: function (val) {",
  "                return activePriceUnit === 'kg' ? `₹\${val.toFixed(1)}` : `₹\${val}`;",
  "              }",
  "            }",
  "          }",
  "        }",
  "      }",
  "    });",
  "",
  "    // Update Chart Top Header Info",
  "    const titleEl = document.getElementById('insight-chart-title');",
  "    const subEl = document.getElementById('insight-chart-sub');",
  "    if (titleEl) titleEl.textContent = `\${commodity.emoji} \${commodity.name} • Mandi Rate Trends & AI Projection`;",
  "    if (subEl) subEl.textContent = `Primary Hub: \${commodity.hub} • 24h Modal: \${formatInsightPrice(commodity.currentModalQt)}`;",
  "  }",
  "",
  "  // Render Top KPI & Summary Cards",
  "  function renderInsightSummaryCards() {",
  "    const commodity = COMMODITY_INSIGHTS[activeCommodity];",
  "    if (!commodity) return;",
  "",
  "    const modalEl = document.getElementById('kpi-insight-modal');",
  "    const spreadEl = document.getElementById('kpi-insight-spread');",
  "    const arrivalsEl = document.getElementById('kpi-insight-arrivals');",
  "    const sentimentEl = document.getElementById('kpi-insight-sentiment');",
  "",
  "    if (modalEl) modalEl.innerHTML = `\${formatInsightPrice(commodity.currentModalQt)} <span style=\"font-size:0.75rem; color:\${commodity.trendDir === 'up' ? '#166534' : '#991b1b'}; font-weight:700;\">(\${commodity.trendPct})</span>`;",
  "    if (spreadEl) spreadEl.innerHTML = `+\${commodity.arbitragePct}% <span style=\"font-size:0.74rem; color:#166534; font-weight:600;\">(Save ₹ \${((commodity.terminalVashiQt - commodity.farmGateQt) / 100).toFixed(2)} /kg)</span>`;",
  "    if (arrivalsEl) arrivalsEl.innerHTML = `\${commodity.arrivalsQt.toLocaleString('en-IN')} Qt <span style=\"font-size:0.74rem; color:#64748b;\">(\${commodity.arrivalsChange})</span>`;",
  "    if (sentimentEl) sentimentEl.innerHTML = `\${commodity.sentiment} <span style=\"font-size:0.74rem; color:#0c5a36; font-weight:700;\">(\${commodity.sentimentScore}/100)</span>`;",
  "  }",
  "",
  "  // Render Left Column: Supply Inflow & Belts Heatmap",
  "  function renderSupplyInflowHeatmap() {",
  "    const container = document.getElementById('supply-inflow-container');",
  "    if (!container) return;",
  "",
  "    const belts = [",
  "      { name: 'Nashik Onion & Grape Belt', mandi: 'Lasalgaon & Pimpalgaon', crop: 'Red Onion, Grapes', volume: '8,950 Qt', pct: 88, status: 'Surge Arrival', color: '#166534' },",
  "      { name: 'Pune Junnar Tomato Corridor', mandi: 'Narayangaon & Manchar', crop: 'Hybrid Tomato, Cabbage', volume: '6,200 Qt', pct: 78, status: 'Heavy Supply', color: '#0c5a36' },",
  "      { name: 'Khandesh Banana Belt', mandi: 'Raver & Jalgaon APMC', crop: 'Grand Naine Banana', volume: '4,600 Qt', pct: 70, status: 'Steady Inflow', color: '#0284c7' },",
  "      { name: 'Marathwada Oilseed Cluster', mandi: 'Latur Mega Silos', crop: 'Soybean, Pulses, Jowar', volume: '9,400 Qt', pct: 92, status: 'Storage Peak', color: '#7c3aed' },",
  "      { name: 'Vidarbha Citrus & Cotton', mandi: 'Katol, Amravati, Kalamna', crop: 'Nagpur Orange, Raw Cotton', volume: '5,800 Qt', pct: 65, status: 'Fresh Harvest', color: '#ea580c' }",
  "    ];",
  "",
  "    container.innerHTML = belts.map(b => `",
  "      <div style=\"margin-bottom: 14px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px 14px;\">",
  "        <div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;\">",
  "          <div>",
  "            <strong style=\"font-size: 0.88rem; color: #0f172a;\">\${b.name}</strong>",
  "            <span style=\"font-size: 0.74rem; color: #64748b; display: block;\">📍 \${b.mandi} • \${b.crop}</span>",
  "          </div>",
  "          <div style=\"text-align: right;\">",
  "            <strong style=\"font-size: 0.9rem; color: \${b.color};\">\${b.volume}</strong>",
  "            <span style=\"font-size: 0.7rem; color: #166534; font-weight: 700; background: #e8f5ed; padding: 1px 6px; border-radius: 4px; display: inline-block;\">\${b.status}</span>",
  "          </div>",
  "        </div>",
  "        <div style=\"background: #e2e8f0; height: 6px; border-radius: 999px; overflow: hidden;\">",
  "          <div style=\"width: \${b.pct}%; height: 100%; background: \${b.color}; border-radius: 999px;\"></div>",
  "        </div>",
  "      </div>",
  "    `).join('');",
  "  }",
  "",
  "  // Render Right Column: AI Procurement & Arbitrage Advisory",
  "  function renderAiProcurementAdvisories() {",
  "    const container = document.getElementById('ai-advisory-container');",
  "    if (!container) return;",
  "",
  "    const commodity = COMMODITY_INSIGHTS[activeCommodity];",
  "    if (!commodity) return;",
  "",
  "    container.innerHTML = `",
  "      <div style=\"background: #f0fdf4; border: 1.5px solid #bbf7d0; border-radius: 12px; padding: 16px; margin-bottom: 14px;\">",
  "        <div style=\"display: flex; align-items: center; gap: 8px; margin-bottom: 8px;\">",
  "          <span style=\"font-size: 1.2rem;\">🤖</span>",
  "          <strong style=\"color: #065f46; font-size: 0.95rem;\">AI Procurement Action Plan: \${commodity.name}</strong>",
  "        </div>",
  "        <p style=\"font-size: 0.82rem; color: #166534; line-height: 1.5; margin: 0 0 12px 0;\">",
  "          \${commodity.recommendation}",
  "        </p>",
  "        <div style=\"display: flex; gap: 8px; flex-wrap: wrap;\">",
  "          <button class=\"btn btn-primary btn-sm\" onclick=\"switchView('view-verified-produce')\" style=\"background: #0c5a36; border-color: #0c5a36; font-weight: 700;\">",
  "            Browse Verified \${commodity.name.split('(')[0]} Lots &rarr;",
  "          </button>",
  "          <button class=\"btn btn-outline btn-sm\" onclick=\"openDistrictMatrixModal('\${commodity.key}')\" style=\"font-size: 0.76rem; border-color: #0c5a36; color: #0c5a36;\">",
  "            🗺️ All District Rates for \${commodity.name.split('(')[0]}",
  "          </button>",
  "        </div>",
  "      </div>",
  "",
  "      <div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-size: 0.8rem;\">",
  "        <div style=\"background: #ffffff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px;\">",
  "          <span style=\"color: #64748b; font-size: 0.72rem; display: block; text-transform: uppercase;\">Direct Sourcing Spread</span>",
  "          <strong style=\"font-size: 1.05rem; color: #0c5a36;\">Save ₹ \${((commodity.terminalVashiQt - commodity.farmGateQt) / 100).toFixed(2)} /kg</strong>",
  "          <div style=\"font-size: 0.7rem; color: #64748b; margin-top: 2px;\">vs Vashi APMC middleman rate</div>",
  "        </div>",
  "        <div style=\"background: #ffffff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px;\">",
  "          <span style=\"color: #64748b; font-size: 0.72rem; display: block; text-transform: uppercase;\">Optimal Sourcing Window</span>",
  "          <strong style=\"font-size: 1.05rem; color: #1e3a8a;\">Next 3–5 Days</strong>",
  "          <div style=\"font-size: 0.7rem; color: #64748b; margin-top: 2px;\">Before festive demand uptick</div>",
  "        </div>",
  "      </div>",
  "    `;",
  "  }",
  "",
  "  // Render Maharashtra Mandis Real-Time Table with 5-by-5 Pagination",
  "  function renderMaharashtraMandisTable() {",
  "    const tbody = document.getElementById('insights-mandis-tbody') || document.getElementById('maharashtra-mandis-tbody');",
  "    if (!tbody) return;",
  "",
  "    const filtered = MAHARASHTRA_MANDIS_TABLE.filter(item => {",
  "      if (tableDistrictFilter !== 'all' && item.district.toLowerCase() !== tableDistrictFilter.toLowerCase()) return false;",
  "      if (tableSearchQuery) {",
  "        const text = `\${item.crop} \${item.mandi} \${item.district}`.toLowerCase();",
  "        if (!text.includes(tableSearchQuery)) return false;",
  "      }",
  "      return true;",
  "    });",
  "",
  "    const paginationContainer = document.getElementById('insights-table-pagination');",
  "",
  "    if (filtered.length === 0) {",
  "      tbody.innerHTML = `<tr><td colspan=\"7\" style=\"text-align:center; padding: 30px; color:#64748b;\">No APMC mandis found in \${tableDistrictFilter !== 'all' ? tableDistrictFilter : 'search query'}. Select another district or search.</td></tr>`;",
  "      if (paginationContainer) paginationContainer.style.display = 'none';",
  "      return;",
  "    }",
  "",
  "    const visibleItems = filtered.slice(0, tableVisibleCount);",
  "",
  "    tbody.innerHTML = visibleItems.map(item => `",
  "      <tr style=\"border-bottom: 1px solid #f1f5f9; transition: background 0.15s ease;\">",
  "        <td style=\"padding: 12px 14px;\">",
  "          <div style=\"display: flex; align-items: center; gap: 10px;\">",
  "            <span style=\"font-size: 1.3rem;\">\${item.emoji}</span>",
  "            <div>",
  "              <strong style=\"color: #0f172a; font-size: 0.88rem;\">\${item.crop}</strong>",
  "              <div style=\"font-size: 0.72rem; color: #64748b;\">📍 \${item.mandi} (\${item.district}, MH)</div>",
  "            </div>",
  "          </div>",
  "        </td>",
  "        <td style=\"padding: 12px 14px;\">",
  "          <strong style=\"color: #0f172a; font-size: 0.88rem;\">\${item.arrivalsQt.toLocaleString('en-IN')} Qt</strong>",
  "          <div style=\"font-size: 0.7rem; color: #64748b;\">(\${item.arrivalsKg.toLocaleString('en-IN')} kg)</div>",
  "        </td>",
  "        <td style=\"padding: 12px 14px; font-size: 0.82rem; color: #64748b;\">",
  "          \${formatInsightPrice(item.minPriceQt)}",
  "        </td>",
  "        <td style=\"padding: 12px 14px;\">",
  "          <strong style=\"font-size: 0.95rem; color: #0c5a36;\">\${formatInsightPrice(item.modalPriceQt)}</strong>",
  "          <span class=\"badge \${item.trend === 'up' ? 'badge-grade-green' : 'badge-grade-blue'}\" style=\"font-size: 0.68rem; font-weight: 800; margin-left: 4px;\">",
  "            \${item.trendText}",
  "          </span>",
  "        </td>",
  "        <td style=\"padding: 12px 14px; font-size: 0.82rem; color: #64748b;\">",
  "          \${formatInsightPrice(item.maxPriceQt)}",
  "        </td>",
  "        <td style=\"padding: 12px 14px;\">",
  "          <div style=\"font-weight: 800; color: #166534; font-size: 0.88rem;\">+\${item.savingsPct}% Spread</div>",
  "          <span style=\"font-size: 0.72rem; color: #64748b;\">(Save \${formatInsightPrice(item.savingsQt)})</span>",
  "        </td>",
  "        <td style=\"padding: 12px 14px; text-align: right;\">",
  "          <div style=\"display: flex; gap: 6px; justify-content: flex-end;\">",
  "            <button class=\"btn btn-outline btn-sm\" onclick=\"openDistrictMatrixModal('\${item.cropKey}')\" style=\"font-size: 0.72rem; padding: 4px 8px; border-color: #0c5a36; color: #0c5a36;\" title=\"View All District Rates\">",
  "              🗺️ Districts",
  "            </button>",
  "            <button class=\"btn btn-outline btn-sm\" onclick=\"selectInsightCommodity('\${item.cropKey}'); window.scrollTo({top: 0, behavior: 'smooth'});\" style=\"font-size: 0.72rem; padding: 4px 8px;\" title=\"View AI Chart\">",
  "              📈 Chart",
  "            </button>",
  "            <button class=\"btn btn-primary btn-sm\" onclick=\"switchView('view-verified-produce')\" style=\"font-size: 0.72rem; padding: 4px 8px; background: #0c5a36;\" title=\"Buy from Farmers\">",
  "              Direct Buy",
  "            </button>",
  "          </div>",
  "        </td>",
  "      </tr>",
  "    \`).join('');",
  "",
  "    if (paginationContainer) {",
  "      paginationContainer.style.display = 'flex';",
  "      paginationContainer.style.alignItems = 'center';",
  "      paginationContainer.style.gap = '10px';",
  "",
  "      let buttonsHtml = '';",
  "      if (tableVisibleCount < filtered.length) {",
  "        buttonsHtml += `",
  "          <button class=\"btn btn-outline\" onclick=\"showMoreMandis()\" style=\"font-weight: 700; font-size: 0.85rem; padding: 8px 20px; border-color: #0c5a36; color: #0c5a36; display: flex; align-items: center; gap: 8px; border-radius: 8px;\">",
  "            <span>Show More Crops (+5)</span>",
  "            <span style=\"background: #e8f5ed; color: #0c5a36; font-size: 0.75rem; padding: 2px 8px; border-radius: 999px;\">Showing \${visibleItems.length} of \${filtered.length}</span>",
  "          </button>",
  "        `;",
  "      } else {",
  "        buttonsHtml += `",
  "          <span style=\"font-size: 0.8rem; color: #64748b; font-weight: 600;\">✓ Showing all \${filtered.length} APMC entries</span>",
  "        `;",
  "      }",
  "",
  "      if (tableVisibleCount > 5) {",
  "        buttonsHtml += `",
  "          <button class=\"btn btn-outline\" onclick=\"showLessMandis()\" style=\"font-weight: 700; font-size: 0.85rem; padding: 8px 18px; border-color: #cbd5e1; color: #475569; display: flex; align-items: center; gap: 6px; border-radius: 8px; background: #ffffff;\">",
  "            <span>▲ Show Less (-5)</span>",
  "          </button>",
  "        `;",
  "      }",
  "",
  "      paginationContainer.innerHTML = buttonsHtml;",
  "    }",
  "  }",

  "  // Open District Price Comparison Matrix Modal",
  "  function openDistrictMatrixModal(cropKey) {",
  "    const modal = document.getElementById('modal-district-crop-matrix');",
  "    if (!modal) return;",
  "",
  "    const targetKey = cropKey || activeCommodity;",
  "    const commodity = COMMODITY_INSIGHTS[targetKey];",
  "    if (!commodity) return;",
  "",
  "    const emojiEl = document.getElementById('district-matrix-emoji');",
  "    const titleEl = document.getElementById('district-matrix-title');",
  "    const subEl = document.getElementById('district-matrix-subtitle');",
  "    const tbody = document.getElementById('district-matrix-tbody');",
  "    const countEl = document.getElementById('district-matrix-count');",
  "",
  "    if (emojiEl) emojiEl.textContent = commodity.emoji;",
  "    if (titleEl) titleEl.textContent = `All Maharashtra Districts APMC Price Matrix: \${commodity.name}`;",
  "    if (subEl) subEl.textContent = `Live APMC benchmark rates & arrival volumes across all producing districts for \${commodity.name.split('(')[0]}`;",
  "",
  "    const hubs = commodity.districtHubs || [];",
  "    if (countEl) countEl.textContent = `\${hubs.length} Districts Available`;",
  "",
  "    tbody.innerHTML = hubs.map(h => {",
  "      const kgPrice = (h.modalQt / 100).toFixed(2);",
  "      const minKg = (h.minQt / 100).toFixed(2);",
  "      const maxKg = (h.maxQt / 100).toFixed(2);",
  "      const savingsKg = ((commodity.terminalVashiQt - commodity.farmGateQt) / 100).toFixed(2);",
  "      return `",
  "        <tr style=\"border-bottom: 1px solid #f1f5f9;\">",
  "          <td style=\"padding: 12px 14px;\">",
  "            <strong style=\"color: #0f172a; font-size: 0.9rem;\">📍 \${h.district} District</strong>",
  "            <div style=\"font-size: 0.74rem; color: #64748b;\">\${h.mandi}</div>",
  "          </td>",
  "          <td style=\"padding: 12px 14px;\">",
  "            <strong style=\"font-size: 1.05rem; color: #0c5a36;\">₹ \${kgPrice} /kg</strong>",
  "          </td>",
  "          <td style=\"padding: 12px 14px; font-weight: 700; color: #1e293b;\">",
  "            ₹ \${h.modalQt.toLocaleString('en-IN')} /Qt",
  "          </td>",
  "          <td style=\"padding: 12px 14px; font-size: 0.78rem; color: #64748b;\">",
  "            ₹ \${minKg} – ₹ \${maxKg} /kg",
  "          </td>",
  "          <td style=\"padding: 12px 14px; font-weight: 700; color: #0f172a;\">",
  "            \${h.arrivalsQt.toLocaleString('en-IN')} Qt",
  "          </td>",
  "          <td style=\"padding: 12px 14px;\">",
  "            <span class=\"badge badge-grade-green\" style=\"font-size: 0.72rem;\">+\${commodity.arbitragePct}% (Save ₹ \${savingsKg}/kg)</span>",
  "          </td>",
  "          <td style=\"padding: 12px 14px; text-align: right;\">",
  "            <button class=\"btn btn-primary btn-sm\" onclick=\"closeDistrictMatrixModal(); switchView('view-verified-produce');\" style=\"font-size: 0.72rem; padding: 4px 10px; background: #0c5a36;\">",
  "              Procure Lot",
  "            </button>",
  "          </td>",
  "        </tr>",
  "      `;",
  "    }).join('');",
  "",
  "    modal.style.display = 'flex';",
  "  }",

  "  function openCurrentDistrictMatrixModal() {",
  "    openDistrictMatrixModal(activeCommodity);",
  "  }",

  "  function closeDistrictMatrixModal() {",
  "    const modal = document.getElementById('modal-district-crop-matrix');",
  "    if (modal) modal.style.display = 'none';",
  "  }",

  "  function filterDistrictMatrixSearch(query) {",
  "    const q = (query || '').trim().toLowerCase();",
  "    const rows = document.querySelectorAll('#district-matrix-tbody tr');",
  "    rows.forEach(r => {",
  "      const text = r.textContent.toLowerCase();",
  "      r.style.display = text.includes(q) ? '' : 'none';",
  "    });",
  "  }",

  "  function showMoreMandis() {",
  "    tableVisibleCount += 5;",
  "    renderMaharashtraMandisTable();",
  "  }",

  "  function showLessMandis() {",
  "    tableVisibleCount = Math.max(5, tableVisibleCount - 5);",
  "    renderMaharashtraMandisTable();",
  "  }",

  "  function resetMandisTableCount() {",
  "    tableVisibleCount = 5;",
  "    renderMaharashtraMandisTable();",
  "  }",

  "  function formatInsightPrice(priceQt) {",
  "    if (activePriceUnit === 'kg') {",
  "      const kg = (priceQt / 100).toFixed(2);",
  "      return `₹ \${kg} /kg`;",
  "    }",
  "    return `₹ \${priceQt.toLocaleString('en-IN')} /Qt`;",
  "  }",

  "  function handleMandiTableSearch(val) {",
  "    tableSearchQuery = (val || '').trim().toLowerCase();",
  "    tableVisibleCount = 5;",
  "    renderMaharashtraMandisTable();",
  "  }",

  "  function filterMandiDistrict(dist) {",
  "    tableDistrictFilter = dist;",
  "    tableVisibleCount = 5;",
  "    renderMaharashtraMandisTable();",
  "  }",

  "  function triggerMandiSync() {",
  "    const icon = document.getElementById('mandi-sync-icon');",
  "    if (icon) icon.style.animation = 'spin 1s linear infinite';",

  "    showToast('Connecting to e-NAM & Maharashtra APMC Mandi Servers...', 'info');",

  "    setTimeout(() => {",
  "      if (icon) icon.style.animation = 'none';",
  "      updateLiveTimestamp();",
  "      renderProduceSelectorChips();",
  "      renderInsightChart();",
  "      renderInsightSummaryCards();",
  "      renderMaharashtraMandisTable();",
  "      showToast('✓ Mandi arrival volumes & live auction benchmarks synchronized!', 'success');",
  "    }, 900);",
  "  }",

  "  function updateLiveTimestamp() {",
  "    const el = document.getElementById('mandi-live-timestamp');",
  "    if (el) {",
  "      const now = new Date();",
  "      el.textContent = `Synced: Today at \${now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} • e-NAM & APMC Live`;",
  "    }",
  "  }",

  "  // Export to window",
  "  window.initBuyerMarketInsights = initBuyerMarketInsights;",
  "  window.selectInsightCommodity = selectInsightCommodity;",
  "  window.selectInsightCategory = selectInsightCategory;",
  "  window.setInsightTimeframe = setInsightTimeframe;",
  "  window.setInsightPriceUnit = setInsightPriceUnit;",
  "  window.handleMandiTableSearch = handleMandiTableSearch;",
  "  window.filterMandiDistrict = filterMandiDistrict;",
  "  window.showMoreMandis = showMoreMandis;",
  "  window.showLessMandis = showLessMandis;",
  "  window.resetMandisTableCount = resetMandisTableCount;",
  "  window.triggerMandiSync = triggerMandiSync;",
  "  window.openDistrictMatrixModal = openDistrictMatrixModal;",
  "  window.openCurrentDistrictMatrixModal = openCurrentDistrictMatrixModal;",
  "  window.closeDistrictMatrixModal = closeDistrictMatrixModal;",
  "  window.filterDistrictMatrixSearch = filterDistrictMatrixSearch;",

  "})();",
  ""
];

const targetPath = path.resolve(__dirname, '..', 'buyer-module', 'js', 'insights.js');
fs.writeFileSync(targetPath, jsLines.join('\n'), 'utf8');
console.log('Successfully generated multi-district buyer-module/js/insights.js!');
